### ISSUE TITLE
Wrong handling of SVG links

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#103]
Take `xlink:href` instead of `href` attribute for SVG links.

**Comment by mathisonian** [comment]
I'm running into this issue - do you know of any workaround/hack or have ideas for how to fix it? Happy to work on a PR if needed.

I tried also giving my SVG links `href` props in addition to `xlink:href`, but that didn't seem to work.

**Comment by gmrchk** [comment]
Hi @mathisonian, sorry about the delay, somehow missed your comment. 

How about creating a click listener for such SVG links and using swup API ([loadPage](https://github.com/gmrchk/swup#api) method) to load the page?

**Comment by mathisonian** [comment]
That's a good idea - thanks @gmrchk! I'll try it out

**Comment by gmrchk** [comment]
Should be fixed in v2.
