### ISSUE TITLE
Does Swup and Gia work with static websites?

### ISSUE THREAD

**Issue by alcantara** [swup/swup#105]
Does swup and gia work with static webpages? Or does it require backend processing?

For example, does swup and gia work well with github pages?

**Comment by panayotov** [comment]
I've tested it with static website ( compiled Nunjacks templates + Swup + GIA~ish components ) and deployed to firebase, works like a charm.

**Comment by gmrchk** [comment]
swup is actually mainly made as a plug&play solution with no setup required on a server, therefore you won't have any problem implementing with building tools and GH pages. It can also be easily modified to work with custom responses from a server if you need to.

One thing to take into consideration regarding GH pages it that all the project are hosted on one domain (unless you set up your own), which means that any custom [page transitions based on routes](https://github.com/gmrchk/swup#how-it-works) won't work as it does in a usual local environment with projects hosted at root (localhost/).
