### ISSUE TITLE
swupMergeHeadPlugin Not Triggering New Scripts

### ISSUE THREAD

**Issue by AugmentBLU** [swup/swup#129]
Hi, I'm using swupMergeHeadPlugin in my main swup call but it is not triggering new scripts that arrive in the header. I have tried setting the `runScripts` option in the swup call and hard coded it it in the plugin file itself but the scripts are being ignored.

I can see a simple console log call arriving in the head of the page after the content has been replaced but it is not triggering. 

I have a dynamic site that requires variables from certain pages that cannot be set at the site index. I cannot get the variables to the right JS functions without a page refresh, however the swupMergeHeadPlugin should be the answer to my needs but it is not triggering the scripts. 

I should add that the scripts I'm adding are not standalone JS files but will be embedded in HTML/PHP files as they will need variables based on user data.

```
<script type="text/javascript">
console.log('Hello World');
var name = "<?= $this->user->name ?>";
</script>
```

I tried debugging the plugin using `console.log(currentHead, newHead);` and the currentHead does show all the header scripts etc that were pulled through, newHead is completely empty so `newHead.querySelectorAll('script').forEach` function is not doing anything. Although the debug does show `Removed 1 / added 1 tags in head` but still not triggering. 

Any ideas?

**Comment by gmrchk** [comment]
I will try to debug this and see what is happening in the plugin, but the truth is that I have personally never used it and I discourage anyone who wants to use it.

I believe it's a completely wrong way of handling your JS. As you are kind of transforming your website into a single page application, your scripts should be written accordingly.

How about using the swup events for running your JS at the right time instead?

**Comment by AugmentBLU** [comment]
Yeah I agree with you on this, however I'm using this in dynamic backend area where other scripts are loaded in when components require them, this is why I was looking at the plugin. I don't want to alter the core backend if there was a way to trigger the JS using the swupMergeHeadPlugin.

**Comment by gmrchk** [comment]
Interesting. Could you elaborate on the components requiring other scripts or provide some demo? Maybe we can come up with some other workaround. I really don't want people to use this plugin and won't have time to look into it any time soon. 😐

**Comment by AugmentBLU** [comment]
An example is when loading a page with a richtext component. The CMS loads Froala Editor scripts only when a specific page requires them. The issue I discovered is that depending on how many levels deep the navigation was, a different result was reached on whether or not the scripts were triggered. It was very weird and unreliable.

For now, I've complied all the scripts required so they're also available on load. This does mean that scripts are still loaded in even though their in the new complied JS file but at least it works until I get a better solution.

**Comment by gmrchk** [comment]
The CMS you are referring to is probably only accessible to you as a logged in user, isn't it? If so, how about disabling swup for logged in users all together? It's definitely possible to make it work with a CMS, but I guess it's not going to be a pleasant task to do, nor really useful unless I misunderstood your motivation. 

I don't think a merge-head plugin is really a good solution for such a task anyway. Did/would you consider using bundler with a dynamic import to get packages like Froala Editor when you need to, and let bundler separate the code? [Gia](https://github.com/giantcz/gia#require) and the component kind of approach would definitely work nicely for something like this.

**Comment by gmrchk** [comment]
swupMergeHeadPlugin is now deprecated. 

You can try using [scripts plugin](https://swup.js.org/plugins/scripts-plugin) with swup v2 instead, but the suggestion mentioned previously seem like a better option.
