### ISSUE TITLE
Is it possible to hide /index.html from url?

### ISSUE THREAD

**Issue by k6jge3jf10o7** [swup/swup#137]
Navigating back to home page adds index.html to url. Is it possible to get rid of it and have a clean url?

**Comment by gmrchk** [comment]
Hi, this definitely can be faked with `replaceState` with some extra options like the ones used [here](https://github.com/gmrchk/swup/blob/master/src/index.js#L217), but I think the problem should be solved on the server side, which likely sends back this URL to swup.

**Comment by gmrchk** [comment]
Will close this as it's most likely not a swup issue. Swup set's URL with anything it's given.

Note: Services like Netlify can "fake" you sites structure and remove the `.html` files extensions for you.
