### ISSUE TITLE
Please help a beginner

### ISSUE THREAD

**Issue by athmihir** [swup/swup#138]
Hi! I'm new to javascript and wanted to learn to add page transitions to a website i'm creating using flask. While searching i came across swup and it seemed to be easier than learning how to use those fancy libraries.
The thing is, after adding swup it seems to work but a few of my pages that have other javascript scripts dont seem to be working unless i reload the page using ctrl+r. Also some of the data in my pages and my javascript is not static and should change with my backend as i pass it to the templates via my flask render template function.
So i need swup to refresh the page each time i transition onto a new page so that the javascript as well as the new data from the backend can be reloaded onto the page.
I tried: 
```javascript
let options = { cache: false }
const swup = new Swup(options);
```

But it still wont refresh the entire page

So then i considered using swupjs since i could do that manually by using `window.location.reload` But swupjs is not working for some reason. 
i created a script which i wanted to run called it myswup.js
Did that: `<script src="{{ url_for('static', filename='js/myswup.js') }}"></script>`

Now inside myswup.js:
```javascript
let options = {
    animations: {
        'login>register': {
            in: function(next){
                document.querySelector('#swup').style.opacity = 0;
                TweenLite.to(document.querySelector('#swup'), .5, {
                    opacity: 1,
                    onComplete: next
                });
            },
            out: function(next){
                document.querySelector('#swup').style.opacity = 1;
                TweenLite.to(document.querySelector('#swup'), .5, {
                    opacity: 0,
                    onComplete: next
                });
            }
        },
    }
}

const swupjs = new Swupjs(options);
```

The gsap is working properly individually.
But the above code seems stuck.
Also if i put anything after that code it does not run.
Maybe im a bit inexperienced in this what are your thoughts?
Thanks really appreciate it!

**Comment by gmrchk** [comment]
Hi @athmihir, I won't go into detail, but I think the main thing that you're struggling with is reloading of your javascript code. [This thread](https://github.com/gmrchk/swup/issues/41) should give you some more info on that. Let me know if it helps.

**Comment by athmihir** [comment]
okay some changes.. The swupjs is working now (i had the imports wrong yikes!).
Now,


let options = {
    animations: {
        'register>login': {
            in: function(next){
                document.querySelector('#swup').style.opacity = 0;
                TweenMax.to(document.querySelector('#swup'), .5, {
                    opacity: 1
                });
                window.location.reload(1);
                next()

            },
            out: function(next){
                document.querySelector('#swup').style.opacity = 1;
                TweenMax.to(document.querySelector('#swup'), .5, {
                    opacity: 0
                });
                next()
            }
        },
        'login>register': {
            in: function(next){
                document.querySelector('#swup').style.opacity = 0;
                TweenMax.to(document.querySelector('#swup'), .5, {
                    opacity: 1
                });
                window.location.reload(1);
                next()
            },
            out: function(next){
                document.querySelector('#swup').style.opacity = 1;
                TweenMax.to(document.querySelector('#swup'), .5, {
                    opacity: 0
                });
                next()
            }
        },
    }
}

const swupjs = new Swupjs(options);

is what I am running, and the transition works when the window.reload is not present.
 I want to refresh the page after the transition is done so that the dynamic elements
of the page can be reloaded. When I add window.reload as shown above, the transition wont work and the page just redirects to the respective templates like it normally would without the transition.
Also when I turn off cache, the same no transition thing.

Now you suggested reloading your javascript and i'll try that, but why do you have to do so?
Why doesn't swup run the javascript code present in the other template like it normally would when you click a link to another page?
Suppose I am in the login template initially, I click a link on the page to go to the register 
template. I get a nice transiton. In the register template I have a javascript code. I want it to run as i am
in the register template, but instead it does not run (or some older script is running) for that i need to press ctrl + r.
All I want is a nice transition to another html page running the way it is.
But instead i get transported to a mirror world where everything in the template matches except the template is not a fresh reloaded template with new data, it is an old one.

What are your thoughts? You could go a bit in detail as it would be a big help
Sorry if i am asking very trivial questions as i'm new to this.
Thank you for your time!

**Comment by gmrchk** [comment]
That's basically not how the browser works. In order to create page transitions, you need to prevent the native browser refresh, but by removing the refresh, all the other scripts need to be disabled, and new ones loaded manually. It is what is, and there is no way around it...

If you'd like your scripts on each page to just run, you can check out new [scripts plugin](https://swup.js.org/plugins/scripts-plugin), which will do exactly that. Keep in mind that all your old scripts will still be running on the page and that's just not right, so it's better to invest into writing your scripts properly for the page transitions.

I have also put together a [small section](https://swup.js.org/getting-started/reloading-javascript) in docs about re-running scripts. Not sure if any of the info is new tho.

Closing to make space for issues of new version 2. Also not a swup issue.
