### ISSUE TITLE
Module not found: Error: Can't resolve './getDataFromHTML'

### ISSUE THREAD

**Issue by davidnash** [swup/swup#141]
I'm getting the following errors from webpack:
```
ERROR in ./node_modules/swup/lib/helpers/index.js
Module not found: Error: Can't resolve './getDataFromHTML' in '/var/www/disciple-webview-apps/node_modules/swup/lib/helpers'
 @ ./node_modules/swup/lib/helpers/index.js 16:23-51
 @ ./node_modules/swup/lib/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/swup/lib/index.js
Module not found: Error: Can't resolve './modules/cache' in '/var/www/disciple-webview-apps/node_modules/swup/lib'
 @ ./node_modules/swup/lib/index.js 18:13-39
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```
It's strange that it's just these two - it's not complaining about any of the other modules in `lib/heplers/index.js`

This is right after installing - I did `npm install swup`, added `import Swup from 'swup';` to my app.js and then did `npm run dev`, which outputs the errors above.

This is a Laravel project, and I get the same error on a fresh install too.

Thanks for your help!

**Comment by jamie-jenks** [comment]
I'm experiencing the same issue after updating to 2.0.2

**Comment by gmrchk** [comment]
Sorry guys, my bad. Seems like some lowercase/uppercase mismatch in the imports...
Please update swup and everything should be fine now.

Out of curiosity, which system/bundler are you running? Mac with webpack doesn't seem to mind wrong names (which it really should).

Thanks for reporting!

**Comment by davidnash** [comment]
> which system/bundler are you running?
Ubuntu 19.04 and webpack

**Comment by jamie-jenks** [comment]
> Out of curiosity, which system/bundler are you running? Mac with webpack doesn't seem to mind wrong names (which it really should).

I was using macOS Mojave 10.14.2 - which worked fine for local development.

When deploying using a Buddy.works (deployment tool), that's when I was experiencing the issue.
