### ISSUE TITLE
Where are plugin files for download?

### ISSUE THREAD

**Issue by AdventurouslySocial** [swup/swup#142]
I do not see any plugin files within the dist folder where the documentation says to find them. Where does one go to download the actual plugin files themselves? I'm specifically looking for the SwupHeadPlugin.js file, but I would like access to all of them for use in experimentation. Thanks in advance.

**Comment by AdventurouslySocial** [comment]
Found them. I just didn't see them being clearly linked to.

For anyone else in the future believing the files to be linked for download from https://swup.js.org/plugins - please navigate to **https://github.com/swup/name-of-plugin-you-want** (i.e. https://github.com/swup/body-class-plugin )

**Comment by gmrchk** [comment]
All repos can be found under [swup organization](https://github.com/swup). 
I've included the info here on main [swup repo](https://github.com/swup/swup) now as well.

Cheers
