### ISSUE TITLE
Theme usage

### ISSUE THREAD

**Issue by Grafikart** [swup/swup#143]
I'm trying swup and followed the example 

## The code

Content wrapper with 

```html
<div id="swup" class="transition-fade">
</div>
```

Swup is imported

```js
import Swup from 'swup';
const swup = new Swup();
```

And I added the CSS. Everything works as expected

## The problem

Than I read the "theme" part of the documentation and chose to change my JS

```js
const swup = new Swup({
  theme: [new SwupOverlayTheme()]
});
```

But I don't see the overlay animation. Am I missing an extra step ? (I should add a class somewhere ?)
The theme option is not documented here : https://swup.js.org/options
And I don't get why this is an array (I guess we can have multiple theme but how do we toggle them ?
I think this page https://swup.js.org/themes lack some informations ;)

Thanks for your work I'm currently trying to replace turbolink with your library

**Comment by gmrchk** [comment]
Themes are essentially plugins, and that can also be seen on their usage. To include a theme, use it in the `plugins` option.

```javascripts
const swup = new Swup({
  plugins: [new SwupOverlayTheme()]
});
``` 

I see that this option is missing in the options page as well, so I will add that. No extra step should be needed. 

I will also make the theme page a bit clearer on the usage (include an example with plugins options).

Thank you for reporting!

**Comment by Grafikart** [comment]
Indeed it works as expected if I replace themes: by plugins: (I'll try to PR the doc if I have time).
