### ISSUE TITLE
lib folder is ignored but referenced in package.json

### ISSUE THREAD

**Issue by tedw** [swup/swup#148]
The lib folder is currently bring ignored:
https://github.com/swup/swup/blob/be428e6e3279d0b122b2c5c71706ef05e4ed7339/.gitignore#L16

But the main file in `package.json` is in the lib folder:
https://github.com/swup/swup/blob/be428e6e3279d0b122b2c5c71706ef05e4ed7339/package.json#L5

Is there another step you’re taking to publish the lib folder to npm? I’m unclear how this works.

Thanks for the help!

**Comment by gmrchk** [comment]
Hi, NPM has it's own ignore file [.npmignore](https://github.com/swup/swup/blob/master/.npmignore), where the folder is not listed. `.gitignore` only applies to git, where the folder is simply unnecessary.

**Comment by tedw** [comment]
Ah, ok, thanks. I was linking to my fork in package.json using the GitHub URL, which is why I was missing the lib folder.

Appreciate the reply, sorry for the false alarm issue!
