### ISSUE TITLE
Cannot set property 'responseURL' of null

### ISSUE THREAD

**Issue by pixelsaft** [swup/swup#152]
We would include Swup. After we add

`const swup = new Swup(); // only this line when included with script tag
`

  into an external js file (swup.config.js), we got this error:

```
swup.js:363 Uncaught TypeError: Cannot set property 'responseURL' of null
at Swup.enable (swup.js:363)
    at new Swup (swup.js:343)
    at swup.config.js:30
enable @ swup.js:363
Swup @ swup.js:343
(anonymous) @ swup.config.js:30
```
Has anyone an idea how can we fix the issue?

**Comment by tzeller** [comment]
same issue... wired.. i have only the problem with tailwind - with another css-framework it does not exist?

**Comment by tzeller** [comment]
found the issue... when you set an id for swup e.g. #nav and you won't have this id in your source.. you will get this error...

**Comment by gmrchk** [comment]
Yes, this is most likely wrong settings, eg. some id is missing on the element. Detection for this would be useful in a debug plugin. 

I have created an issue for this [here](https://github.com/swup/debug-plugin/issues/2) and will implement once I have some time. Anyone is welcome to create PR too.

**Comment by brandlewco** [comment]
@gmrchk If you used Swup before the update you used to define it as:
`const options = {
  elements: ["#content"],
}`

but it is now called **containers**
`const options = {
  containers: ["#content"],
}`

**Comment by rozza-m** [comment]
Not sure why this was closed. I just tried to use swup (which looks awesome btw) and encountered exactly the same thing.

I think the problem is with the docs, the installation page says to just drop that line in a script and you're done, when actually you need an element with the id of "swup".

**Comment by CFMazzarago** [comment]
why thi is closed? i have the same problem when i try to integrate swup into wordpress.

**Comment by QuirkyWallace** [comment]
Hello, I encountered the same issue on WordPress. I tried to define the container with a main content div that already exists in the theme I am using as well as adding my own div with the ID `#swup`. Still got the issue.

**Comment by moevbiz** [comment]
i'm encountering the same issue, and it isn't solved by either having an element with an id of `swup`, or by defining a different selector in the options.

**Comment by danielgroner** [comment]
In case anybody stumbling upon this issue. 
One reason this might be caused by is when you include the script in the head. 
Swup is then executing the script where it is searching for the element with the ID before this element is even rendered. 

Move your script to the end, before the closing body tag. This might solve your issue.

**Comment by NayeemHR** [comment]
When I was creating a theme, I had the same problem. I solved that problem by adding this line  'menu_id' => 'swupMenu'  to the wp_nav_menu() .

**Comment by CrownKingClown** [comment]
had the same problem, forgot to include the .css file in one of my head tags
