### ISSUE TITLE
Cache Control

### ISSUE THREAD

**Issue by shotaMik** [swup/swup#153]
First of all, thank you for this amazing project!

I am trying to use Swup for page transitions Wordpress with Woocommerce Shop and still can't figure out solution with caching. 

**Is it somehow possible to exclude certain objects (maybe containers) or pages from Cache?** maybe you can use link attributes to exclude certain links from caching.

Thanks!

**Comment by gmrchk** [comment]
The cache can be disabled all together with [options](https://swup.js.org/options#cache).

But if you'd only like to prevent some pages from caching (/cart for example), you could use swup events to remove that page from cache on every `contentReplaced`.

```javascript
swup.on('contentReplaced', () => {
    swup.cache.remove('/cart');
});
```

More [here](https://swup.js.org/api/cache).

**Comment by shotaMik** [comment]
It works perfectly! Thank you!

**Comment by shotaMik** [comment]
Hello,

What I am trying to achieve is:

I am assigning revision version to page meta and after it caches certain page I want to make an ajax request to a server and check if there is new version available, if yes, clear cache for that page to fetch new version before page transition.

Is it possible to check meta tag of requested html and run it before "pageRetrievedFromCache" event?

Thanks
