### ISSUE TITLE
Please Help With Initializing Multiple Plugins

### ISSUE THREAD

**Issue by AdventurouslySocial** [swup/swup#154]
I have swup running and it's a wonderful project.

As a novice dev I lack the understanding of how to properly initialize more than one plugin at a time.

My current options are successfully setup to run a single plugin as follows:

    const options = {
        plugins: [new SwupHeadPlugin()],

	 LINK_SELECTOR:'a[href^="/"]:not([data-no-swup]), a[href^="' + window.location.origin + '"]:not([data-no-swup])'
    };
    const swup = new Swup(options);

My trouble begins when I attempt to use multiple plugins simultaneously. I have tried variations including the following (all wrong according to console, but the online docs don't spell it out clearly for someone who is using swup to get their coding toes wet like me.)

I've tried:

     const options = {
        plugins: [new SwupHeadPlugin()],
                  [new SwupBodyClassPlugin()],
      };
    const swup = new Swup(options);

I have tried:

    const options = {
        plugins: [new SwupHeadPlugin(),SwupBodyClassPlugin()],
      };
    const swup = new Swup(options);

I have even tried:

    const options = {
        plugins: [new SwupHeadPlugin()],
        plugins: [new SwupBodyClassPlugin()],
      };
    const swup = new Swup(options);

What is the correct manner for running multiple swup plugins together?

**Comment by gmrchk** [comment]
Hi, plugins option is an array of plugin instances.

```javascript
const options = {
    plugins: [
        new SwupHeadPlugin(),
        new SwupBodyClassPlugin()
    ],
 };
const swup = new Swup(options);
```

but honestly, if you're struggling with this, I would recommend going through some JavaScript basics before you dive into something more complex.
