### ISSUE TITLE
SwupScriptsPlugin Vs. SwupHeadPlugin

### ISSUE THREAD

**Issue by AdventurouslySocial** [swup/swup#155]
I have the understanding that the **_SwupHeadPlugin_** is deprecated and is to be replaced by the **_SwupScriptsPlugin_** instead.

My experience in using **_SwupHeadPlugin_**, is that navigation between swup enabled pages look great because all of page specfic stylesheets accompany the pages they belong to.

Without the **_SwupHeadPlugin_**, swup does transition between pages without console errors, but the incoming pages lack the page specific stylesheets necessary to present the pages properly.

So... even though **_SwupHeadPlugin_** is deprecated - here I am using it and unable to move away from doing so.

Which brings me to **_SwupScriptsPlugin_**.

When I run **_SwupScriptsPlugin_** I encounter two problems: one **_console_** related. One related to aesthetic functionality.

The **_console_** error is due to  **_SwupScriptsPlugin_** attempting to rerun swup.min.js itself upon navigation to a new page because swup.min.js is itself... a script.

Console reads:

    Uncaught SyntaxError: Identifier 'options' has already been declared

It is referring to:

    const options = {

	plugins: [new SwupScriptsPlugin()],

	 LINK_SELECTOR:'a[href^="/"]:not([data-no-swup]), a[href^="' + window.location.origin + '"]:not([data-no-swup])'
    };
    const swup = new Swup(options);

What am I doing incorrectly?

**Comment by gmrchk** [comment]
Hi, sorry for the late reply. 

I think there is some confusion here. `SwupHeadPlugin` is not deprecated, it's just new as there was a lot of breaking changes in v2.

Original SwupHeadPlugin is was basically replaced by two plugins, **SwupHeadPlugin** which does the job of merging the head tag contents, and **SwupScriptsPlugin** which takes care of re-running scripts. 

I think what you need is to run both plugins (SwupHeadPlugin first), and you need to avoid re-running script to enable swup again. Please, read the [docs](https://swup.js.org/plugins/scripts-plugin) for that.
