### ISSUE TITLE
Countdowns, Elements with Entrance Animations, & The Like Disappearing.

### ISSUE THREAD

**Issue by AdventurouslySocial** [swup/swup#156]
I have a countdown timer on my homepage. Upon first visit to the homepage the countdown timer is present. When I swup transition away from the homepage and then swup transition back to homepage the countdown digits of the timer are not present - all that is left visible are the static digit containers and the static labels for the digits.

This is indicative of the behavior I am seeing happen to any similar element on my pages that contain any of the following: an entrance animation, a dynamic component such as a timer, etc.)

I have attempted to use **_SwupScriptsPlugin_** as the solution, but this did not work.

I have also attempted to utilize the following which is a snippet I found in #81 

    swup.on('contentReplaced', () =>{
    $('#elementor-countdown-item').elementor-countdown-digits, elementor-countdown-days('destroy');
    
    });

The structure of the countdown itself is:
(The double asterisk marks the dynamic element that disappears upon swup navigation)

     <div id="#myCountdown class=".elementor-element elementor-element-5ac397b elementor-countdown--label-block elementor-widget elementor-widget-countdown">
        <div class="elementor-widget-container">
            <div class="elementor-countdown-wrapper">
                <div class="elementor-countdown-item">
                    **<span class="elementor-countdown-digits elementor-countdown-days"></span> 
                      <span class="elementor-countdown-label"></span> 
                </div> 

     </div> 

On swup navigation console reports:
    
    ReferenceError: countdown is not defined

I clearly understand that I am doing something wrong and that this is operator error. I am seeking Swup community guidance on how to fix this error and enable countdowns, elements with entrance animations, and the like to work as they do in the [https://swup.github.io/swup-gia-demo/index.html](url)

**Comment by gmrchk** [comment]
Hi, sorry for the delay! 
I'm not sure if you solved your issue, so I will try to help, but if you have, please post your solution here. 

First thing first, as this is not a valid JS code, there is probably some problem there. 
```javascript
swup.on('contentReplaced', () =>{
    $('#elementor-countdown-item').elementor-countdown-digits, elementor-countdown-days('destroy');
});
```

If you use some jQuey plugin, it would be helpful to see their docs, but in general, you are probably going for something like the following: 

```javascript
swup.on('contentReplaced', () =>{
    $('#elementor-countdown-item').countdown();
});

swup.off('willReplaceContent', () =>{
    $('#elementor-countdown-item').countdown('destroy');
});
```
