### ISSUE TITLE
Javascript carrying over to new page after content replace

### ISSUE THREAD

**Issue by Rickardo228** [swup/swup#160]
Hi there! First post on Github woop!

So I've written this piece of code that, on any page which doesn't have '.overlay', loads the index page upon scrolling to the top. This page load is initiated by auto clicking on '#button-three' (a link to the index page). See below:

```javascript
swup.on('contentReplaced', function() {
   var buttonThree = document.getElementById("button-three");
   if(document.querySelector('.overlay') != null) {
        window.onscroll = function() {
            $(function () {
                var $win = $(window);

                $win.scroll(function () {
                    if ($win.scrollTop() == 0)
                        buttonThree.click();
                 });
             });
         }
    }
});
```

This works great, the index page is loaded when a user reaches the top of the sub-page, as if the user clicked the button-three. 
However, the script seems to keep running and the page reloads if the user scrolls to the top of the index, despite there being no '.overlay' class or '#button-three' on the index page.
This only happens once before the page is returned to normal and scroll top no longer initiates a button click.

How can the index page even access a '.overlay' or '#button-three' from the previous page to enable the 'window.onscroll' script to keep running?
I lack a fundamental understanding on javascript events it seems!

Thanks in advance :)

**Comment by gmrchk** [comment]
Hi @Rickardo228, I totally missed your question, so sorry about a late reply. 

Good job on the description, especially given the first time! 👍 

I would avoid using `onscroll`, as this is a function browser will execute every time a scroll happens, which we want. However, every time we set `window.onscroll = ...`, we rewrite a previously set value. I would suggest using the `addEventListener` instead. 

`$(function () {...});` is unnecessary here. 

You are also setting scroll listener inside of an `onscroll`, which doesn't really make sense. 

What you are probably looking for is something like the following (not tested):

```javascript
var $win = $(window);
var scrollHandler = function () {
    if ($win.scrollTop() == 0) {
        var buttonThree = document.getElementById("button-three");    // this assumes the button is always in a page
        buttonThree.click();
        // this can also be replaced by a swup API call of loadPage method 
        // https://swup.js.org/api/methods
    }
};

swup.on('willReplaceContent', function() {
    $win.off('scroll', scrollHandler);
});

swup.on('contentReplaced', function() {
   if(document.querySelector('.overlay') == null) {
        $win.on('scroll', scrollHandler);
    }
});
```
