### ISSUE TITLE
linkSelector and target="_blank"

### ISSUE THREAD

**Issue by MMasey** [swup/swup#161]
Heyo, 

First off, fantastic project you've got going on here, loving your work 😄

I've been playing around with the `linkSelector` options when setting up swap, and when I set it up as followed to exclude any links with `target="_blank"`, it still handles the link with the swup animation.

`a[href^="${window.location.origin}"]:not([data-no-swup]):not([target="_blank"]), a[href^="/"]:not([data-no-swup]):not([target="_blank"]), a[href^="#"]:not([data-no-swup]):not([target="_blank"])`

I've checked each of the queries using a `document.querySelectorAll` to see what gets picked up and as far as I can tell it's correct. Is there a reason why the links are still being intercepted.

Taking this further, does it make sense to ignore all links with `target="_blank"` by default as this intercepts expected browser behaviour?

Thanks in advance.

**Comment by MMasey** [comment]
Scrap that, I've found the issue. I'm on version 1.9.0 and was looking at the docs for version 2 🤦‍♂️

For anyone else who's managed to do the same thing, the issue is that in version 1.9.x it's `LINK_SELECTOR` and in version 2, it's `linkSelector`.

**Comment by evromalarkey** [comment]
Shouldn't target="_blank" be ignored by default though? What's the expected behaviour here? @gmrchk

**Comment by stuartcusackie** [comment]
Two years later it seems target blank has to be ignore manually??

```
linkSelector:
  'a[href^="' +
  window.location.origin +
  '"]:not([data-no-swup]):not([target="_blank"]), ' +
  'a[href^="/"]:not([data-no-swup]):not([target="_blank"]), ' +
  'a[href^="#"]:not([data-no-swup]):not([target="_blank"])',
```

Same as OP's version. Not tested very well but looks fine to me.

**Comment by daun** [comment]
I've started constructing the selector from separate include/exclude settings. Easier to edit/update.

```js
// Valid links for swup navigation
const linkInclude = [
  `a[href^="${window.location.origin}"]`,
  `a[href^="/"]`,
  `a[href^="#"]`
]
// Links to skip for swup navigation
const linkExclude = [
  '[download]',
  '[target="_blank"]',
  '[data-no-swup]',
  `[href$=".pdf"]`
]

const exclude = linkExclude.map(selector => `:not(${selector})`).join('')
const linkSelector = linkInclude.map(include => `${include}${exclude}`).join(',')

const swup = new Swup({ linkSelector })
```
