### ISSUE TITLE
popState scroll position bug

### ISSUE THREAD

**Issue by MMasey** [swup/swup#164]
Hello,

I'm experience an off bug in Swup v2 in that when a person uses the browser back and forward history buttons they aren't taken to the correct previous scroll location. According to the docs the `animateHistoryBrowsing` default value is `false` which should mean that the browser handles all of the history related scroll positions but it keeps scrolling to the locations that the person was first on they they either visited the page, or reloaded it.

My current config is as followed.

```
const swup = new Swup({
	containers: ["#swup"],
	animationSelector: '[class*="swup-swipe"]',
	linkSelector: `a[href^="${window.location.origin}"]:not([data-no-swup]):not([target="_blank"]), a[href^="/"]:not([data-no-swup]):not([target="_blank"]), a[href^="#"]:not([data-no-swup]):not([target="_blank"])`,
	plugins: [
		new SwupGaPlugin(),
		new SwupPreloadPlugin(),
		new SwupFormsPlugin(),
		new SwupScrollPlugin({
			animateScroll: false
		})
	]
};);
```

I have tried disabile all the other JavaScript that is used on the site, as well as removing all of the plugins and the issue still seems to present itself. Has anyone else experienced this. I can't figure out if it's a bug with the core Swup code, or user error on my part.

Edit: Forgot to mention, i'm using the latest version of Chrome on Windows 10.

Thanks

**Comment by MMasey** [comment]
Manage to solve the issue, once again it was user error and some false positives on my end. 😝

That said i did have to implement this solution to get the scroll positioning saved on the popState - https://github.com/swup/swup/issues/48#issuecomment-423854819

**Comment by aerni** [comment]
@MMasey How did you solve this exactly? I'm still having an issue, where the scroll position is set to the saved value upon click on back/forward button, but then scrolling all the way to the top when the animation is done. #48

**Comment by tahola** [comment]
Same here, back button click result in bad scrolling position (if I am on the bottom of the page when I click the scroll position of the previous page will be the bottom too), anyway to fix that ?
