### ISSUE TITLE
Error: Cannot resolve module '@swup/body-class-plugin'

### ISSUE THREAD

**Issue by dayneh88** [swup/swup#165]
Hi,

Firstly! Love, love, loveeeee this package. It's soo easy to use.

I'm trying to install some plugins but running into errors during the build stage:

1. Have run "yarn add @swup/body-class-plugin --save" which works fine
2. Inside my component index.js file I've got "import SwupBodyClassPlugin from '@swup/body-class-plugin';"
3. When it tries to build it gives me the error:
"Error: Cannot resolve module '@swup/body-class-plugin'" yet I can see the folder inside my "node_modules" folder.

Any thoughts would be appreciated.

Thanks so much,
Dayne

**Comment by dayneh88** [comment]
Can anyone please shed some light on this issue? It's holding up our development on a project haha.

**Comment by gmrchk** [comment]
Hi and thanks!

It doesn't sound like an issue with swup or the plugin.
Did you try installing with npm instead? Maybe a build issue... what bundler (and stuff) is used in a setup? 

A repo/demo would be helpful so we can sort this out.
