### ISSUE TITLE
Reloading ReCaptcha script

### ISSUE THREAD

**Issue by MikeHarrison** [swup/swup#166]
Hi,
I am having the same issue as here: https://github.com/swup/swup/issues/98. I have the recaptcha script in the header (`<script src="https://www.google.com/recaptcha/api.js" defer></script>`), and the captcha appears and works if I load the page as normal. If I arrive to the page via Swup then the captcha does not appear.

I have tried this in my js:
```
document.addEventListener('swup:contentReplaced', function(){
  grecaptcha.reset();
});
```
But this gives me the following console error: `Error: No reCAPTCHA clients exist`. when I arrive at the page via Swup. This error is also appearing on other pages where there is not a form (but I guess I would expect that). If anyone has any pointers that would be great.

**Comment by gmrchk** [comment]
Hi, 

did you try using the [solution](https://github.com/swup/swup/issues/98#issuecomment-453612681) provided in that thread? 

Having the `defer` attribute on the recaptcha script tag could also cause problems.

**Comment by gmrchk** [comment]
As discussed over at #98, we were only able to make the reCaptcha v2 work so far. 

I have created a [repo](https://github.com/swup/recaptcha-plugin) for the plugin. I won't get to it this week at least, so if anyone wants to dig into it, please, create a PR.
