### ISSUE TITLE
Youtube API and Swup

### ISSUE THREAD

**Issue by MikeHarrison** [swup/swup#167]
Hi,

I am using the YouTube iframe API to load videos on my site. This is working fine when I load the page as normal, but not when I arrive on the page via Swup. There are no errors in the console, just nothing is happening. The setup I have is:

On the page I have:
```
<div id="player"></div>
```

At the end of my page I have:
```
<script src="/assets/js/youtube-min.js"></script>
<script src="/assets/js/app-min.js"></script>
```
`app-min.js` has most of my javascript in it, including swup. `youtube-min.js` looks like this:

```
var playerWrapper = document.getElementById("player");

  if(playerWrapper) {

      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          width: '1280',
          height: '720',
          playerVars: { 'autoplay': 1, 'controls': 0, 'showinfo': 0, 'rel': 0, 'playsinline': 1, 'modestbranding': 1, 'iv_load_policy': 3, 'showinfo': 0 },
          videoId: '6MqbczgkFag',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange,
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        player.mute();
        event.target.playVideo();
      }

      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.ENDED) {
          player.playVideo();
        }
        if(event.data == YT.PlayerState.PLAYING) {
          var thing = document.getElementById("player");
          thing.classList.add('show');
        }
      }
  }
```

When I arrive via Swup nothing happens, the iframe is not created or anything. If anyone has any thoughts on how I can sort this that would be great.

**Comment by 23d1** [comment]
The thing with AJAX is that you are not loading a new page, you are loading and replacing content within a page. This means that any javascript that is executed when you load a page would need to be run again for new pageloads. There's calls like "contentReplaced" and so forth, that SWUP listens for, and then executes the functions within that call.

So if you have that functionality nested into a function like this;
```
function youtubescript() {
    paste your script here...
}
```

then you could do
```
document.addEventListener('swup:contentReplaced', function(){
    youtubescript();
});
```

That would then run the script on every SWUP "page load".

**Comment by MikeHarrison** [comment]
Hi - thanks for the reply.

Before your edit:

I tried wrapping the functionality in a function but that hasn't worked. I dropped the function call into the `app.js` and also in a `swup:contentReplaced` listener - the function itself is running (checked with a `console.log`) and the script tag is being created in the `head` but the `onYouTubeIframeAPIReady()` function isn't being triggered, I guess maybe because it is nested?

After:

I am happy to hard-code the script tag and remove that from the javascript - the javascript is lifted straight from the implementation guide from Google. But I think I may still hit the issue of the subsequent functions not being triggered as they are wrapped in the `youtubescript()` function to allow me to put them into the swup listener.

**Comment by 23d1** [comment]
Hmm. Nesting, or wrapping into a function shouldn't affect it's ability to run. You have to also run it on page load, so you could try adding;
```
document.onreadystatechange = event => {
    if (document.readyState == "interactive") {
        youtubescript();
    }
}
```

**Comment by gmrchk** [comment]
Hi guys, 

creating multiple script tags is definitely unnecessary, so you can either separate that part of the code from the rest (that needs to be called on every page view) or hard code it with a script tag, as suggested. 
Keep in mind, that once you're executing your code for creating the player, youtube API must be loaded by then.

In your code snippet, you have a function that actually creates the player `onYouTubeIframeAPIReady`, but I don't see it ever being called. This is the function that should be executed on `contentReplaced` event.

```javascript
var swup = new Swup();
swup.on('contentReplaced', onYouTubeIframeAPIReady);
```

Keep in mind that you should again check for the element being in the page first.

```javascript
var swup = new Swup();

swup.on('contentReplaced', function () {
    var playerWrapper = document.getElementById("player");
    if(playerWrapper) {
        onYouTubeIframeAPIReady();
    }
});
```
---
As @23d1 suggests, placing an iframe into your page should work just fine as well, unless your video is dynamic or something.

**Comment by gmrchk** [comment]
Hi @MikeHarrison, any news on this?

**Comment by MikeHarrison** [comment]
Hi @gmrchk - unfortunately no. I ended up switching it out for a standard `<video>` element and hosting the video myself. Then I used the standard `autoplay` attribute to trigger playback.

**Comment by gmrchk** [comment]
I guess that's a way too 👍 let's close this.
