### ISSUE TITLE
Animation selector "swup-" doesn't work

### ISSUE THREAD

**Issue by aerni** [swup/swup#173]
I would like to use `swup-` instead of `transition-` as the animation selector. Using the following options doesn't work though: `animationSelector: '[class*="swup-"]'`.

I'm now using this selector as a workaround `animationSelector: '[class*="page-transition-"]'`. This works with no problems.

Is the `swup-` class reserved in some way? Is there a reason why it shouldn't work?

**Comment by gmrchk** [comment]
Hi, swup is using `swup-enabled` class on html tag so you can adjust the styles based on swup running or not. This class overlaps with your selector `[class*="swup-"]`. You could:

1. Remove the class from html tag after the swup startup.
2. Use something like `[class*="swup-"]:not(.swup-enabled)` for swup option. 

Feel free to reopen in case something new comes up.
