### ISSUE TITLE
Executing inline script

### ISSUE THREAD

**Issue by MikeHarrison** [swup/swup#174]
Sorry me again!

Still trying to get my head round some instances of executing scripts on swup-loaded pages. I have sorted most things, but this one I am not sure how to approach. It is an inline script in the body of the page, looks like this:

```
<script async id="epo-booking-widget" src="https://easypreorders.com/embed/js?venueId=XXXX&key=XXXXXXXXXXXXXXXX" type="text/javascript"></script>
```

This is dropped in by the client via the CMS so I don't have any control over it really. On a normal page load it generates an `<iframe>` above itself with a booking form inside. However when the page is loaded via swup this doesn't happen. If anyone has any ideas how I can get round this that would be amazing. And thanks for all the help so far with my various questions!

**Comment by gmrchk** [comment]
Hi, 

did you try [Scripts plugin](https://swup.js.org/plugins/scripts-plugin)? Although, I'm not sure if the `async` attribute won't be a problem, so try removing it if it is.

Scripts plugin could also not work if it's blocked by sites server settings.

**Comment by MikeHarrison** [comment]
Ah yes I have seen that - I am still running Swup v1 so currently that isn't an option. Was holding off upgrading as everything is working apart from this one issue, but might have to bite the bullet and do it! Was put off as I am using forms, smooth scrolling etc. so would need to install the plugins for those too

**Comment by gmrchk** [comment]
Your call 🙂there is always an option of doing [what the plugin does](https://github.com/swup/scripts-plugin/blob/master/src/index.js) manually. Anyway, I don't think we can do anything more than suggested. Will close for now, but feel free to reopen.

**Comment by MikeHarrison** [comment]
I upgraded! Super easy process and I really like the plugins system. Only stuck on the smooth scrolling issue [here](https://github.com/swup/scroll-plugin/issues/3#issue-468876287) but apart from that all good, and the script is now running as I need with the [Scripts plugin](https://swup.js.org/plugins/scripts-plugin)
