### ISSUE TITLE
Load new Javascript code when page replace

### ISSUE THREAD

**Issue by swve** [swup/swup#176]
Hi All,

I'm having problems with javascript code execution when a page is replaced,
When i switch from page A to page B, JS code available in page B ( which is different from page A one ) don't run and i don't know why

**Comment by gmrchk** [comment]
Hi, please [read the docs](https://swup.js.org/getting-started/reloading-javascript).

**Comment by LauraSophieM** [comment]
Hi I've tried to re-call an event listener on willReplaceContent. Yessss, I've read the docs. Still does not work...

**Comment by gmrchk** [comment]
Hi everyone,

@swve just curious, any updates?
@LauraSophieM if you want help, you will need to include more information, like used code, or even better, a hosted site with the problem.
