### ISSUE TITLE
Close slidebar menu and then run page transition

### ISSUE THREAD

**Issue by xhostar** [swup/swup#178]
Swup documentation says: "Use swup events to ... close sidebars ...", but sorry ... this is what I am trying to do without success.

What I want to happen is that when a user clicks on a menu option, first of all menu must close (it takes a while due to a transition) and "only" when the menu is closed, then swup replacing content begins ...

My menu.close() function returns a promise, 

```
menu.close = function () {
    return new Promise(function (resolve, reject) {
        // close menu, wait until animation ends, then resolve promise... 
        resolve();
    }
};
```
... so that I could do something like this:

```
Promise.all([menu.close()]).then(() => {
    // now is when swup should start his job...
});
```
I have tried something like this:

```
swup.on('clickLink', function () {
    Promise.all([app.menu.close()]).then(() => {
        // here it's too late, because swup has already started, and also stops and nothing works
    });
});
```
I wan to create a visual effect similar to this website menu: http://toppaddockcafe.com

Can someone help me, thanks.

**Comment by gmrchk** [comment]
The CSS nature of timing in swup doesn't really go well together with custom waiting on promises to resolve, but...

How about attaching own event listener to the menu links and using [swup API](https://swup.js.org/api/methods) to start the transition after closing of the menu? 

Another option could be to use [JS plugin](https://swup.js.org/plugins/js-plugin) where the control over stuff is much better.

**Comment by xhostar** [comment]
Yes!, that was approximately the first thing I thought.

-  First, I add `data-no-swup` to the links, so Swup ignore them...
- Second, retrigger click.

```
swup = new Swup({
            cache: false,
            plugins: [
                new SwupHeadPlugin(),
                new SwupScrollPlugin(),
                new SwupFadeTheme()
            ]
        });

const options = document.querySelectorAll( 'a.menu__option' );

options.forEach((option) => {
    option.addEventListener( 'click', (e) => {
        e.preventDefault();
        e.stopPropagation();

        let link = e.target;

        // close menu and then...
        Promise.all([menu.close()]).then(() => {
            link.click(); // <------ retrigger link click
        });
}
```
... and it works!.

But now that you mention me `swup API` I have tried to load new page using `loadPage`:

```
// close menu and then...
Promise.all([menu.close()]).then(() => {
    swup.loadPage({
        url: link.href
    });
});
```

... and apparently it works (i can see new content), but I get the following error in the javascript console (and the header is not updated):

```
TypeError: Cannot read property 'originalContent' of undefined
    at t.r.getNextHeadChildren (SwupHeadPlugin.min.js:1)
    at r.getHeadAndReplace (SwupHeadPlugin.min.js:1)
    at swup.min.js:1
    at Array.forEach (<anonymous>)
    at e [as triggerEvent] (swup.min.js:1)
    at e [as renderPage] (swup.min.js:1)
    at swup.min.js:1
```

So unless you can give me a solution, I will opt for my first option, `link.click()`

**Comment by gmrchk** [comment]
A bit hacky, but if it works, it works... 👍 

However, the error sounds like a possible error in Head plugin. Would you mind sharing a link for a demo or something? I'm unable to replicate this problem.

**Comment by xhostar** [comment]
Unfortunately, I can't share any links because the website where I am developing is not yet published, I am on a local network, but if I can help you with something...

```
var pageContent = _this.swup.cache.getCurrentPage().originalContent.replace('<head', '<div id="swupHead"').replace('</head>', '</div>');
```

What is clear is that the error occurs when the plugin tries to get the current page from the cache, but this page is missing.
I tried to activate and deactivate the cache when create Swup (```new Swup({cache: true/false});```, but the error persists

**Comment by gmrchk** [comment]
No matter what I do, I cannot replicate the problem. I'll let it go through my head and see if there is something I missed, but it would really help to see the problem in action on a site. 

I understand that you might not want to publish the site here, so I would really appreciate if you hit me with an email once the site is ready. 🙂

Since the initial issue we were dealing with is resolved, I'm gonna go ahead and close this.
