### ISSUE TITLE
execute js after page change

### ISSUE THREAD

**Issue by Damiano31** [swup/swup#179]
Hi, I have a big problem. I have a site with various pages that need to run scripts. The problem is that the scripts are executed only if I open the page directly, not if I change. I'm reading and trying to figure out how to do it by reading the problems already encountered and by the site but I can't. can someone give me a schematic solution, perhaps with steps to follow?

```javascript
function init() {
    if (document.querySelector('body')) {
        //here I inserted the scripts I want to run 
    }
}
const swup = new Swup();


// run once 
init();

// this event runs for every page view after initial load
swup.on('contentReplaced', init);
```

**Comment by bronze** [comment]
im using hugo, so adapt it to your flow...

on my #main im calling an unique id (for now) for what i used to call custom backgrounds: `<main id="main" class="site-main transition-fade {{ .Params.bodybackground }}" role="main">`
so, my main in html is `<main id="main" class="site-main transition-fade home" role="main">`

in my app.js i got
```
  if (document.querySelector('.home')) {
      ...
    console.log("done");
  }
```

when i reach home, swup fires whatever is there. no problemo.

**Comment by gmrchk** [comment]
Hi @Damiano31, looks like you're doing everything fine so far (except the unnecessary if statement, as the `body` is always present in the page), so I think the problem is in the actual code you want to re-run. Can you share that? 

Just for the record, as you probably found it - in general, [this](https://swup.js.org/getting-started/reloading-javascript) is the page to refer to.

**Comment by Damiano31** [comment]
> Hi @Damiano31, looks like you're doing everything fine so far (except the unnecessary if statement, as the `body` is always present in the page), so I think the problem is in the actual code you want to re-run. Can you share that?
> 
> Just for the record, as you probably found it - in general, [this](https://swup.js.org/getting-started/reloading-javascript) is the page to refer to.

Hi @gmrchk instead of the body i assigned an id or a class for each page.
ex. page agency 

`<body id="agency">`

so in the script i create an if statement like the one written above for all the page. 
 
the code of the index page is :

`<script>
AOS.init();

var i = 0;



TweenMax.to(".body",1.4,{
  backgroundColor:"#045685",
  onComplete  : function(){
   TweenMax.to(".body",0.5,{
    backgroundColor:"#fff"
   })
  }
});

if( /windos phone|android|iPad|iPhone|iPod/i.test(navigator.userAgent) ){
  TweenMax.to("#logo-animazione",0,{
  y:"50vh",
  x:"-50px"
})

TweenMax.to("#logo-animazione",1,{
  onStart  : function(){
   TweenMax.to("#logo-animazione",1,{ 
     scale:"2%",
     ease: Back.easeOut.config(1.7),
       })
  },
  onComplete : function(){
    i++;
  }
  });
}else{
  TweenMax.to("#logo-animazione",0,{
  y:"60vh",
  x:"10vh"
})

TweenMax.to("#logo-animazione",1,{
  onStart  : function(){
  TweenMax.to("#logo-animazione",1,{ 
  scale:"3%",
  ease: Back.easeOut.config(1.7),
       })
  },
  onComplete : function(){
    i++;
    console.log(i);
  }
  });
}



  //logo cambia colore
TweenMax.to("#logo-animazione",0.5,{
     scale:1,
     delay:1.5,
     x:"0px",
     y:"0px",
    onStart: function(){
      TweenMax.to(".path-logo",.5,{
        fill:"#121212"
      })
    },
   });

   var tlnav = new TimelineLite();


//voce menu compare
tlnav.from(".num1",0.4,{
  y:"-10vh",
  delay:1.5,
  ease: Back.easeOut.config(1.7)
})
.from(".num2",0.4,{
  y:"-10vh",
  ease: Back.easeOut.config(1.7)
},"-=0.2")
.from(".num3",0.4,{
  y:"-10vh",
  ease: Back.easeOut.config(1.7)
},"-=0.2")
.from(".num4",0.4,{
  y:"-10vh",
  ease: Back.easeOut.config(1.7)
},"-=0.2")


//body che si sposta 

var gubu = new TimelineLite();

gubu.fromTo(".col-md-11.payoff",.5,{
  y:"100vh",
  autoAlpha:0
},{
  y:"0px",
  ease: Power4.easeOut,
  autoAlpha:1,
  delay:1.5
})


function init() {
    if (document.querySelector('#verticale')) {

if(i>=1){
gubu.fromTo(".col-md-11.payoff",.5,{
  y:"100vh",
  autoAlpha:0
},{
  y:"0px",
  ease: Power4.easeOut,
  autoAlpha:1
});}

var indi = new TimelineLite();

indi.to("#indirizzo",.4,{
  autoAlpha:1,
  scale:1
},"+=2");

indi.to(".social-img",.4,{
  autoAlpha:1,
  scale:1
},"+=.5")



//menu che compare 

TweenMax.to(".header",1, {
 onComplete : function(){
  TweenMax.to(".header",1,{
   autoAlpha:1
  })
 }
});



//morphing testo
var tl = new TimelineLite;
tl.to(".secondafrase",1.5, {
  morphSVG:".terzafrase",
  repeat:10,
  repeatDelay:3.5,
  yoyo:true 
  },"+=6.5");

 

//indirizzo cambia colore
TweenMax.to("#indirizzo",1,{
  
  backgroundColor:"#045685",
  color:"#f7f7f7",
  delay : 3,
  repeat: 6,
  repeatDelay: 1,
  yoyo : true,
　ease: Bounce.easeOut
})
setTimeout(function(){ $('#link-logo').css({pointerEvents:"auto"})}, 3600);
    }
}
const swup = new Swup();
// run once 
init();
// this event runs for every page view after initial load
swup.on('contentReplaced', init);

</script>` 

while the code of the agency page is that:

`<script>
AOS.init();


var firstsec = new TimelineLite();

firstsec.fromTo(".entrata-ag",.8,{
 css: {
   height:"2vh",
 }
},{
 css: {
   height:"80vh",
   y:"0px"
 }
})
.fromTo(".tit-sub-ag p",.8,{
  y:"50vh"
},{
  y:"0px",
  ease:Power3.easeInOut
},"-=.3")
.fromTo(".tit-sub-ag h1",.5,{
  y:"-80vh"
},{
  y:"0px"
},"-=.6")





const swup = new Swup();


// this event runs for every page view after initial load
swup.on('contentReplaced');
  </script>`

tell me something plsss

**Comment by Damiano31** [comment]
> im using hugo, so adapt it to your flow...
> 
> on my #main im calling an unique id (for now) for what i used to call custom backgrounds: `<main id="main" class="site-main transition-fade {{ .Params.bodybackground }}" role="main">`
> so, my main in html is `<main id="main" class="site-main transition-fade home" role="main">`
> 
> in my app.js i got
> 
> ```
>   if (document.querySelector('.home')) {
>       ...
>     console.log("done");
>   }
> ```
> 
> when i reach home, swup fires whatever is there. no problemo.

HI @bronze i don't understand what hugo is and how I could solve my problem. can you explain me a little more in detail?
Thank you!

**Comment by bronze** [comment]
Hi @Damiano31 
Hugo is a CMS (think wordpress, but not bad).
It helps me declare variables i can call on certain pages (like a body class in my example).

What im understanding from your code, you're calling two versions of swup is that right?
I dont think swup will trigger that page's js, but still... make a global .js file and have swup initialized in there, with your querySelectors

**Comment by gmrchk** [comment]
Hi @Damiano31, from the code you passed in here, I can't tell anything regarding what is your site supposed to do (it's a mess), so I can't help, but... I can tell you two things that could help you out:

1. `id` attribute on the body won't get replaced by swup, only contents of it will, which makes your condition for running different code for each page broken. 
2. Not sure if that's a problem here, but scripts included in different pages don't run automatically. You need to include any code you want to run in that `init` function and load that init function on all pages of your website.

I would suggest starting slowly and add code as you go, as it seems you have a lot of code there mixed together, which probably makes it impossible to find a bug.
