### ISSUE TITLE
Page stuck on "is-changing" (no error reported)

### ISSUE THREAD

**Issue by bronze** [swup/swup#180]
Hi
One (yes, ONE) of my pages gets stuck with `is-changing to-visaogeral-midia is-rendering` (but renders).
I believe this is different from #13 since i am not getting any errors on console and the page actually renders (most of it). It stops rendering after a point.
Clicking a link gives me `is-changing to-visaogeral-midia is-rendering is-leaving is-animating to-homepage` to `is-changing to-visaogeral-midia is-rendering is-leaving is-animating to-homepage to-tibrasilhoje` to `is-changing to-visaogeral-midia is-rendering is-leaving is-animating to-homepage to-tibrasilhoje is-popstate`

I believe ive narrowed it down to an incompatibility with UiKit's slideshow component. https://getuikit.com/docs/slideshow

Sorry, ive lost whatever point i had coming here while trying to get some more info on this.
Gonna take a better look now i know what bugged it, but i'll leave this issue for posterity.... maybe someone has encountered this before...

cheers

**Comment by bronze** [comment]
new info, it only bugs if there is more than 1 instance of slideshow

**Comment by gmrchk** [comment]
Hi, the linked library uses classes in a format of `...transition-...` which are used by swup as well.

Fortunatelly, swup can also use other, more specific classes, like `swup-transition-` that can be set with [animation selector option](https://swup.js.org/options#animation-selector).

**Comment by bronze** [comment]
Mr. Wizard that solved it! I was so sure it must have been a javascript issue this never occurred to me... thank you!
