### ISSUE TITLE
Cannot read property 'innerText'

### ISSUE THREAD

**Issue by carlm-fieldtrip** [swup/swup#182]
Getting the following error: Cannot read property 'innerText'

Any ideas on what might be causing this?

I'm running a local site that is in a subdirectory (http://localhost:8888/NAMEOFSITE) on MAMP if that helps any?

**Comment by gmrchk** [comment]
Hi 👋 

you're probably missing `<title>` tag in one or more of your pages. Those are required for swup, and should be present in any page in general.

**Comment by carlm-fieldtrip** [comment]
Bingo! That was it. Thank you!

**Comment by gmrchk** [comment]
Great! 🎉 

I have also added a simple check for title into [debug plugin](https://swup.js.org/plugins/debug-plugin).
