### ISSUE TITLE
SwupScrollPlugin is not defined

### ISSUE THREAD

**Issue by bronze** [swup/swup#184]
Hi there
Ive tried the SwupScrollPlugin so i ould scroll pages on transition and (after much longer than id like to admit) ive narrowed down that i have no idea what im doing wrong here.
Ive set up a clean neltify address with just swup, swup-preload (to check if something else broke) and swup-scroll, and even on a clean boilerplate i get an error.
```
    <script src="./vendor/swup.js"></script>
    <script src="./vendor/swuppreloadplugin.min.js"></script>
    <script src="./vendor/swupscrollplugin.min.js"></script>
    <script>
      var swup = new Swup({
        containers: ['#main','#navbar','#footer','#offcanvasnav'],
        animateHistoryBrowsing: true,
        animationSelector: '[class*="swup-transition-"]',
        plugins: [
          new SwupPreloadPlugin(),
          new SwupScrollPlugin(),
          new SwupBodyClassPlugin('page-'),
        ],
        preload: true,
      });
    </script>
```
Here's the link: https://swup-scroll-not-defined.netlify.com/

**Comment by sethmcleod** [comment]
It doesn't look like you've imported the body class plugin:

```diff
  <script src="./vendor/swup.js"></script>
  <script src="./vendor/swuppreloadplugin.min.js"></script>
  <script src="./vendor/swupscrollplugin.min.js"></script>
+ <script src="./vendor/swupbodyclassplugin.min.js"></script>
  <script>
    var swup = new Swup({
      containers: ['#main','#navbar','#footer','#offcanvasnav'],
      animateHistoryBrowsing: true,
      animationSelector: '[class*="swup-transition-"]',
      plugins: [
        new SwupPreloadPlugin(),
        new SwupScrollPlugin(),
        new SwupBodyClassPlugin('page-'),
      ],
      preload: true,
    });
  </script>
```

**Comment by bronze** [comment]
that didnt change showing the error but i cant reproduce it now, gonna close this up
thx anyway man

**Comment by bronze** [comment]
on my computer it hangs, netlify gets me an error... maybe it has to do with classes again @gmrchk?
https://swup-scroll-not-defined.netlify.com/

**Comment by gmrchk** [comment]
Hey, it seems you're importing the SwupScrollPlugin after you are actually using it in code. Move the plugin script tag above the **app.js** script tag.

**Comment by bronze** [comment]
yea i got it wrong in my example.
trouble was with bundling resources through hugo pipelines. everytime i added swupscroll it broke.
apparently hugo has an issue with bundling many different resources, i only realized this after importing one by one on prod.
