### ISSUE TITLE
Keep the scroll position with back button / browsing back

### ISSUE THREAD

**Issue by tahola** [swup/swup#185]
Hello, when I click a link in the bottom of a page I will be on the bottom of the next page, I fixed that with the scroll plugin but when when I go back, the scroll position is allways the top of the page, so in the both case Swup is doing the opposite of what I want, I am doing something wrong ? 

Here is my config :

```javascript
const options = {
	plugins: [
		new SwupScriptsPlugin({
			head: false,
			body: false
		}),
		new SwupScrollPlugin({
			doScrollingRightAway: true,
			animateScroll: true,
		}),
		new SwupPreloadPlugin(),
		new SwupDebugPlugin(),
	],
	animateHistoryBrowsing: false,
	animationSelector: '[class*="transition-"]',
	containers: ["#swup"],
	cache: false,
	linkSelector:
	'a[href^="' +
	window.location.origin +
	'"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup])',
	skipPopStateHandling: function(event) {
	if (event.state && event.state.source == "swup") {
	 	return false;
	}
		return true;
	}
};

const swup = new Swup(options);
```

**Comment by aerni** [comment]
I first struggled with this as well. You have to save the scroll positions of previous pages. This is how I'm doing it. It only works when navigating back though. Forward navigation doesn't work …

```
scrollPositions = [];
retrieveScrollPosition = false;

swup.on('clickLink', () => {
  saveScrollPosition();
});

swup.on('popState', () => {
  retrieveScrollPosition = true;
});

swup.on('animationInStart', () => {
  if (retrieveScrollPosition) scrollToSavedPosition();
  retrieveScrollPosition = false;
});
    
function saveScrollPosition() {
  scrollPositions[window.location.href] = window.scrollY;
}

function scrollToSavedPosition() {
  window.scrollTo(0, scrollPositions[window.location.href]);
}
```

And in the scroll plugin I had to define this. Otherwise there's some weird scrolling up and down happening.
```
new SwupScrollPlugin({
    doScrollingRightAway: false,
    animateScroll: false,
    scrollFriction: 0.3,
    scrollAcceleration: 0.04
})
```

**Comment by tahola** [comment]
Thank you @aerni , at this point I will just remove the scroll plugin ? I tought his purpose was to fix this bug but apparently no.

**Comment by aerni** [comment]
No, You still need the scroll plugin for this to work. I'm calling the `scrollTo` function the plugin provides in the `scrollToSavedPosition` function.

**Comment by tahola** [comment]
You code doesnt work for me, its scrolling to the absolute bottom, I will look for Swup alternatives, thank for your help.

**Comment by gmrchk** [comment]
Hi guys,

Thank you for your input @aerni. This code is actually only needed for stuff like a bug in Firefox (Chrome or Edge works correctly from what I know), which sets the scroll position before replacing content, so it causes the page to be in a wrong position after back/forward, as pages can have different heights. 

@tahola what scroll plugin does is that it scrolls to the top (or anchor element) after content replace. On back/forward, scroll plugin leaves the setting of the scroll to the browser, which will process it based on the popstate event. 

Is it possible that your page styles will cause the page to reset scroll? Something like `overflow: hidden` on the body element and `overflow: scroll` on some child wrapper element, which is replaced by swup, or something like that? 

Anyways, sorry to see you go.

**Comment by aerni** [comment]
@gmrchk The scroll position actually doesn't work on Chrome either. Or maybe I'm doing something wrong on my end?
