### ISSUE TITLE
Menu button doesn't reset on the website

### ISSUE THREAD

**Issue by MrAnyx** [swup/swup#186]
On smartphone, the menu button doesn't reset its state when we change the page until we reload the page. It says "Hide" when the menu isn't displayed and "Menu" when it is displayed.

**Comment by 23d1** [comment]
Depending on your logic in terms of how you show/hide the menu, you would most likely need to run that function to hide when clicking on an item in the menu, or once the new page content has loaded.

For the latter, here's an example;
```
swup.on('contentReplaced', function() {
    theFunctionForResettingTheMenu();
});
```

**Comment by MrAnyx** [comment]
I mean, it happens on the swup website when you click on the menu button

**Comment by 23d1** [comment]
Ah! Gotcha. :) Yep—the toggle needs to be fixed. I noticed a double scrollbar too.

**Comment by gmrchk** [comment]
Thanks, guys! Will fix both.

**Comment by gmrchk** [comment]
Should be fixed, and fixed. Thank you for reporting guys.
