### ISSUE TITLE
Page won't load when transition ends

### ISSUE THREAD

**Issue by FarfamaH** [swup/swup#188]
I get this error 

swup.js:363 Uncaught TypeError: Cannot set property 'responseURL' of null
    at Swup.enable (swup.js:363)
    at new Swup (swup.js:343)

I think it might have something to do with the local server I'm using? I'm using Jekyll with http://localhost:4000

When I click a link it does the fade out, but at the end it will stop and not load the content of the next page.

**Comment by gmrchk** [comment]
Hi, this means that the structure of the next page is wrong. Most likely, it has a missing container (defined in `container` option) or missing title of a page.

**Comment by omarel1** [comment]
I just saw this. I have the same issue posted here. It's not resolved. Was this ever resolved?
https://github.com/swup/swup/issues/195

**Comment by omarel1** [comment]
omg "Most likely, it has a missing container (defined in container option) or missing title of a page."

I just added a <title> tag and it works. Swup relies on a title tag? wow! that should definitely be mentioned in the docs. thank you!

**Comment by gmrchk** [comment]
@omarel1 glad that fixed it. This is a common problem. I will change swup so the title is not required. Nothing to the about the wrong structure of a page tho...
@FarfamaH I assume this is the same issue for you.

@heidiyee if you're getting this behavior, but not the error, it probably means that your animations never end (promise never gets resolved). More info [here](https://swup.js.org/common-issues#missing-style-for-transition--class).
