### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by MMasey** [swup/swup#190]
At the moment when pjaxing between pages, if using a screen reader such as NVDA, the new content won't be read out. Using [ARIA Live Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) can potentially solve this. 

Barba solve the issue by dynamically adding the `aria-live="polite"` attribute. Maybe something similar could work for this too? https://github.com/barbajs/barba/issues/35. I've solved this on projects using swup by adding aria-live="assertive" aria-atomic="true" too.

Cheers

**Comment by gmrchk** [comment]
This sounds really interesting! 

Can you think of any other accessibility features that swup could handle automatically (maybe buttons, menu items, etc.)? It doesn’t really need to be related to the page transition.

If the accessibility attributes on containers are all we can do, we can add it to the swup core (or we probably should in any way), but in case there would be more things (maybe even some crazy cool ones that no websites do but should) the accessibility could have own plugin with anything we can think of. 

Thoughts?

**Comment by MMasey** [comment]
Hey @gmrchk, apologies for taking so long to respond to you on this.

Off the top of my head I can't think of anything else that swup could handle automatically when it comes to accessibility. For the most part it comes down to people using correct semantic markup, and is less to do with JavaScript. 

As ensuring that screen readers can still understand a website when it's using something like swup, i think including it as part of core would be a good idea. I think it should only require a few lines of code too. If I can find time to create a PR I will 🙂

**Comment by gmrchk** [comment]
Hi @MMasey, no worries, same on my side... we've all got jobs to do in the first place. 🙂

I see... and agree. I guess we're settled on adding it to a core. 

I will try to add this sometime soon, or if you create a PR and beat me to it, that would be awesome.

**Comment by MMasey** [comment]
PR for this at #214

**Comment by gmrchk** [comment]
As mentioned in the PR, I don't think this can be solved automatically. [Added to the docs](https://swup.js.org/common-issues#improving-accessibility) tho.
Thanks for the help!
