### ISSUE TITLE
Question: how to determine if the page is already cached in the transitionStart event?

### ISSUE THREAD

**Issue by manuel-84** [swup/swup#191]
With  
```
swup.on('clickLink', function(e) {
    if (swup.exists(e.target.getAttribute('href'))) return;
    // else do something
  });
```
I got swup.exists is not a function. Ideally I would need to use this inside the transitionStart event

**Comment by manuel-84** [comment]
I found this solution working for me:

```
  swup.on('clickLink', function(e) {
    if (e.target.getAttribute('href').replace(window.location.origin, '') in swup.cache.pages) return;
    //
  });
```

**Comment by gmrchk** [comment]
This is my bad, a mistake in documentation. The ‘exists’ and all other methods in cache section belong to the cache instance, so you should do ‘swup.cache.exists(...)’.

I will fix the docs.

**Comment by manuel-84** [comment]
> This is my bad, a mistake in documentation. The ‘exists’ and all other methods in cache section belong to the cache instance, so you should do `swup.cache.exists(...)`.
> 
> I will fix the docs.

Thank you.
I had to abandon the transitionStart way because inside the event we don't have any reference to the page clicked. It would be useful to have an object passed inside the event containing informations like this.
