### ISSUE TITLE
Remove error

### ISSUE THREAD

**Issue by Felixr91** [swup/swup#192]
Swup is working great! Thanks!

I have the following right above my closing body tag.... 

`
    
    <script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>  
    <script type="text/javascript">
        const swup = new Swup();
    </script>
`
and I am receiving the following error.... 

`
Uncaught TypeError: Cannot set property 'responseURL' of null
    at e (swup.min.js:1)
    at new e (swup.min.js:1)
    at (index):499
e @ swup.min.js:1
e @ swup.min.js:1
(anonymous) @ (index):499
`

I would like to rid this error as I'm debugging another issue in my project and would like a clean console to work in. 

Any suggestions?

**Comment by gmrchk** [comment]
Hey, this is most likely caused by missing title of a page, or missing container in the initially loaded page which causes swup to fail when caching the page.

If that’s really the case, debug plugin should actually hint you that.

**Comment by gmrchk** [comment]
Hmm, maybe running swup before the html structure is there could be the issue? Swup caches the page right after creating the instance. If you don’t want that, you can disable the cache at first, and then enable the option

´´´javascript
swup.options.cache = true;
´´´

or move the swup init.

**Comment by gmrchk** [comment]
```javascript
const swup = new Swup({cache: false});
```

**Comment by Felixr91** [comment]
Still plugging away at this issue. I think this error may be having an effect on Ipad's using the Chrome browser. 

Correct me if I'm mistaken, but I think when declaring "var n" it is not able to read the outerHTML property of document.documentElement correctly. 

Should I see the footer of the HTML page?

When debugging this is the value I get for document.documentElement.outerHTML...

`
<html lang="en-US" class="sr"><head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="https://gmpg.org/xfn/11">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,700|Noto+Serif|Roboto:700,400,300|Vast+Shadow|Oswald:500,300|Raleway:200,300&amp;display=swap" rel="stylesheet"> 
	
	<link rel="stylesheet" href="https://use.typekit.net/swo7bjj.css">

	
  	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

	<title>Work Page – Alzar School – 116West</title>
<link rel="dns-prefetch" href="//s.w.org">
<link rel="alternate" type="application/rss+xml" title="116West » Feed" href="http://b1n.27f.mwp.accessdomain.com/feed/">
<link rel="alternate" type="application/rss+xml" title="116West » Comments Feed" href="http://b1n.27f.mwp.accessdomain.com/comments/feed/">
		<script type="text/javascript">
			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/12.0.0-1\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/12.0.0-1\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/b1n.27f.mwp.accessdomain.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.2.2"}};
			!function(a,b,c){function d(a,b){var c=String.fromCharCode;l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,a),0,0);var d=k.toDataURL();l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,b),0,0);var e=k.toDataURL();return d===e}function e(a){var b;if(!l||!l.fillText)return!1;switch(l.textBaseline="top",l.font="600 32px Arial",a){case"flag":return!(b=d([55356,56826,55356,56819],[55356,56826,8203,55356,56819]))&&(b=d([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]),!b);case"emoji":return b=d([55357,56424,55356,57342,8205,55358,56605,8205,55357,56424,55356,57340],[55357,56424,55356,57342,8203,55358,56605,8203,55357,56424,55356,57340]),!b}return!1}function f(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var g,h,i,j,k=b.createElement("canvas"),l=k.getContext&&k.getContext("2d");for(j=Array("flag","emoji"),c.supports={everything:!0,everythingExceptFlag:!0},i=0;i<j.length;i++)c.supports[j[i]]=e(j[i]),c.supports.everything=c.supports.everything&&c.supports[j[i]],"flag"!==j[i]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[j[i]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(h=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",h,!1),a.addEventListener("load",h,!1)):(a.attachEvent("onload",h),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),g=c.source||{},g.concatemoji?f(g.concatemoji):g.wpemoji&&g.twemoji&&(f(g.twemoji),f(g.wpemoji)))}(window,document,window._wpemojiSettings);
		</script><script src="http://b1n.27f.mwp.accessdomain.com/wp-includes/js/wp-emoji-release.min.js?ver=5.2.2" type="text/javascript" defer=""></script>
		<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
	<link rel="stylesheet" id="dashicons-css" href="http://b1n.27f.mwp.accessdomain.com/wp-includes/css/dashicons.min.css?ver=5.2.2" type="text/css" media="all">
<link rel="stylesheet" id="admin-bar-css" href="http://b1n.27f.mwp.accessdomain.com/wp-includes/css/admin-bar.min.css?ver=5.2.2" type="text/css" media="all">
<link rel="stylesheet" id="wp-block-library-css" href="http://b1n.27f.mwp.accessdomain.com/wp-includes/css/dist/block-library/style.min.css?ver=5.2.2" type="text/css" media="all">
<link rel="stylesheet" id="wpaas-admin-css" href="http://b1n.27f.mwp.accessdomain.com/wp-content/mu-plugins/gd-system-plugin/assets/css/admin.min.css?ver=3.9.8" type="text/css" media="all">
<link rel="stylesheet" id="onesixteenwest-style-css" href="http://b1n.27f.mwp.accessdomain.com/wp-content/themes/onesixteenwest/style.css?ver=5.2.2" type="text/css" media="all">
<link rel="stylesheet" id="wpaas-admin-bar-css" href="http://b1n.27f.mwp.accessdomain.com/wp-content/mu-plugins/gd-system-plugin/assets/css/admin-bar.min.css?ver=3.9.8" type="text/css" media="all">
<link rel="https://api.w.org/" href="http://b1n.27f.mwp.accessdomain.com/wp-json/">
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://b1n.27f.mwp.accessdomain.com/xmlrpc.php?rsd">
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://b1n.27f.mwp.accessdomain.com/wp-includes/wlwmanifest.xml"> 
<link rel="canonical" href="http://b1n.27f.mwp.accessdomain.com/work-page-alzar-school/">
<link rel="shortlink" href="http://b1n.27f.mwp.accessdomain.com/?p=364">
<link rel="alternate" type="application/json+oembed" href="http://b1n.27f.mwp.accessdomain.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fb1n.27f.mwp.accessdomain.com%2Fwork-page-alzar-school%2F">
<link rel="alternate" type="text/xml+oembed" href="http://b1n.27f.mwp.accessdomain.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fb1n.27f.mwp.accessdomain.com%2Fwork-page-alzar-school%2F&amp;format=xml">
		<style type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style>
		<style type="text/css" media="print">#wpadminbar { display:none; }</style>
	<style type="text/css" media="screen">
	html { margin-top: 32px !important; }
	* html body { margin-top: 32px !important; }
	@media screen and ( max-width: 782px ) {
		html { margin-top: 46px !important; }
		* html body { margin-top: 46px !important; }
	}
</style>
	</head>

<body class="loading" style="height: 100%;">

<div id="page" class="site">


	<div class="container-fluid desktop-nav-container">
		<div class="row desktop-nav-row d-flex justify-content-between">
			<div class="col-1"></div>
			<div class="col-1"><div class="ham"></div></div>
		</div>
	</div>

	
			<div class="col-1 fab-container">
			<div class="fab-div"><a href="https://www.facebook.com">
				<svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-f" class="svg-inline--fa fa-facebook-f fa-w-10" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg>
			</a></div>
			<div class="fab-div">
				<svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="instagram" class="svg-inline--fa fa-instagram fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path></svg>
			</div>
			<div class="fab-div">
				<svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="linkedin-in" class="svg-inline--fa fa-linkedin-in fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"></path></svg>
			</div>
			<div class="fab-div">
				<svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter" class="svg-inline--fa fa-twitter fa-w-16" role=
`

**Comment by gmrchk** [comment]
I see, yep, disabling cache actually won't help, as swup still kind of uses it, but empties the cache regularly. 

Can you move the swup init to the end of a page? If you have a demo/the site is running somewhere, that would also be really helpful so I can have a closer look!

**Comment by Felixr91** [comment]
Absolutely. I'll email it to you. 

I'd like to keep this page private if thats okay.

**Comment by Felixr91** [comment]
Hey Georgy!

I closed the issue since the error was resolved. I have a new question
about swup here <https://github.com/swup/swup/issues/199> if you are still
feeling like a fountain of pure generosity.

I really appreciate your time. I want to support swup or repay you for your
help in some way. Please let me know! If I can make a donation to swup or
contribute to a patreon or something please let me know.

Thank you!

**Comment by gmrchk** [comment]
Glad I could help 👍 

I'll just add for the record that problem was incorrectly defined containers in the page (missing element with the id defined in swup `containers` option).

Swup actually has an [open collective](https://opencollective.com/swup) page and some other ways to support this project financially that you can use if you wish, it's all up there in the Sponsor button (I actually turned it off some time ago and forgot to turn back on again, so thanks for reminding me 👏)
