### ISSUE TITLE
Other Javascript Dependencies not loading after Page Transition

### ISSUE THREAD

**Issue by Jay-Ferguson** [swup/swup#196]
I am having an issue using Swup.JS. When transitioning between pages the other JS dependencies attached to the page do not load.  At first I thought this is was due to the other libraries using "-transition" classes as well so I used the 
const options ={ animationSelector: '[class*="swup-transition]'};
to make the transitions only interact with swup. The transitions in between pages is functioning however the rest of the javascript is not. When I refresh the page the rest of the javascript then functions. Has anyone encountered a similar issue?

**Comment by gmrchk** [comment]
Hi, have you checked [this page](https://swup.js.org/getting-started/reloading-javascript)?
