### ISSUE TITLE
Update href of the anchors on the others pages

### ISSUE THREAD

**Issue by iamalessiopaoletti** [swup/swup#198]
Hi!

I have a problem with menu anchors when I'm on another page.

"#Anchor"

on another page it obviously doesn't work,
how do I change the url only on the other pages in

"/Index.html#anchor"

but making it come back "#anchor" in the index.html page?
and then, why is the animation not activated using the browser back button?

**Comment by gmrchk** [comment]
Hi 👋

I don't understand the issue, could you explain some more or even better, provide a demo?

The animation is not present on back/forward as it is expected behavior of swup (reasoning: user wants to get where he was as quickly as possible). However, this can be [adjusted with options](https://swup.js.org/options#animate-history-browsing).

**Comment by iamalessiopaoletti** [comment]
Hi,

Thanks for the reply,
Sorry I try to explain better,

In the menu I have 4 links, 3 of these are anchors on the homepage (index.html):

there is my code:
```
<nav id="nav">
        <ul>
            <li><a class="menu-item anchor" href="#sezione-chi-siamo">01.  Su di noi</a></li>
            <li><a class="menu-item anchor" href="#wg-title">02.  Wedding Gallery</a></li>
            <li><a class="menu-item " href="/ph/it/servizi.html">03.  Servizi</a></li>
            <li><a class="menu-item anchor" href="#contatti">04.  Contatti</a></li>
        </ul> 
    </nav>
```

when you browse on other pages the href doesn't work.
the last anchor for example href="#contatti" is in the home and the right path is href="index.html#contatti".

Demo:
[https://alessiopaolettidesign.it/ph/it/](url)

my code for swup:
```
const swup = new Swup();

            swup.on('pageView', function() {
                 window.scrollTo(0, 0);

                    $('#nav').toggleClass('nav-open');
                    $('#nav ul li a').toggleClass('nav-open');
                    $('#menu-btn-open').css("display", "block");
                    $('#menu-btn-close').css("display", "none");
              });
```

**Comment by gmrchk** [comment]
Correct me if I'm wrong, but I think you mean that on other pages the links don't lead to the homepage. So instead of `#contatti` you want to have links like `/ph/it/#contatti`. I guess that's what you're looking for. 

I also think that this
```javascript
$('#nav').toggleClass('nav-open');
$('#nav ul li a').toggleClass('nav-open');
```

should be

```javascript
$('#nav').removeClass('nav-open');
$('#nav ul li a').removeClass('nav-open');
```

**Comment by iamalessiopaoletti** [comment]
This was a mistake that caused the menu to reopen by going back, I corrected it last night I hadn't noticed before,

however I mean this:
![immagine](https://user-images.githubusercontent.com/41924220/64922637-b5d0af80-d7d1-11e9-879c-c6f701291c30.png)
In this case it is right.



but in another page such as "servizi.html":
![immagine](https://user-images.githubusercontent.com/41924220/64922688-4dce9900-d7d2-11e9-98fb-7568d38a24f3.png)
in this case it does not work because "#sezione-chi-siamo" is on the page index.html and not here.

**Comment by gmrchk** [comment]
As mentioned, you need to include the link of the page in the `href` attribute as well, not just the `#` part. 

`#contatti` ➡️`/ph/it/#contatti`

Please read through https://www.w3schools.com/html/html_links.asp.

**Comment by iamalessiopaoletti** [comment]
Oh sorry, I used a script to scroll through the anchors and it didn't work with those paths, now I've solved using the swup scroll-plugin!
