### ISSUE TITLE
Running Anime.js animation during swupscrollplugin runs

### ISSUE THREAD

**Issue by Felixr91** [swup/swup#199]
I have an anime.js animation that looks something like this.... 

```
		anime({
			targets: '.line-drawing-demo .lines path',
			strokeDashoffset: [anime.setDashoffset, 0],
			easing: 'easeInOutSine',
			duration: 1500,
			delay: function(el, i) { return i * 250 },
			direction: 'alternate',
			loop: true, 
			complete: function(){

			}
		});

		anime({
			targets: '.line-drawing-demo .lines polygon',
			strokeDashoffset: [anime.setDashoffset, 0],
			easing: 'easeInOutSine',
			duration: 1500,
			delay: function(el, i) { return i * 250 },
			direction: 'alternate',
			loop: true
		});

		
		
		setTimeout(function(){
			  	$(".preloader").fadeOut(1500, function() {
		      	$('body').removeClass('loading');
		      	anime.remove('.line-drawing-demo .lines path');
				anime.remove('.line-drawing-demo .lines polygon');
	  		});
		}, 2000);
```

The animation is set to fade out for 1.5 seconds and plays for 2 seconds. 

The HTML section for the element looks like this... 

```
			<div class="preloader" style="background-color: #<?php the_sub_field('background_color'); ?>">
			      <div class="demo-content align-center line-drawing-demo">
			          <svg xmlns="http://www.w3.org/2000/svg" class="lines" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 601.34 353.47"><defs><style>.cls-1{fill:none;stroke:#<?php the_sub_field('animation_color'); ?>;stroke-miterlimit:10;}.cls-2{fill:url(#New_Gradient_Swatch);}</style><linearGradient id="New_Gradient_Swatch" x1="1249" y1="462" x2="1249" y2="462" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="red"/><stop offset="1" stop-color="#d9e021"/></linearGradient></defs><title>dmlogo</title><g id="Layer_1" data-name="Layer 1"><path class="cls-1" d="M985,311l79,31V517H987c-.13-3.62-.77-12.29-5-20a47.67,47.67,0,0,0-4-6,43.63,43.63,0,0,0-7-7c-6.87-5.1-15.65-5.14-19-5a30.33,30.33,0,0,0-14,4,32.18,32.18,0,0,0-11,11c-3.6,5.49-4.83,10.38-6,15a69.56,69.56,0,0,0-2,18,80.62,80.62,0,0,0,1,13c1.06,6.51,1.87,11.45,5,17,1.81,3.21,5.4,9.57,13,13a27.33,27.33,0,0,0,14,2,34.82,34.82,0,0,0,18-7,37.25,37.25,0,0,0,10-12,47.58,47.58,0,0,0,6-19h78v90l-70-27a59.89,59.89,0,0,1-6,9,70.94,70.94,0,0,1-13,12c-19.88,13.89-47,13-47,13-5.24-.08-31-1-54-19-39.57-31-36.73-85.83-36-100,1.43-27.68,10.93-46.11,13-50,4.76-8.95,13.65-25.18,32.84-37.14A84.64,84.64,0,0,1,926,412c3.36-.05,24.41-.2,39,9a93,93,0,0,1,16.51,13.92c1.94,2,3.46,3.83,4.49,5.08Q985.5,375.5,985,311Z" transform="translate(-837.16 -310.26)"/><path class="cls-1" d="M1080,420l75,28a82.64,82.64,0,0,1,65-35c6.86-.22,36.3-1.15,56,20a58.76,58.76,0,0,1,11,17c4.11-6.46,17.07-25,42-34a83,83,0,0,1,40-4c11.88,1.24,37.51,5.71,54,26,12.54,15.43,15,32.95,15,46V625h-83q.49-60,1-120c0-.75,0-17.64-13-25a24.84,24.84,0,0,0-14-3,24.28,24.28,0,0,0-13,2c-11.39,5.35-17.87,20.53-16,38q.49,54,1,108h-83V517c-.11-3.52-.59-15.67-3-24a20.35,20.35,0,0,0-2-5,20,20,0,0,0-7-7c-5.46-3.33-10.94-3.16-16-3-3.56.11-7,.22-11,2a24.66,24.66,0,0,0-9,7c-9,10.59-7.28,27.59-7,30h-83Z" transform="translate(-837.16 -310.26)"/><path class="cls-2" d="M1249,462" transform="translate(-837.16 -310.26)"/></g><g id="dmline"><polygon class="cls-1" points="242.84 222.74 324.84 222.74 324.84 352.74 242.84 320.74 242.84 222.74"/></g></svg>
			      </div>
			</div>
```

Anime.js is animating the the svg paths. 

I finally have swup running nicely but would like for this animation to run immediately after the transition and while swupscrollupplugin scrolls to the top of the page.  

Georgy, if you're reading this, thanks for all the help on my last issue. I really appreciate it!

**Comment by Felixr91** [comment]
Solved!

**Comment by gmrchk** [comment]
Glad you solved it! Could you post your solution here? In case someone runs into something similar.

**Comment by Felixr91** [comment]
Sure!

I added the swupscriptsplugin to make my JS files run after my content was 'swupped'. 

`
            const options = {
			    plugins: [
			        new SwupScrollPlugin({
				    	doScrollingRightAway: true,
					    animateScroll: false,
					    scrollFriction: 0.3,
					    scrollAcceleration: 1,      	
			        }),
			        new SwupScriptsPlugin({
						head: true,
						body: true			        	
			        })
			    ],
			    cache: false
			 };

			const swup = new Swup(options);
`

Then in my JS file I used Jquery to load my animation for the first 3 seconds... 

`
	function startPreload(){

		anime({
			targets: '.line-drawing-demo .lines path',
			strokeDashoffset: [anime.setDashoffset, 0],
			easing: 'easeInOutSine',
			duration: 1500,
			delay: function(el, i) { return i * 250 },
			direction: 'alternate',
			loop: true, 
			complete: function(){

			}
		});

		anime({
			targets: '.line-drawing-demo .lines polygon',
			strokeDashoffset: [anime.setDashoffset, 0],
			easing: 'easeInOutSine',
			duration: 1500,
			delay: function(el, i) { return i * 250 },
			direction: 'alternate',
			loop: true
		});

		
		setTimeout(function(){
			  	$(".preloader").fadeOut(1500, function() {
		      	$('body').removeClass('loading');
		      	anime.remove('.line-drawing-demo .lines path');
				anime.remove('.line-drawing-demo .lines polygon');
	  		});
		}, 3000);
	};

	startPreload();

`
