### ISSUE TITLE
how to set linkSelector to accept all relative links without them starting with  /

### ISSUE THREAD

**Issue by patrickroppel** [swup/swup#200]
`i` have installed swup on my homepage which works super nice. 
i am now trying to make a phonegapbuild app out of it and run into a problem. 

in order to make the internal links work, i had to take out the starting / in front of all of them.

so instead of `<a href="/page.html">` i now have`<a href="page.html">`.

which excludes them from swup. i know that i should be changing the link selector in the options but just dont get it to run on all links? 

sorry if this is a stupid one, but i am new to js and have now tried for hours...

**Comment by gmrchk** [comment]
Hi  👋 

This can be adjusted with [linkSelector](https://swup.js.org/options#link-selector) option, which accepts [any valid selectors](https://www.w3schools.com/cssref/css_selectors.asp). 

If you want to simply select all `<a>...</a>` elements, you can set the option to `linkSelector: 'a'`.
