### ISSUE TITLE
Issue with display:none property and hidden elements

### ISSUE THREAD

**Issue by nothingtodotoday** [swup/swup#201]
Hello,

I'm a complete beginner in this. I'm doing a static website with a few pages and to be responsive some of the elements are displayed and hidden with display property, based on the viewport.

Swup loads the whole code in the page without considering the hidden elements and creating a problem with the visualization of the page.

I attached some pictures to explain well. As you can see, Desktop and Mobile versione are quite different and some elements appear/disappear based on the devices. 

If I click on the element to change page I land on a broken page and only when I refresh it works well (but if I click on the back Swup is disabled as expected).

Is there a way to do this? Thanks.

![Mobile-norefresh](https://user-images.githubusercontent.com/55437837/65032082-c2284a00-d942-11e9-80a9-90e952c01c0d.png)
![Desktop](https://user-images.githubusercontent.com/55437837/65032083-c2284a00-d942-11e9-8869-7471cde584e4.png)
![Mobile](https://user-images.githubusercontent.com/55437837/65032085-c2c0e080-d942-11e9-8a5c-5db3d1ce727e.png)
![Desktop-norefresh](https://user-images.githubusercontent.com/55437837/65032086-c2c0e080-d942-11e9-9f7d-71070e285229.png)

**Comment by gmrchk** [comment]
Hi, it seems like one of two things. 

1. You're displaying/hiding parts of your HTML with JS, based on the `window.innerWidth` or something. In that case, don't. Use CSS instead. 

2. If that's not the case, then probably all the CSS is not loaded when using swup, as swup doesn't replace contents of the head tag. Do you load separate CSS file for each page? If so, you can always load CSS for all pages, or try using Head plugin/your custom solution to load CSS files.

**Comment by nothingtodotoday** [comment]
Hi gmrchk, thanks for answering and sorry for late.

I was in the second situation.

Homepage had only ` <link rel="stylesheet" href="style-min.css">` and the second page ` <link rel="stylesheet" href="style-min.css">
    <link rel="stylesheet" href="clients-page-min.css">`

Now it works very well loading in the homepage as you suggested ` <link rel="stylesheet" href="style-min.css">
    <link rel="stylesheet" href="clients-page-min.css">`.

Thanks a lot!
