### ISSUE TITLE
Scroll to anchor on new tab

### ISSUE THREAD

**Issue by bronze** [swup/swup#202]
Hi there

When opening a page on a new tab though `<a  href="/link#anchor" >}}" data-no-swup>`, the page does not scroll to the right position.
I got the ScrollPlugin as
```
new SwupScrollPlugin({
  doScrollingRightAway: false,
  animateScroll: true,
  scrollFriction: 0.3,
  scrollAcceleration: 0.04,
}),
```

Tried a javascript solution without success either.
```
if (location.hash) {
  let target = location.hash;
  window.scrollTop = document.querySelector(target).offsetTop;
  console.log(target);
}
```
it outputs correctly the anchor on console, just doesnt scroll.

Any ideas?

**Comment by gmrchk** [comment]
Swup doesn't handle any scroll when a page is open with an anchor in a new tab, the browser should. The only exception is when you have an `animateHistoryBrowsing` option enabled, which will cause the scroll plugin to set the thing below and disable native handling. Is that the case?

```javascript
window.history.scrollRestoration = 'manual';
```

To your custom solution... `scrollTop` doesn't work on window, use `scrollTo` instead. `offsetTop` is probably also not the info you want, try using `getBoundingClientRect` instead.
