### ISSUE TITLE
Page transition not working, link attribute error

### ISSUE THREAD

**Issue by arthurdjn** [swup/swup#203]
**Hello,** 
I am trying to animate the **transitions** of a site I have designed. However, I can't figure out how to use swup.js, even on simple code. The problem I am facing, is the transition between two pages: The animation works well, but not the transition (I am stucked to the same html page).
My problem is very similar to this one :

> _https://github.com/swup/swup/issues/30_

, however the answers did not solved it. I am using a localhost server, I changed the **link selector attribute** to only 'a':
```
    let options = {
        LINK_SELECTOR: 'a',
        debugMode: true,
    };
    const swup = new Swup(options);
```

Moreover, when I load my index.html with the localhost server, it doesn't animate and I have the error **"Cannot GET access /subpage.html"**. But if I open my index.html on my browser, google chrome, I can see the transition and then it is stucked and doesn't load my subpage.html.

**My code :**

https://codepen.io/arthurdraws/pen/KKPEpEa

**index.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1.0">
    <meta http-equiv="X-UAV-Compatible" content="ie=edge">
    <title>SWUP test</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>  
</head>

<body>
    <div class="container">
        <nav>
            <a href="#">company</a>
        </nav>
        <main id="swup" class="transition-fade">
            <h1>Home page here</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda quasi reprehenderit non corrupti quae quis facilis natus veniam quas quibusdam? Provident voluptates nemo excepturi corporis saepe obcaecati sapiente, quas culpa!</p>
            <a href="/index.html">Go to other page</a>
        
        </main>
    </div>

    <script>

    const swup = new Swup();
    </script>

</body>
</html>
```
The button is linked to the same index.html file, so it should load the page again when the button is clicked.
In my project, I have another file, subpage.html which is the same as index.html (with the appropriate href `<a href="/index.html">Go to main page</a>).`

**style.css**
```
body{
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
}
a{
    text-decoration: none;
}
.container{
    width: 80%;
    margin: 0 auto;
}
nav {
    background: rgb(255,0,0);
    padding: .5em;
}
nav a{
    font-weight: bold;
    color: white;
}
main{
    width: 80%;
    margin: 5em auto;
}
main a{
    display: inline-block;
    background: red;
    color: white;
    padding: .8em;
    margin-top: 2em;
}
.transition-fade {
    transition: 0.4s;
    opacity: 1;
  }
  
  html.is-animating .transition-fade {
    opacity: 0;
  }
```

On a code snippet, I get the error
```
 Error{
       "message": "Script error.",
       "filename": "",
       "lineno": 0,
       "colno": 0
}
```

**Comment by AugustMiller** [comment]
Could you let us know what local server you're using? The `Cannot GET …` error sounds like the browser is unwilling or unable to make the proper XHR request. If that fails, Swup won't do anything (and your page will fade/transition out, then not display the next page).

The above is important, because XHR will only work over HTTP, not the “`file://`” protocol—so, if you're just double-clicking the file to open it in your browser, it isn't apt to work. Similarly, because CodePen only offers single-page projects, it's hard to demonstrate there, as well.

**Comment by AugustMiller** [comment]
Also worth noting—Swup doesn't make a request or re-load the current page if the clicked link points to the current URL. :v:

**Comment by arthurdjn** [comment]
Thanks for your answers ! I was using the live server from VS Code : ritwickdey.liveserver.
