### ISSUE TITLE
Calling `destroy()` does not remove `popstate` listener

### ISSUE THREAD

**Issue by morki** [swup/swup#205]
This is because `bind()` always returns new instance so references are different in this two calls.

```javascript
window.addEventListener('popstate', this.popStateHandler.bind(this));
...
window.removeEventListener('popstate', this.popStateHandler.bind(this));
```

The solution is to save it to property and use it as parameter of `addEventListener` and `removeEventListener` like this:

```javascript
this.boundPopStateHandler = this.popStateHandler.bind(this);
window.addEventListener('popstate', this.boundPopStateHandler);
...
window.removeEventListener('popstate', this.boundPopStateHandler);
```

Thanks for this cool library :)

**Comment by AugustMiller** [comment]
This sounds like something suited for the docs. I'll see if we can't find a spot for it—definitely a common pattern with significant side-effects that aren't apparent until you start dealing with a persistent page, a la Swup! Function binding in and of itself is a sticky wicket, but if we have an opportunity to introduce readers to an advanced JS subject, I'm all about it!

**Comment by gmrchk** [comment]
Hi guys,

I think @AugustMiller misunderstood the problem. There is a bug in swup which causes it to still listen for `popstate` events after calling a `destroy` method. As I have really only tried calling a destroy method while implementing and never in a real project, I can see that easily happening. 

Will fix. Feel free to create a PR is you're up for it guys. Thank you both 🙏

**Comment by gmrchk** [comment]
Fixed 👍 
Although it seems browser remembers that the page was switched using `pushState`, so it won't do anything on popstate anyway (can be force reloaded using `window.location`).
