### ISSUE TITLE
Bring in next page WHILE current page is exiting?

### ISSUE THREAD

**Issue by oelbaganwg** [swup/swup#207]
While using the css transitions, the next page waits until the current page exit transition is complete before coming in. Is there a way to fetch and bring in the next page at the same time the current page is exiting? or even before the current page exits?

**Comment by AugustMiller** [comment]
As far as Swup's configurable behavior goes, this isn't currently an option, sorry! The library just [replaces the HTML](https://github.com/swup/swup/blob/master/src/modules/renderPage.js#L33) of each registered container, and doesn't make a distinction between the removal of outgoing markup and the insertion of the incoming markup.

It might be possible to use the `willReplaceContent` and `contentReplaced` events to inject the new markup _earlier_, but this would be venturing outside the advertised functionality, and is apt to produce some unusual side effects. 😬

I can see how this would be helpful, though, for something like a cross-fade transition! I hate to undercut any interest in Swup, but it might be worth looking at [Barba.js](https://barba.js.org), which leans more heavily on scripting to set up and transition pages. :v:

**Comment by oelbaganwg** [comment]
Yeah I was digging around and it didn't seem so. The problem is that it isn't as worth doing it all if you have to wait for a page transition to completely end and then another to start. I guess it can look good if you constantly interrupt each page load with a loader or something blocking the wait time, but its too interruptive. It would be better if it can be seamless.

**Comment by AugustMiller** [comment]
This is a totally fair criticism! It took a while on our first implementation to figure out how to make things feel like they weren't held up by the animations—it was helped largely by just speeding them up a bit, but also by keeping as much of the page intact between transitions as possible.

For example, breaking up transitions into smaller, faster “chunks” (not applying them from the Swup `containers` or high-level elements) and leaving things like the navigation entirely _without_ transitions ended up reducing the UX penalties of full-page transitions.

Let us know if you have any additional feedback, or want to hash out some ideas about how to approach parallel load + unload steps!

**Comment by gmrchk** [comment]
Surely, it really depends on the effect you are trying to achieve. [Swup docs](https://swup.js.org/getting-started) are using simple slide up/down effect with CSS where the easing and the speed of it make it feel kind of like a "crossfade". 

With the current state of what swup offers (eg. multiple containers, animation based on CSS classes on html tag, really simple implementation) it would be very problematic to incorporate something like a "crossfade" into the equation, so if you're looking for that, I would recommend looking at Barba, as @AugustMiller suggested. 

We can look into some plugin implementation of this for the future, but this is currently not possible unless you pull swup and start rewriting parts of it. [JS plugin](https://swup.js.org/plugins/js-plugin) would be helpful in that case. 

Great job August!

**Comment by daun** [comment]
Update from 2023 — we've just released [swup 4](https://swup.js.org/announcements/swup-4/) which supports [parallel animations](https://swup.js.org/plugins/parallel-plugin/).
