### ISSUE TITLE
Triggering transition on another event than click

### ISSUE THREAD

**Issue by quentin-f451** [swup/swup#209]
Hi!

Is this possible to have the transition triggered on another event than a click on a link? For example, I would like to go back to landing page from another page when I scroll to the bottom of this page.

I currently simply change the `document.location.href` to `'/'` but there's no transition.

Thanks a lot!

**Comment by Symediane** [comment]
Hi,

I think you can find what you searching for on this page :
https://swup.js.org/api/methods#loadpage

You can use the swup object you instantiate to trigger the navigation when user scrolled to the bottom of the page by using the "loadPage" method. :+1:

**Comment by quentin-f451** [comment]
That's perfect, thanks a lot!
