### ISSUE TITLE
Swup and foundation - Cannot GET / .... content.

### ISSUE THREAD

**Issue by DanBilly** [swup/swup#211]
Hi Guys

Really excited about using this. Sorry to hassle you but I am having some difficulty getting it working. I am using the foundation framework. I have made the recommended changes you mention in one of the issues. But I am getting the below message (see image).

If i click on one of these I typically get 'Cannot GET /tags.html:content'

Foundation using Panini and handlebars to insert pages could this be a problem.

I had to go through some hoops to get it in to Foundation but it is there.

Instead of using '<script src="node_modules/swup/dist/swup.min.js"></script>' it is imported through a custom dependences file (this seems to be the way with foundation - although as you can probably tell i'm no pro ; )

Any way using this method means I have also not been able to use the 'defer' part you mention in your video. Any thoughts there?

Any help would be greatly received as I am pulling out what little hair I have left. 

<img width="281" alt="Screenshot 2019-10-16 at 07 31 38" src="https://user-images.githubusercontent.com/14996908/66890645-14629680-efe7-11e9-9551-3927c8d6e6b7.png">

<img width="751" alt="Screenshot 2019-10-16 at 07 17 41" src="https://user-images.githubusercontent.com/14996908/66890308-f0eb1c00-efe5-11e9-97de-5e6f811f71c4.png">

**Comment by AugustMiller** [comment]
Hey Dan!

I'm afraid I don't understand your implementation—it sounds like you (or Foundation) are bundling some third-party dependencies into one file (`injection.js`)? I take it the script is included in your page automatically by Foundation…  which is why you can't set specific attributes on the `<script></script>` tag?

Could you post a basic HTML + JS example, each enclosed in triple-backticks ( `` ``` ``, before the first line, and after the last in each block)?

The logging you've captured doesn't look like it's related to Swup, per se.

When you say "clicking on one of these," it's reasonable you're getting an error, but likely produced by whatever local server you're running—this seems like debugging data that Foundation is outputting, which includes… the name of a partial? Your server is probably not able to respond to the full URL with `:content` at the end, as it doesn't match a file in your project. Most debuggers highlight what they believe are links in the console and in HTML attributes as a convenience, but in this case, it doesn't know that the `:content` part is irrelevant.

If we can clear away some of the noise, we may be able to figure out what exactly about Swup isn't working, and/or whether we're looking at some kind of incompatibility.
