### ISSUE TITLE
Pages staying at the same scroll location on load. 

### ISSUE THREAD

**Issue by Dave10055** [swup/swup#213]
Hi All, 

I seem to be experiencing an issue integrating SWUP with my WordPress theme. I have managed to set the script up and it does work successfully, however, when clicking through to a new page it will stay at the same scroll location as the previous page. 

Is there any way to reset the scroll position to the top of the page when linking through? Have I missed an option with the documentation?

**Comment by jeremydouglas** [comment]
@Dave10055 are you using the Scroll Plugin?

**Comment by Dave10055** [comment]
> @Dave10055 are you using the Scroll Plugin?

Nope, I am using this alongside of ScrollMagic.js - could this be the issue?

**Comment by jeremydouglas** [comment]
Could be, I had a vanilla smooth scrolling script that wasn't compatible with swup.

**Comment by Dave10055** [comment]
I was able to fix the issue by using the SwupScrollPlugin.min.js script, with the following settings: 

`const swup = new Swup({
  plugins: [new SwupScrollPlugin({
    doScrollingRightAway: false,
    animateScroll: false,
    scrollFriction: 0,
    scrollAcceleration: 0,
})]
});`

This seemed to fix the issue. Hopefully, this can help anyone else experiencing this issue.

**Comment by leph83** [comment]
Thanks for the information how to fix the problem. But do I really need to add the scrolling plugin to fix the problem? I don't think this should be the default behaviour, when navigating to a new page

**Comment by gmrchk** [comment]
Some sites lack scrolling all together and are positioned in a fixed way. Without the plugin, swup simply doesn't do anything to control the scroll. 
If you only want to reset scroll to the top on each page transition, you can easily do that using swup events. 
```javascript
swup.on('contentReplaced', function () {
    window.scrollTo(0, 0);
});
```

**Comment by leph83** [comment]
> Some sites lack scrolling all together and are positioned in a fixed way. Without the plugin, swup simply doesn't do anything to control the scroll.
> If you only want to reset scroll to the top on each page transition, you can easily do that using swup events.
> 
> ```js
> swup.on('contentReplaced', function () {
>     window.scrollTo(0, 0);
> });
> ```

This almost works. The problem with this solution is, that you navigate with the nice transition to the next page. But then you see the page scrolling to the top if you have
```
html {
scroll-behavior: smooth;
}
```

**Comment by gmrchk** [comment]
If this CSS rule something necessary, then use swup events to add/remove this CSS before and after the transition is done.

https://swup.js.org/events

**Comment by leph83** [comment]
I appreciate your suggestions, but this is getting more and more complicated for something that I think, shouldn't happen in the first place. 
I would be happy, if you think the same way. If not....you still did an amazing job with swup.

**Comment by gmrchk** [comment]
Swup offers some options. You can implement simple (or advanced) scroll controls yourself, or use the plugin to get some advanced (although a bit opinionated) solution out of the box. 

Introducing a default scroll to 0 in swup would basically prevent the option of implementing the scroll yourself. Additionally, it wouldn't solve the issue with people adding `scroll-behaviour` property anyway.  

I appreciate your opinion, but I have to think of all the options people would like from swup, and yours is just one of many.

**Comment by leph83** [comment]
Maybe you'll find a solution, that can do both, scroll to top by default and keep the possibility to implement scroll yourself. Thanks for your support. I am really grateful for that

**Comment by matias-autio** [comment]
If you're using Bootstrap 5, make sure to disable smooth scrolling in [Bootstrap options](https://getbootstrap.com/docs/5.3/customize/options/), as it's on by default and makes it seem like the ScrollPlugin is not working.
