### ISSUE TITLE
Push style transition

### ISSUE THREAD

**Issue by Mishkamshka** [swup/swup#215]
Hi, I read that the next animation doesn't start until the previous animation finishes, how can I overlap them so i can make something very similar to this? Thank you

http://dvmg.tv/info

**Comment by riiccardo** [comment]
in this case, you have to use `Barba.js` because `barba.js` have `old and new-container` wrapper u can 
add this animation to ur HTML

`Barba v1` have this feature I don't know `Barba v2` api

https://barba.js.org


``` html
<!-- during the transition old container still in the page -->
<div class="old-container"></div>

<!-- after animation end old-container will remove and replace with new container -->
<div class="new-container"></div>
```

**Comment by AugustMiller** [comment]
Just to clarify @riiccardo's comment: Barba.js is an entirely separate library! I wouldn't recommend trying to use Swup + Barba in parallel, as it could lead to some “interesting” behavior.

That said, I think the suggestion is spot-on—this is where we arrived in #207, as well. :v:

**Comment by daun** [comment]
Update from 2023 — we've just released [swup 4](https://swup.js.org/announcements/swup-4/) which supports [parallel animations](https://swup.js.org/plugins/parallel-plugin/).
