### ISSUE TITLE
A different js bundle for each pages using webpack and HtmlWebpackPlugin to load my html files

### ISSUE THREAD

**Issue by dylandoamaral** [swup/swup#216]
Hi, first of all thanks you for this library, it really gives a good feature to our website !

However I have a problem using Swup with webpack and more precisely because of my HtmlWebpackPlugin. Indeed, HtmlWebpackPlugin generate my html's files according to a js bundle where are included my file's components such as its css and so on. 

My pages have a different bundle so each one generate a different css style for each pages for example. Using Swup, when I go to another page, my scripts are not updated neither runned.

I tried two plugins, the head one and the script one but the problem is still here and that's normal since my scripts doesnt change when I go in another page.

Here is an example because I have some trouble to explain clearly my problem ^^':
- I have two pages, a and b. Each one has a bundle so a has a.bundle.js that generate the css and so on and b has b.bundle.js.
- When I reload b, inside scripts I can see b.bundle.js and b is well rendered but when I go to a from b I still have b.bundle.js instead of a.bundle.js and the contrary is the same, if I reload a I have a.bundle.js and if I go to b from a I still have a.bundle.js

For the moment the only things that can work for me is to create an unique bundle and load it for each page, however different css may will have same classes and destroy them to each other.

Do you think I have another solution that can prevent me to regroup everything in one css and one js ?

Thanks you for your attention and sorry for my english, it's not perfect !

**Comment by AugustMiller** [comment]
Hi, Dylan!

It sounds like you're describing [code splitting](https://webpack.js.org/guides/code-splitting/), no? If so, you might be able to extract some "global" dependencies into a different `entry` point?

Overall, my sense is that `swup-head-plugin` is what you're looking for (in that they should reconcile the contents of the current + incoming `document`s `head` and ensure the contents are not duplicated.

Do you mind posting the resulting HTML? I'm curious to know what those documents end up looking like, and how you're initializing Swup (i.e. is it initialized only in one bundle, in both, or do you have a third bundle that loads on every page?).

**Comment by dylandoamaral** [comment]
Hi August,

I have fixed the problem by creating only one bundle for my whole application! The resulting HTML put my script inside my body so I couldn't use the head's plugin that easily.
