### ISSUE TITLE
Animate scroll only when link contains #

### ISSUE THREAD

**Issue by aerni** [swup/swup#217]
I'm using the `ScrollPlugin` but only want to animate the scroll when you click on a link with a `#`. I've tried to set `animateScroll: true` on `samePageWithHash` event. But this only works on the second click on the link. Is there a good solution to this?

**Comment by gmrchk** [comment]
I guess you mean only animating the scroll on the same page, but not during the transition. 
In that case I would actually suggest a similar, but opposite approach. When the animation starts (`animationOutStart` event), you can switch the `animateScroll` options to false, and switch the options back on `animationInDone` event.

**Comment by aerni** [comment]
This works perfectly, thanks!

Anyone looking for this too. This is the solution:

```JS
const swup = new Swup({
  plugins: [
    new SwupScrollPlugin({
      animateScroll: true,
    }),
  ],
});

swup.on('animationOutStart', () => {
  const scrollPlugin = swup.findPlugin('ScrollPlugin');
  scrollPlugin.options.animateScroll = false;
});

swup.on('animationInDone', () => {
  const scrollPlugin = swup.findPlugin('ScrollPlugin');
  scrollPlugin.options.animateScroll = true;
});
```
