### ISSUE TITLE
Adding swup to cdnjs.com CDN

### ISSUE THREAD

**Issue by mfabing** [swup/swup#219]
I am a big user of CDN (Content Delivery Network). And I personnally love particularly https://cdnjs.com
Would it be possible for you guys to upload this awesome Javascript Library to https://cdnjs.com?

**Comment by gmrchk** [comment]
Hi, you can actually get swup and all it's plugins from unpkg.com, like [this page](https://swup.js.org/getting-started/installation) suggests. Anyways, sounds like a great idea!

From a quick glimpse it seems it takes a lot of work to get swup to **cdnjs** in a first place and keep it up to date with each version as well, or am I missing something? It also seems anyone can suggest (or put up) a package, so if you want to pitch in, you can probably even do it yourself.

**Comment by gmrchk** [comment]
Hey again, I will not find any time for this any time soon, so I will close this issue. 

It's not critical and you can get swup from the unpkg CDN as well as mentioned in the link above.

In case anyone wants to take care of this and put up swup to the cdnjs.com, feel free to comment below.
