### ISSUE TITLE
Swup in swup

### ISSUE THREAD

**Issue by JohannesSchwegler** [swup/swup#222]
Hello,
is it possible to create a swup element within another swup element?

**Comment by gmrchk** [comment]
Hi,
if you're refering to swup containers, I see no reason to do such thing, as you would be replacing the same content during one transition (and you would probably encounter some error as well). 
Swup allows to replace even the smallest parts of the page with unlimited number of containers. Maybe I don't understand your question tho, can you elaborate?

**Comment by JohannesSchwegler** [comment]
@gmrchk thanks for your reply. What i mean is a container in a container. Somethings like this:
https://cuberto.com/services/branding/.
I know this can be done with ajax aswell, but i was wondering if i could add another element( for example <main id="swup2"> in <main id="swup> and then when i click on a link in the child container, only this one changes.

**Comment by JohannesSchwegler** [comment]
@gmrchk thanks for your reply. I think you explained it right. Are there some examples somewhere? I cant find them.

**Comment by gmrchk** [comment]
Swup is enhancement of your website, which basically means that anything that is normally on the page based on the URL is also there when using swup. 
In practice that would mean that you can replace all conatiners on the page every time, but in case some are identical to the previous page, it will look just the same and no one should notice it was even replaced (you might need to restore scroll with swup events). 
If you really need to replace only that one container and have those multiple instances on the page, I would suggest to just use some pjax library instead.

**Comment by JohannesSchwegler** [comment]
Ok thanks :) you can close this issue
