### ISSUE TITLE
Run animations after load all images?

### ISSUE THREAD

**Issue by ethereal94** [swup/swup#223]
Tell me how to run animations after load all the images on the site?

**Comment by JohannesSchwegler** [comment]
I think you can use  addEventListener("swup:content-replaced", ()=>{}= or addEventListener("load", ()=>{} to animate things. Or do you mean the transition-animation?

**Comment by ethereal94** [comment]
> I think you can use addEventListener("swup:content-replaced", ()=>{}= or addEventListener("load", ()=>{} to animate things. Or do you mean the transition-animation?

transition-animation

**Comment by gmrchk** [comment]
For that you would be best using swup with [JS plugin](https://swup.js.org/plugins/js-plugin), as it gives you more control over when to run things and you can run a code to detect this when you need. However, I've summarized my opinion about this [here](https://github.com/swup/swup/issues/118) as this sounds as a bad idea.

I would focus on preloading assets, not blocking transition.
