### ISSUE TITLE
Errors when loading plugins (using NPM and ParcelJS)

### ISSUE THREAD

**Issue by 23d1** [swup/swup#225]
For some reason, whenever I try to run a plugin through

```
import Swup from 'swup';
import ScrollPlugin from '@swup/scroll-plugin';

const swup = new Swup({
    LINK_SELECTOR: 'a[href^="' + window.location.origin + '"]:not([data-no-swup])',
    elements: [
        '.page-container',
        '#menu-contents > *',
    ],
    plugins: [new ScrollPlugin()]
});
```

I get;

```
Uncaught TypeError: plugin.exec is not a function
    at Swup.module.exports [as usePlugin] (app.a6a4d504.js:1905)
```

which refers to this line;
`plugin.exec(options, this, getCurrentPageHtml);`

and this;
```
this.options.plugins.forEach(function (item) {
    return _this.usePlugin(item);
});
```

Any ideas? I can't seem to locate the probable user error. ;)

**Comment by gmrchk** [comment]
Hi Anders, `usePlugin` mentioned in the stacktrace is a method from old swup version, which is incompatible with current plugins. 
Update swup to version 2 and you can use all the plugins. 

Cheers!
