### ISSUE TITLE
Wordpress bug

### ISSUE THREAD

**Issue by Giorgiodir** [swup/swup#227]
The bug itself is that when you're logged in and the admin bar is visible, it doesn't update. So if you start on about, then go to the contact and click on 'Edit page', you'll land on the about page in the backend, don't contact it as it should.

how can i solve? has anyone already faced this problem?

**Comment by AugustMiller** [comment]
This is likely due to the WP "Admin Bar" being outside your main [Swup container](https://swup.js.org/options#containers).

The admin bar is injected server-side for every request (unless something has changed recently), so by adding a second container to your Swup initializer…

```js
new Swup({
  containers: ['#swup', '#wpadminbar']
});
```

…Swup will know to look for incoming elements matching both of those containers and replace their contents.

Let us know if this works!

**Comment by AugustMiller** [comment]
Noting that I'm not sure how this will behave when the admin bar is _not_ present—be sure to test in logged-in and logged-out states!

**Comment by gmrchk** [comment]
What @AugustMiller suggest is correct, but I would actually suggest different approach here. You're the only one (or one of few people) being logged in and seeing this content. You also don't need any "best experience" yourself from your site. Another thing is that there might also be a lot of things in this WP admin mode that can be broken by swup. 

...so my solution would be to just not run swup when the admin bar is present at all.

**Comment by Giorgiodir** [comment]
> What @AugustMiller suggest is correct, but I would actually suggest different approach here. You're the only one (or one of few people) being logged in and seeing this content. You also don't need any "best experience" yourself from your site. Another thing is that there might also be a lot of things in this WP admin mode that can be broken by swup.
> 
> ...so my solution would be to just not run swup when the admin bar is present at all.

Hi gmrchk  how can I disable the script if you are logged in, could you give me a small code example?

**Comment by Giorgiodir** [comment]
> This is likely due to the WP "Admin Bar" being outside your main [Swup container](https://swup.js.org/options#containers).
> 
> The admin bar is injected server-side for every request (unless something has changed recently), so by adding a second container to your Swup initializer…
> 
> ```js
> new Swup({
>   containers: ['#swup', '#wpadminbar']
> });
> ```
> 
> …Swup will know to look for incoming elements matching both of those containers and replace their contents.
> 
> Let us know if this works!


this is my code if I put it as you say it gives me error
`jQuery(document).ready(function ($) {
	let options = {
		linkSelector: 'a[href^="'+ document.location.origin +'"]:not([data-no-swup]):not([href*=".jpg"]), a[href^="//"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]),a[xlink\\:href]',
		containers: ['#swup'],
        animationSelector: '[class^="a-"]',
		cache: false,
		plugins: [
			//new SwupGaPlugin(),
			new SwupScrollPlugin(),
			new SwupBodyClassPlugin(),
			new SwupFormsPlugin({formSelector: ''}),
			new SwupHeadPlugin(),
			//new SwupPreloadPlugin(),
			//new SwupDebugPlugin()
		],
		skipPopStateHandling: function(event){
			if (event.state && event.state.source == "swup") {
				return false;
			}
			return true;
		},
	}
	
	var swup = new Swup(options);
	
	// load scripts for replaced elements
	document.addEventListener('swup:contentReplaced', event => {
		
		//close menu on reload content mobile
		var elements = document.getElementsByClassName('navbar-collapse');
		for (var i=0; i < elements.length; i++){
			elements[i].classList.remove("navbar-toggler-icon");
		}
		var menu = document.getElementById('bs4navbar');
		menu.classList.remove("show");
		
		//initialize all scripts
		initalilizeScripts();
		
	});
}(jQuery));`

**Comment by AugustMiller** [comment]
@Giorgiodir A couple requests!

1. Could you surround your pasted code in a pair of three back-ticks (` ``` `), one set before the first line, and one set at the very end? It's hard to tell whether your problem is just a syntax issue, or a configuration issue, without formatting/indentation.
2. Share the error you mention—that'll help isolate the problem.
3. Let us know how `so-scripts-js` relates to your Swup implementation?

Please be aware that we may not be able to help with implementation-specific issues or interference caused by other code/libraries (including those that might be injected by Wordpress).

**Comment by Giorgiodir** [comment]
Thanks I solved it disable the script when the admin bar is present
