### ISSUE TITLE
[Question] Is it possible to pass variables with swup's history?

### ISSUE THREAD

**Issue by 23d1** [swup/swup#228]
Is it possible to pass along variables with swup's `createHistoryRecord`? 

For example an element's `offsetTop` to be able to jump between certain areas in an element using transform or the likes when recalling the history with `popState`.

**Comment by AugustMiller** [comment]
Hey, Anders!

I haven't had a chance to look into the Swup implementation here, but did want to tack on some supporting info from the `pushState` spec… specifically, that each history state entry contains a `state` object that is exposed during subsequent `pop` events.

[Reference](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)

**Comment by 23d1** [comment]
Yeah, I want to kind of piggyback on the swup implementation if at all possible, to store states of elements and things in the history state.

**Comment by gmrchk** [comment]
Hi guys, you can write your page state into the the history record with `replaceState`, which just modifies current record. This can be used before swup creates new record, so event like `clickLink` would be the right time to call this (also called on `popstate` for back/forward). Keep in mind that this history state record should contain `source: "swup"` - that is used by swup. Here's the code that swup is [using](https://github.com/swup/swup/blob/master/src/helpers/createHistoryRecord.js).

I would try to store this state elsewhere, but you might have a reason why you want to store it in the history records (works after hard refresh as well?).
