### ISSUE TITLE
Reinitializing Twitter Widgets on SWUP transition

### ISSUE THREAD

**Issue by x2i4eva** [swup/swup#230]
I have an embedded Twitter widget in my page (below)... however when you browse to it from another page using SWUP for transitioning, it doesn't load the widget as the Script tag never gets run.

Is there any way to reinitialize it?

`<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Cross play is definitely something we&#39;re interested in exploring more in the future.</p>&mdash; Bungie (@Bungie) <a href="https://twitter.com/Bungie/status/1192517759336189952?ref_src=twsrc%5Etfw">November 7, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> `

**Comment by AugustMiller** [comment]
Based on the (limited) docs from Twitter:

> If content is dynamically inserted into a page (such as lazy-loading content or using a `pushState` technique to navigate between articles) it’s necessary to parse new buttons and widgets using the `twttr.widgets.load()` function.
> ```js
> twttr.widgets.load()
> ```

[Source](https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/scripting-loading-and-initialization)

So, in Swup-land, you'll need to do something like this:

```js
const instance = new Swup({ /* …your configuration… */ });

// Called just after replacing the new page's markup:
instance.on('contentReplaced', (e) => {
  twttr.widgets.load();
});
```

**Comment by x2i4eva** [comment]
Thank you, I actually got around it by also doing this in the contentReplaced event:

```
const script = document.createElement("script");
script.setAttribute("src", "https://platform.twitter.com/widgets.js");
document.getElementsByClassName("twitter-tweet")[0].appendChild(script);
```

But your way is a lot better so will adopt this instead.
