### ISSUE TITLE
Prevent navigation?

### ISSUE THREAD

**Issue by svennerberg** [swup/swup#236]
In some cases I would like to prevent swup from navigating to the page that the clicked link refers to. Is that possible?

My idea was to  do something like this:

```javascript
swup.on('clickLink', e => {
  if (e.delegateTarget.attributes.disabled) {
    // prevent navigation
  }
})
```
The problem is that I can't find a way to stop swup from navigating. Any ideas?

**Comment by gmrchk** [comment]
Hey,
this is not possible with swup in the form that you suggested. However, swup has an [API](https://swup.js.org/api/methods) that you can use to navigate between pages on your own, so you can implement any logic on top of it that you need.

```javascript
const link = ...;
link.addEventListener('click', event => {
    if (/* your logic here */) {
         swup.loadPage({
             url: event.target.href
         });
    }
});
```

FYI code not tested...

**Comment by mskocik** [comment]
I agree with @svennerberg, it would be helpful, this would be possible to prevent swup navigation with 2 possible options:

- discard click event
- continue with default click event behaviour  

Imagine scenario, when custom pages can add additional handler to `clickLink` event, which could eventually cancel navigation to given page. 

My real use-case was is: I have html with _specific_ links (external, in specific context). These links don't and cannot have `data-no-swup` attribute, but I definitely need to prevent default swup navigation. This is my workaround where I additionally set `data-no-swup` attribute  and programmatically click on that link again.

```javascript
swup.on('clickLink', e => {
    const link = e.delegateTarget;
    const href = link.href;
    const fromTrix = link.closest('.trix-content');
    if (!fromTrix && (href.indexOf(window.location.host) > -1 || href.substr(-1) === '#')) return;
    link.href = window.location.pathname + window.location.search;
    link.dataset.swupSkip = true;   // setting data-no-swup attr to prevent swup navigation
    link.target="_blank";
    setTimeout(() => {
        link.href = href;
        link.click(); // link will be opened in new window now
    }, 20);
});
```

**Comment by gmrchk** [comment]
Hi, sorry for the delay!

I get the point here, but it would a bit problematic and would introduce options only to specific swup event handlers which could be confusing, so let's try to solve the issue with the current setup.

Can we use a swup [link selector option](https://swup.js.org/options#link-selector) to select only links we want to use, eg. links in the header, footer, links in some other elements, but not the ones you want to be prevented?

**Comment by mskocik** [comment]
I don't see any problems with implementation. It should work fine if the immediate check after triggering `clickLink` event. It's not async, so it should work like a charm. Something like this:

```js
// my event definition
swup.on('clickLink', event => {
  // here we can set some 'internal' property to event
  // or trigger some swup internal setter
  if (mySpecialCondition) {
    swup.skipCurrentLink();   // this sets Swup internal 'shouldSkipLink' property to true
  }
});

// swup code
// index.js:200
...
this.triggerEvent("clickLink", event);
/** new code */
if (this.shouldSkipLink === true) {
  this.shouldSkipLink = false; // reset internal 'shouldSkipLink' property to false
  return; 
}
/** end new code */
event.preventDefault(); // normal swup logic continues...
...
```
Here is demo sandbox, where google will be opened in new tab, when clicked on red link
[codesandbox.io](https://zqd5w.csb.app/)

**Comment by svennerberg** [comment]
@gmrchk In my case it's the same link but depending on a dynamic condition, such as selected date it should be prevented. So what you're suggesting wouldn't help in that case.

@mskocik That's exactly what I'm looking for!

**Comment by svennerberg** [comment]
Any news about this request? Is this something you would consider implementing in the library?

**Comment by lubomirblazekcz** [comment]
My solution is following and works, needed this for confirm dialog for leaving the page.

```js
document.addEventListener('click', event => {
    if (!event.target.closest(Swup.options.linkSelector)) {
        return false
    }

    if (CONDITION) {
        event.stopImmediatePropagation()
        event.preventDefault()
        return false
    }
}, true)
```

**Comment by hirasso** [comment]
@lubomirblazekcz your solution looks good! Setting `useCapture` on the `addEventListener` to `true` and conditionally stopping the event propagation was the solution for me, too. Probably a more clear way to write it would be like so:

```js
document.addEventListener('click', event => {
    if (!event.target.closest(Swup.options.linkSelector)) {
        return
    }

    if (CONDITION) {
        // since we are in the capturing phase, stopping the event here will cause it to never reach 
        // the swup linkClickHandler will never fire, since it is triggered during the bubbling phase
        event.stopPropagation() 
        // your custom code...
    }
}, {capture: true});
```
