### ISSUE TITLE
Support for typescript

### ISSUE THREAD

**Issue by lukechu10** [swup/swup#238]
**Describe your issue**:
I want to use this in a typescript project that I am working on. There doesn't seem however to be any type definitions available for swup, official or community made. 

Is there any plan to add typescript support for swup because this is a great project and not having typescript reduces the amount of developers who can use this.

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better?

**Comment by gmrchk** [comment]
Hey, not sure why you closed this. Seem like a valid request. Did you use some workaround/defined types yourself? 

Not sure how requested it would be, so let's keep it open for a bit. I would actually like to add at least type definitions as well. Rewriting to TS won't be necessary tho.

**Comment by lukechu10** [comment]
> Hey, not sure why you closed this. Seem like a valid request. Did you use some workaround/defined types yourself?
> 
> Not sure how requested it would be, so let's keep it open for a bit. I would actually like to add at least type definitions as well. Rewriting to TS won't be necessary tho.

Sorry, there wasn't any activity for the past month so I closed it. I was planning to use this project in an electron environment. By default, electron refreshes the renderer process on a page load which means there is an ugly white flash when changing pages. In order to prevent this, I disabled electron from refreshing the process. I am still be interested in seeing type definitions for the project.

**Comment by daun** [comment]
Closing in favor of #486
