### ISSUE TITLE
swup don't work in xamp

### ISSUE THREAD

**Issue by 0d1n92** [swup/swup#243]
Hello everyone,
I recently got to know swap.js and was testing. but swup doesn't seem to work, it adds the unicament class to the htlm tag, but continues to reload the pages and not make animations.
 I use xamp (apache).
my code index: https://pastebin.com/44AaXAs8
my code 2page: https://pastebin.com/BTaUPXmA
why din't work?

**Comment by EnzoEmb** [comment]
Check the Link Selector section on the Options page of the docs: [https://swup.js.org/options](url)
By default works when the url of the anchor start with / or #
You can try this: const swup = new Swup({ linkSelector:'a.swup-link' });
and add the class "swup-link" to your anchor tags

**Comment by 0d1n92** [comment]
i fixed

**Comment by Naren-hybreeder** [comment]
Hi @0d1n92 ,
I am also getting the same issue. Can you share you code? and how you fixed that issue?
