### ISSUE TITLE
Other JS scripts (AddThis, Sumo, ShareThis, Instagram Embed) are broken with swup.js

### ISSUE THREAD

**Issue by vamsi3001** [swup/swup#244]
**Describe your issue**:
I'm using [Ghost CMS](ghost.org) with [London Theme](https://github.com/TryGhost/London). You can find the Swup code in default.hbs. 

Unable to make any Social Sharing Plugins like [ShareThis](https://sharethis.com/), [Sumo](https://sumo.com/), [AddThis](https://www.addthis.com) and the [Instagram Embed JS](https://www.instagram.com/developer/embedding/)

**You can replicate the issue with the following steps:**
**Scenario 1:**
Visit [vamsithota.me](vamsithota.me) > Click on Photography Page > Click on Photography2 Page - You'll see the AddThis on the bottom left not loaded correctly any of the pages.

**Scenario 2:**
Visit [vamsithota.me/photography](vamsithota.me/photography) > Click on Home Page > Click on Photography2 Page - AddThis will load on the first load then if you move between pages, you'll notice the icons are enlarged and look broken. 

Also, it's not supposed to load on the home page if you observe it will display scenario 1 and scenario 2.

The home page is excluded from the AddThis Dashboard.

I'm trying to reinitialize both the AddThis and Instagram Embed Js functions but still, the issue is not fixed.

**Swup config or any additional relevant code used**:
You can see my customisations made to default Swup code [here](https://github.com/vamsi3001/London/blob/master/default.hbs) 

```javascript
    <script data-swup-ignore-script>
        $(document).ready(function () {
            // Mobile Menu Trigger
            $('.nav-burger').click(function () {
                $('body').toggleClass('site-head-open');
            });
        });
        // Initiate Swup transitions
        const swup = new Swup({
            plugins: [new SwupHeadPlugin(), new SwupScriptsPlugin()],
        });
        document.addEventListener('swup:contentReplaced', event => {
            initInfiniteScroll(window, document);
            $('body').removeClass('site-head-open');
            addthis.init();
            instgrm.Embeds.process();
            
        });
    </script>
```

**Before creating this issue, did you think of...**:
- [X] Have you checked closed issues for similar/related problems.
- [X] Have you provided all helpful information available? 
- [X] Have you considered creating a demo so we can help you better?

**Comment by ptiozzo** [comment]
Try to add

new SwupScriptsPlugin({
      head: true,
      body: true
    });

**Comment by gmrchk** [comment]
Hey, I don't think the problem is with your swup setup. Everything seems fine there. 

Are you sure calling `addthis.init()` is the way to re-initialize the plugin on a single page application?

**Comment by msilight** [comment]
I have the same problem with fslighbox. when I disable swup it work. but when swup loads, lgihtbox doesn't work.

**Comment by gmrchk** [comment]
All the information on reloading can be found [here](https://swup.js.org/getting-started/reloading-javascript), but what's the correct way to refresh the third-party scripts is not something I can answer.
