### ISSUE TITLE
Scrollmagic pinning does not recognize the heights of the elements after contentReplaced.

### ISSUE THREAD

**Issue by mantrone** [swup/swup#245]
Hi,
I'm trying to implement Scrollmagic library on my website with Swup JS. I need to pin one element on specific page.
When refresh page work, but if I change page and then come back, it seems that Scrollmagic does not recognize the heights of the elements. Pinning works only if I refresh the page.

I've created 2 functions. One for scrollmagic init and one for destroy it.

I think I've to find a way to fire the scrollmagic init function on the event 'contentReplaced' and then fire the destroy function for the other page. But i don't know how.

Anyone can help me? Ty

**Comment by mantrone** [comment]
This is a part of my code inside init function:
```
if (document.querySelector('.mockup_txt_wrap')) {
	var ctrlHome;
	function initScrollMagicMain() {
		// Init ScrollMagic
		ctrlHome = new ScrollMagic.Controller();
		// Pin text 
		var pin = new ScrollMagic.Scene({
			triggerElement: '#mockup',
			triggerHook: 0.3,
			duration: '100%'
		})
		.removePin(true)
		.addIndicators()
		.setPin('.mockup_txt_wrap')
		.addTo(ctrlHome);
	}
	initScrollMagicMain();
	swup.on('willReplaceContent', function unload() {
		if (document.querySelector('.mockup_txt_wrap')) {
			ctrlHome.destroy(true);
		}
	});
}
```

This is the [link](https://nexibo.agency/progetti/stensen/) if it can help.

**Comment by LilianCruanes** [comment]
@mantrone Is your block of code into an event listener that listen to page's changes ?

```
document.addEventListener("swup:pageView", function () {
     <your block of code here>
})
```

or

```
document.addEventListener("swup:contentReplaced", function () {
     <your block of code here>
})
```

**Comment by mantrone** [comment]
@LilianCruanes Yes. inside this.
```
document.addEventListener("swup:contentReplaced", function () {
     <your block of code here>
})
```

**Comment by LilianCruanes** [comment]
@mantrone Maybe the Scrollmagic library isn't comptabtible with Swup ?
Must ScrollMagic be initialized on all page of your site ?

**Comment by mantrone** [comment]
> Must ScrollMagic be initialized on all page of your site ?

@LilianCruanes probably yes. 
At this point I wonder if it can solve my problem with SwupScriptsPlugin.

**Comment by LilianCruanes** [comment]
Try to use this : 
```
window.addEventListener("load", function () {

   function init () {
      if (document.querySelector('.mockup_txt_wrap')) {
	var ctrlHome;
	function initScrollMagicMain() {
		// Init ScrollMagic
		ctrlHome = new ScrollMagic.Controller();
		// Pin text 
		var pin = new ScrollMagic.Scene({
			triggerElement: '#mockup',
			triggerHook: 0.3,
			duration: '100%'
		})
		.removePin(true)
		.addIndicators()
		.setPin('.mockup_txt_wrap')
		.addTo(ctrlHome);
	}
	initScrollMagicMain();
      

        function unload () {
		if (document.querySelector('.mockup_txt_wrap')) {
			ctrlHome.destroy(true);
		}

                // Don't forget to also remove the unload listener
                document.removeEventListener('swup:willReplaceContent', unload)
         });
	document.addEventListener('swup:willReplaceContent', unload)
      }
   }

  // Init on first display
  init()

  // Init when page change
  document.addEventListener("swup:pageView", init)
})
```
Then enable the SwupScriptsPlugin (don't forget to load the related script) :
```
        const swup = new Swup({
            plugins: [
                new SwupScriptsPlugin(),
            ]
        });
```

Finally on your HTML document :  
 `<script src="your/script/path" data-swup-ignore-script></script>`

PS : My code could contain some syntax errors, I wrote it fastly :upside_down_face:

**Comment by LilianCruanes** [comment]
Thus your script will never be removed of the document and all will be managed by listeners

**Comment by mantrone** [comment]
Ok. thanks for your help @LilianCruanes . I really appreciate. 
I will try this code and let you know.

**Comment by gmrchk** [comment]
Hey guys,

@mantrone, did you this solve your issue?

**Comment by mantrone** [comment]
Hi guys, sorry for delaying my answer.
Not yet. Unfortunately I didn't have time to test it. I have had other work to do, but I plan to try the @LilianCruanes's solution within the next two days.

**Comment by mantrone** [comment]
Here I come again. After applying @LilianCruanes's advice, it still doesn't work.
When refresh page work, but if I change page and then come back, it seems that Scrollmagic does not recognize the heights of the elements. Pinning works only if I refresh the page.

[Here](https://nexibo.agency/about/), on the "About" page there is an example.

**Comment by vidi45** [comment]
I have the same problem with locomotive-scroll in swup. I just get it to work in vue.

**Comment by gmrchk** [comment]
In general, swup replaces the content of the page, which naturally breaks any saved scroll values for elements. Those need to be updated, ideally on swup `contentReplaced` event. 

How to update those values is more of a question for mentioned libraries tho.

**Comment by gmrchk** [comment]
I've included all info about reloading scripts over [here](https://swup.js.org/getting-started/reloading-javascript), but what's the correct way to reload the third party libraries is unfortunately not something I can answer. Some libraries might need to be disabled and enabled again all together, or might not support single-page apps at all. 
I don't think I can be of any more help here, so will close.
