### ISSUE TITLE
ctrl+shift+T problem and other questions

### ISSUE THREAD

**Issue by flyingatm** [swup/swup#246]
First of all this is the best pjax library i have ever seen. I almost used them all and I can clearly say that... Thank you very much for your effort!

But I have some questions about the swup;

1) I'm using this code:
`$swup = false;
if(isset($_SERVER['HTTP_X_REQUESTED_WITH']) and $_SERVER['HTTP_X_REQUESTED_WITH'] == 'swup'){
$swup = true;`

code for my PHP template I'm following a way like this:

`
if($swup == true){
my codes without header and footer included.
}else{
my code with header and footer.
}
`
And this is working like a champ! But the problem is; when I use ctrl + shift + T to recover my recently closed tab: It's trying to show code without header and footer its showing a page without any css and js... How can I prevent that? Back-Forward button working nice but; ctrl + shift + T is an important keycomb.

2) When I rapidly clicks 4-5 links at the same time; swup getting stuck at transition effect till I refresh my page with ctrl+R. Is there way to prevent this? Like -> if(transition started){stop all click events}
if(transition ended){resume all click events)?

Thank you so much for your help! And sorry for my bad grammer, English is not my main language :)

**Comment by gmrchk** [comment]
Hey, thanks, I'm glad you like swup!

To your questions:
1. This is some weird stuff. Sounds like the browser remembers what was the format of the last request to the URL of the closed tab. Similarly, a browser (at least Chrome) also remembers that some URLs were visited by a `pushState`, and ignores any `popstate` event to that browser history record. 
We could possibly avoid this by making POST requests instead with the swup, but that would require some changes to swup. In particular, we would need to pass a `method: 'POST'` option [here](https://github.com/swup/swup/blob/master/src/modules/loadPage.js#L65). Possibly something to add to swup options?
2. I know about this, already mentioned [here](https://github.com/swup/swup/issues/187) (related). I need to have a look at it. 

Never apologize for your non-native language. 🙂

**Comment by gmrchk** [comment]
Hey, I added the note about the first point in the [swup docs](https://swup.js.org/common-issues#sending-partial-response-for-swup) with recommendations on using some other non-standard response, which should solve the issue. I don't think there is anything more we can do with this to trick browser into doing the correct thing. 
I would maybe argue that lowering the payload size might not be that crucial, even tho it feels great. 🙂 

For the second point, let's follow the other issue thread, please.
