### ISSUE TITLE
Swup not working in Prod Mode (webpack)

### ISSUE THREAD

**Issue by TomaruDev** [swup/swup#248]
Good morning, sir,
I recently created a website made in NodeJS with Express, EJS and Webpack.

When Webpack is in development mode (so the JS file is not compressed), everything works. Swup matters well, transitions are done, everything works perfectly.

However, in production mode (so the JS file is compressed), Swup matters well, however no page change (although the url changes), nor transition. I click on a link, nothing happens, just the url that changes page.

My webpack config :
```js
const webpack = require("webpack");
const uglifyJS = require("uglifyjs-webpack-plugin");
const uglifyCSS = require("optimize-css-assets-webpack-plugin");
const extractCSS = require("mini-css-extract-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const manifestPlugin = require("webpack-manifest-plugin");
const path = require("path");

const purgeCSS = require("@fullhuman/postcss-purgecss") ({
	content: ["./views/*.ejs"],
	defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
})

const config = require("./config.json");

var dev = config.mode === "development"

var webpackConfig = {
	entry: ["./assets/app.scss", "./assets/app.js"],
	output: {
		path: path.resolve("./public/app/"),
		filename: dev ? "app.js" : "[chunkhash:8].app.js",
		publicPath: "/app/"
	},
	
	mode: config.mode,
	watch: dev,
	devtool: dev ? "cheap-module-eval-source-map" : false,
	
	plugins: [
		new extractCSS({
			filename: dev ? "app.css" : "[contenthash:8].app.css"
		})
	],
	
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /(node_modules|bower_components)/,
				use: {
					loader: "babel-loader",
					options: {
						presets: ["@babel/preset-env"]
					}
				}
			},
			{
				test: /\.s[ac]ss$/i,
				use: [
					extractCSS.loader,
					{
						loader: "css-loader",
						options: {
							url: false
						}
					},
					{
						loader: "postcss-loader",
						options: {
							plugins: [
								require("postcss-import"),
								require("tailwindcss"),
								require("autoprefixer"),
								...dev ? [] : [purgeCSS]
							]
						}
					},
					"sass-loader",
				],
			}
		]
	}
}

if(!dev) {
	webpackConfig.plugins.push(new uglifyCSS());
	webpackConfig.plugins.push(new uglifyJS({
		sourceMap: true
	}));
	
	webpackConfig.plugins.push(new manifestPlugin());
	webpackConfig.plugins.push(new CleanWebpackPlugin());
}

module.exports = webpackConfig;
```

app.js :
```js
import Swup from 'swup'
const swup = new Swup()
```

app.scss :
```scss
@tailwind utilities;

/* purgecss start ignore */
@tailwind base;
@tailwind components;

.transition-fade {
	transition: 0.4s;
	opacity: 1;
}

html.is-animating .transition-fade {
	opacity: 0;
}
/* purgecss end ignore */
```

index.ejs :
```html
<!DOCTYPE html>

<html lang="fr">
<head>
	<%- include("includes/head") %>
	<title>DeepGroup - Accueil</title>
	<link rel="stylesheet" href="<%= appCSS %>">
</head>
<body>

	<%- include("includes/header") %>

	<div class="transition-fade" id="swup">
		<h1>Hello !</h1>
		<h2>It's Homepage here !</h2>
		<a href="/about">Go to About page !</a>
	</div>

	<%- include("includes/footer") %>
	<%- include("includes/scripts") %>
	<script src="<%= appJS %>"></script>
	
</body>
</html>
```

about.ejs :
```html
<!DOCTYPE html>

<html lang="fr">
<head>
	<%- include("includes/head") %>
	<title>DeepGroup - About</title>
	<link rel="stylesheet" href="<%= appCSS %>">
</head>
<body>

	<%- include("includes/header") %>

	<div class="transition-fade" id="swup">
		<h1>Hi there !</h1>
		<h2>About page !</h2>
		<h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Soluta quisquam asperiores aut reprehenderit reiciendis mollitia corrupti unde ratione eum, porro odit rerum, vero ipsam, non accusantium veniam itaque repudiandae illo.</h2>
		<a href="/">Go to Home page !</a>
	</div>

	<%- include("includes/footer") %>
	<%- include("includes/scripts") %>
	<script src="<%= appJS %>"></script>
	
</body>
</html>
```

**Comment by TomaruDev** [comment]
If I haven't been clear on certain points, ask me!

sorry if some translations are bad, I'm not English :/

**Comment by gmrchk** [comment]
Hey, there is probably a problem with some of the webpack plugins you're using, but I would need to see a demo to tell you more. 

Also, the [debug plugin](https://swup.js.org/plugins/debug-plugin) could maybe help.

Your English is just fine. 🙂

**Comment by TomaruDev** [comment]
Thank you!
I'll try that when I have time 😁

**Comment by TomaruDev** [comment]
Okay.
I've tried a lot of things to make Swup work, but it doesn't change anything.
So: I tried to change my webpack config, no change at all.
the HTML page, nothing either, it's like in the example,
I installed the swup debugger, I noticed that some actions were present in dev but not in prod.
Also that the dev file was heavier than the prod file, even minimized (when they should be the same size)...

You can go and see on the website: https://deepgroup.fr.
it's in production mode, with the debbuger and sources enabled :)

Here are some screens / files of dev mode :
![image](https://user-images.githubusercontent.com/45178402/76445981-9e603100-63c6-11ea-8578-92b7d9259858.png)

Don't forget to check the file, you'll have a better idea of the situation :)

**Comment by TomaruDev** [comment]
Okay, **now** the server is in prod mode :)
Good Luck ?
...

**Comment by TomaruDev** [comment]
Ok
In the worst case, I would install Swup other than on my bundle.js 
As it won't be managed by webpack, so (normally) there won't be any more errors!

**Comment by TomaruDev** [comment]
help ?

**Comment by jonasfeige** [comment]
I’ve got the same issue. It works fine in development mode but breaks in production mode.
Clicking a link actually updates the browsers URL, bot nothing happens. The debug plugin also does not output any errors.

Any ideas?

**Comment by TomaruDev** [comment]
Okay, I forgot to check back in since the last message.
Finally, I found out where the problem came from: it wasn't because of Swup or Webpack, but because of my css!
Indeed, on my SASS loader, I put a code optimizer (and not a compressor) that will remove all the useless code on the page. Except that there, the CSS is only used in javascript, so it doesn't detect the step and removes the code which is according to it nonexistent.
The solution I found (for me): tweak @fullhuman/postcss-purgecss so that it doesn't remove this particular code. Then, for those who use another program, it will have to be adapted.

Otherwise, another method: themes. You can create a theme for Swup that will do exactly the same thing as CSS but at least there is no more problem :D

**Comment by TomaruDev** [comment]
Well, I'll close this issue as soon as you send me back a message, to see if it works for you :)
If you can't modify your CSS optimizer, try the themes, even the predefined ones, just to see if it works.
Then you can code your own theme if you want ;)

**Comment by TomaruDev** [comment]
@jonasfeige

**Comment by jonasfeige** [comment]
Aah, perfect! It was exactly the same problem, purgeCSS removed the js-classes.
Thanks so much for the quick reply. You can close the issue as far as I’m concerned.

**Comment by TomaruDev** [comment]
You're welcome!
Good luck with your project :)
