### ISSUE TITLE
Problem with isotope filter 

### ISSUE THREAD

**Issue by emanuelepinna** [swup/swup#250]
Hello ,
I have implemented swup in wordpress and everything works correctly except for
isotope filters gallery.
To function properly I have to reload the page.
this is the isotope code that i have implemented

    var $grid = $('#griglia').isotope({
             itemSelector: '.item-griglia',
             percentPosition: true,
             layoutMode: 'masonry',
             transitionDuration: '0.7s'
         });

         // filter items on button click
         $('.filter-button-group').on('click', 'button', function () {
             var filterValue = $(this).attr('data-filter');
             $grid.isotope({
                 filter: filterValue
             });
         });

this is the swup code

        let options = {
            linkSelector: 'a[href^="'+ window.location.origin +'"]:not([data-no-swup]):not([class*="ab-item"]), a[href^="/"]:not([data-no-swup]),a[href^="#"]:not([data-no-swup])',
            animateHistoryBrowsing: false,
            animationSelector: '[class*="transition-"]',
            containers: ["#swup"],
            cache: true,
            plugins: [new SwupPreloadPlugin(), new SwupOverlayTheme({color: '#000'}),new SwupScrollPlugin()],  
        };
     
        const swup = new Swup(options);

can you tell me how i could solve to make the filters work properly without having to reload the page?
thank you for your help!

**Comment by gmrchk** [comment]
Hey hey, have you checked https://swup.js.org/getting-started/reloading-javascript?

**Comment by emanuelepinna** [comment]
Hey @gmrchk... I'm sorry I hadn't seen that in the documentation.
thanks a lot I solved it by entering this code

    document.addEventListener("swup:contentReplaced", function() {

        var $grid = $('#griglia').isotope({
            itemSelector: '.item-griglia',
            percentPosition: true,
            layoutMode: 'masonry',
            transitionDuration: '0.7s'
        });


        // filter items on button click
        $('.filter-button-group').on('click', 'button', function() {
            var filterValue = $(this).attr('data-filter');
            $grid.isotope({
                filter: filterValue
            });
        });
    })
