### ISSUE TITLE
How to use page transition fadein effect

### ISSUE THREAD

**Issue by Naren-hybreeder** [swup/swup#253]
I have 2 pages as of now. What I am doing is, I am trying page transition and I am using below plugin swup. Now my issue is page transition fade in when I click on the menu. I have to display my body content fade in.

can anyone help me out with this issue?

I asked the same question here. You can find the code here. 
Note: only refer code instated of description.
 https://stackoverflow.com/questions/60720007/page-transition-is-not-working-with-swup-js

**Comment by gmrchk** [comment]
Answered on StackOverflow.

**Comment by Naren-hybreeder** [comment]
@gmrchk , Yes, I checked but example is my root folder.
