### ISSUE TITLE
Google AdSense loading multiple times

### ISSUE THREAD

**Issue by ronilaukkarinen** [swup/swup#255]
**Describe your issue**:

Thanks for this script, it's awesome. Is there solution for loading up Google AdSense for "some pages" only? I found solutions for Google Analytics and Tag Manager, but not for AdSense.

I have currently this in my <head> section of header.php (please note that I am using WordPress):

``` php
<?php if ( is_singular() && ! has_tag( 'raha' ) ) : ?>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-8523880252818258",
      enable_page_level_ads: true
    });
    </script>
  <?php endif; ?>
```

Getting:

``` js
Uncaught O {message: "adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page.", name: "TagError", pbr: true, stack: "TagError: adsbygoogle.push() error: Only one 'enab…esyndication.com/pagead/js/adsbygoogle.js:57:409)"}
```

**Swup config or any additional relevant code used**:

```javascript
import Swup from 'swup';
import SwupScriptsPlugin from '@swup/scripts-plugin';
import SwupBodyClassPlugin from '@swup/body-class-plugin';
import SwupGaPlugin from '@swup/ga-plugin';

// Initiate Swup transitions
const swup = new Swup({
  plugins: [
    new SwupScriptsPlugin({
      head: true,
      body: true
    }),
    new SwupBodyClassPlugin(),
    new SwupGaPlugin()
  ]
});
```

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better?

My site is live at https://www.rollemaa.fi/ and you can see if you go to a single article and load up the page there, the ads will show. But if you go via swup to other articles or start from front page and go to single article, no ads shown.

**Comment by ronilaukkarinen** [comment]
Bumping this, as I have tried everything... any tips how to just load the script once after changing page? Adding it to contentReplaced doesn't change the situation.

**Comment by gmrchk** [comment]
Hey @ronilaukkarinen, I really have no experience with AdSense, so I don't think I can help you with this. There seem to be [some hints](https://support.google.com/adsense/thread/17897265?hl=en) on AdSense not supporting single-page applications at all (which website with swup basically is). GA and GTM which you mentioned, both have a JavaScript API to control them for use with swup, but AdSense might not have that. 
I would look for some SPA AdSense solution, or direct the questions to Google guys directly.

**Comment by jose-von-chong** [comment]
idk if you solve it but this is my take on it. import adsense and separate script loading by page path name.
Something like this:
`
import adsense from "adsense";

function init() {
  if (window.location.pathname.includes("about")) {
    adsense.load();
  }
}
init();
swup.on("contentReplaced", init);
`
you can do this for all your scripts actually. Thats how i maintain swup js file mostly clean. only import the init functions for each page and load them based on the path name
