### ISSUE TITLE
external script doesn't work

### ISSUE THREAD

**Issue by nandicol** [swup/swup#262]
Sorry for modify, but i think this exemple is perfect for what i mean and is more clean.

I need a slider-comparision in my page.
I found twenty-twenty ( here for download --> https://zurb.com/playground/twentytwenty).

This code need of more script for work.

In particoular, it needs of:

"jquery/1.10.1/jquery.min.js"
"jquery.event.move.js"
"jquery.twentytwenty.js"
"onemorefunction.js"

So, like i read, i done that:
New js file:

```
function jq(){
   // i downloaded and paste content of jquery.min.js
   }

function event(){
   // i downloaded and paste content of jquery.event.move.js
   }

function twenty(){
   // i downloaded and paste content of jquery.twentytwenty.js
   }

function onemore(){
   // i downloaded and paste content of onemorefunction.js
   }


function twenty-twenty(){
    if (document.querySelector('#mybody')) {
    jq();
    event();
    twenty();
    onemore();
    }
}


const swup = new Swup();

twenty-twenty();

swup.on('contentReplaced', twenty-twenty);
```

If i try this way my function doesn't work (but if i refresh my page whit F5 it work).

Thank you for your halp

**Comment by syntrix** [comment]
if you are doing an npm install I get jQuery to work using this  code

import jquery from "jquery";
window.$ = window.jQuery = jquery;

you would then run your query something like

function init() {
 if (document.querySelector("#lightbox")) {
        // something like $('#lightbox').lightbox()
    }
}

**Comment by gmrchk** [comment]
Closing as a cleanup of old issues, but to answer the question at least a bit - there is no need to run the whole source of jQuery or other libraries after swup transition, only the re-initialization is needed, as @syntrix suggested.
