### ISSUE TITLE
File missing ?

### ISSUE THREAD

**Issue by Vincent-Rocher** [swup/swup#263]
Hello guys,
First, thanks for your work.

I don't have a module compiler on one of my projects. So I want to link the necessary js files.

In you [documentation](https://swup.js.org/themes/overlay-theme), it's written :

> "or included from the dist folder : <script src="./dist/SwupOverlayTheme.js"></script>".

Not all of these files are present in the dist folder. Did I miss something?

Thanks.

**Comment by gothadrummer** [comment]
Bonjour !
Le plugin est ici :
[](https://github.com/swup/overlay-theme)
Bonne journée !
Hi! 
The plugin is to be found here:
[](https://github.com/swup/overlay-theme)
