### ISSUE TITLE
Turn off in animation on history browsing using JS Plugin

### ISSUE THREAD

**Issue by baga89** [swup/swup#264]
**Describe your issue**:
Hi folks, I'm using  **JS plugin (swupjs)** to modify swup for use with javascript animation. Also I'm using **GSAP** library like in swup documentation to easily create an overlay animation between pages and everything works perfect, but I realize that swup executes only **in** animation function when going back or forward inside chrome or firefox. I found in documentation that there is animateHistoryBrowsing option set to false by default, but in my case only **in** animation is triggered. Is there an option to trigger **in** and **out** animation function on popState events or to turn off both functions. 

**Swup config or any additional relevant code used**:
```
const options = [
  {
    from: "(.*)",
    to: "(.*)",
    in: (next) => {
      var tl = gsap.timeline();
      tl.set(".loading-containerX", { scaleX: 1 });
      tl.set(".loading-logo", { opacity: 1, display: "block" });
      tl.to(".loading-containerX", { duration: 1, scaleX: 0, transformOrigin: "center right", stagger: -.05 });
      tl.to(".loading-logo", { duration: .5, opacity: 0, display: "none" }, "-=1");
      tl.from("main p", {
        duration: 1,
        translateY: -50,
        opacity: 0,
        stagger: 0.1,
        ease: Power2.easeOut
      }, '-=1.2');
      setTimeout(next, 1000);
    },
    out: (next) => {
      var tl = gsap.timeline();
      tl.to(".loading-containerX", { duration: 1, scaleX: 1, transformOrigin: "center left", stagger: .05 });
      tl.to(".loading-logo", { duration: 1, opacity: 1, display: "block" }, "-=.8");
      setTimeout(next, 1000);
    }
  }
];

const swup = new Swup({
  plugins: [new SwupJsPlugin(options)]
});
```

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better?

**Comment by gmrchk** [comment]
Hi, sorry for the delay. Looks like a bug in swup, which was ignoring the option for IN animations, but it wasn't visible without the JS plugin. Update to 2.0.12 and you should be good to go. Please let us know if the problem persists.
