### ISSUE TITLE
How to clean up HTML before it will be cached?

### ISSUE THREAD

**Issue by philippdaun** [swup/swup#265]
Is there a simple way to get notified before swup will cache the current page?

I have two specific use cases: remove lazyload classes from `img` elements and remove the `autoplay` attribute from playing video elements so they stop emitting sounds in the background while JS is doing garbage collection.

Example Turbolinks code I'm trying to port over to swup:

```js
$(document).on('turbolinks:before-cache', () => {
  $('.lazyloaded').removeClass('.lazyloaded');
  $('.lazyloading').removeClass('.lazyloading');
});
```

**Comment by philippdaun** [comment]
Nevermind. Not even necessary.

In case somebody else has the same question: swup caches the original, unmodified HTML as it is sent by the server. So any back/forward navigation is always going to inject the original HTML. No need to undo any DOM modifications.

**Comment by gmrchk** [comment]
Hey @daun, sorry for the delay. As you figured out, swup caches the clean unmodified page, so this shouldn't be an issue at all. 
However, note that the first loaded page is cached by swup on startup, which can happen after some other scripts already modified the page in some way. I've never seen anyone having an issue like that, so it's not even mentioned in docs, but we can come up with some simple plugin solution in case it would be a problem.

**Comment by daun** [comment]
Thanks, that's good input. I haven't run into any problems yet, but now that you mention it I'd prefer to be on the safe side here and just disable caching of the initial page. Is there an easy way to uncache the most recently cached page?

**Comment by gmrchk** [comment]
I would just empty the cache after init https://swup.js.org/api/cache.
