### ISSUE TITLE
"Preloader animation" for page with more than 20 images

### ISSUE THREAD

**Issue by ositaka** [swup/swup#269]
Hello, I am trying transform the following code to "pageLoaded", but it doesn't work or I am missing something. I want to have a prealoder spinning while the images are downloading, because I am using Isotope to filter/sort the images and they have to be totally loaded, so the isotope/grid can "arrange" the items properly.

```
document.body.onload = function() {
    setTimeout(function() {
        var preloader = document.getElementById("loader");
        if (!preloader.classList.contains("done")) {
            preloader.classList.add("done");
        }

    }, 1000);
    iso.arrange();

    // remove intro-animation on images for isotope animation
    grid.style.opacity = 1;
    for (let i = 0; i < images.length; i++) {
        const image = images[i];
        image.style.animationPlayState = "running";
        setTimeout(() => {
            image.style.opacity = 1;
            image.style.animation = "none";
        }, 2600);
    }
};
```
This code above it works fine if I am "refreshing/loading" this specific page natively, but I would like to use the `pageLoaded` from swup. Any help?

Regarding the app.js file:

```
swup.on('contentReplaced', function() {
    document.querySelectorAll('[data-swup]').forEach(function(container) {
        loadComponents(components, container);
    });
});

// additional JS
function init() {
  if (document.querySelector(".grid")) {  
   // isotope code 
   + document.body.onload (for the preloader)
 }
}
init();

swup.on('contentReplaced', init);
```

Thank you

**Comment by ositaka** [comment]
I am trying with `pageView` event and it works fine, but if I try with `pageLoaded`, nothing happens.

```
document.addEventListener("swup:pageView", (event) => {
    console.log("loaded")
    document.querySelector("body").style.background = "red";
});
```

**Comment by philippdaun** [comment]
@ositaka From what I understand, `pageView` is the one you want here. It fires on initial load as well as on subsequent navigations. Swup's `pageLoaded` event triggers after a page has been fetched — which would only be true on subsequent navigations, i.e. after I clicked a link and before swup has replaced the content.

**Comment by ositaka** [comment]
@philippdaun thanks for the reply! I've tried out again everything I could and I can't have a " real preloader" to preload the images. The `pageLoaded` event works fine, but I realized that doesn't handle the loading of assets/images.

It's a pity! I was really inspired by the page transition of the swup.js and I can't have, after all, a preloader to handle the images loading -- needed for very slow connections. You can check the "artwork" page here: https://lucverbekekunst.be and smilulate a 3g connection.

@gmrchk do you have any tips for this question?
Thank you guys!

**Comment by gmrchk** [comment]
Hey, sorry for the late reply. I think I have answered a similar question [here](https://github.com/swup/swup/issues/118#issuecomment-474135674), and I can't come up with a better answer. 
TL/DR would be - don't do it, or do it in a very limited way with some reasonable timeout.

Closing as part of the cleanup of old issues. Please, feel free to (re)open if you're still digging into this and we can dig some more.

**Comment by evromalarkey** [comment]
Would be cool if it was possible to pause animating state in . Eg. option when to pause animationPause: "animationOutDone" or event.
Then after everything is loaded, I would trigger swup.animationResume() somewhere in promise or callback and the loading would resume.

This would come in handy also when dynamically loading css (or any other content) for next page, because there could be a point where the css / fonts / images weren't loaded yet but the page was.

**Comment by daun** [comment]
@evromalarkey That's where you would use the JS plugin to return a promise. You're free to wire up any custom logic inside those callbacks.
