### ISSUE TITLE
How do you use plugins with a cdn?

### ISSUE THREAD

**Issue by DavidDuyker** [swup/swup#270]
**Describe your issue**:
I am very much a beginner in terms of js and I think this is going to be a very embarrassing question but I've been troubleshooting for a while and can't seem to figure out how to import plugins.

My main question is if it is possible to load plugins using a cdn? If you can then my questions is about importing them. I've tried importing them with:
```javascript
import SwupScrollPlugin from '@swup/scroll-plugin';
```
At the beginning of my js file but that seems to break it when using a cdn.

**Swup config or any additional relevant code used**:

This is all that I have in my javascript file. I am looking to implement the scroll and head plugins. I started with trying to install the debug plugin but the html no longer has the class="swup-enabled".
```javascript
const options = {
   linkSelector: 'a',
   plugins: [new SwupDebugPlugin()]
};
const swup = Swup();
```
My html I am using the script tag and the unpkg cdn. I looked in the cdn files and didn't see any addresses for the plugins? Do I need to use an npm if I want plugins included?

```html
<!DOCTYPE html>
<html>
<head>
   <!-- Site Descriptions -->
   <meta name="viewport" content="width=device-width, user-scalable=yes">
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <title>homepage</title>

   <!-- CSS -->
   <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,500;0,900;1,400&display=swap" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="/stylesheet.css">
	
   <!-- Script -->
   <script defer src="https://unpkg.com/swup@latest/dist/swup.js"></script>
   <script defer src="/script.js" type="text/javascript"></script>
</head>

<body>
   <div  id="swup" class="transition-fade">
      <div class="content">
	*content deleted from this section*
         <div id="siteMap">
            <h5>
               <a href="/about">About</a>&nbsp&nbsp|&nbsp  
               <a href="/projects/first">first</a>&nbsp&nbsp|&nbsp 
               <a href="/projects/second">second</a>&nbsp&nbsp|&nbsp 
               <a href="/projects/third">third</a>&nbsp&nbsp|&nbsp 
               <a href="/projects/reverv">ReVerv</a>
            </h5>
         </div>
      </div>
   </div>
</html>
```

**Before creating this issue, did you think of...**:
- [x] Have you provided all the helpful information available? 
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you considered creating a demo so we can help you better?

**Comment by nateads** [comment]
@DavidDuyker Not sure if you are still stuck on this. I was also looking for a CDN for the plugins and there don't seem to be any. If you're not using a package installer you can npm install the scripts you want using a localhost and copy over the js files you need from their /dist/ folders. That's what I ended up doing.

In regards to your script.js file you need to include your options inside your swup instance.
Original
`const options = {
   linkSelector: 'a',
   plugins: [new SwupDebugPlugin()]
};
const swup = Swup();`

Should be
`const options = {
   linkSelector: 'a',
   plugins: [new SwupDebugPlugin()]
};
const swup = Swup(options);`

Hope this info helps.

**Comment by DavidDuyker** [comment]
Thanks @nateads 
I ended up doing the same as you with linking the pluggin js files. It seems like that is the most straight forward way of doing things without installing node in the host server.
