### ISSUE TITLE
Swup Scroll Plugin Wrong scroll position

### ISSUE THREAD

**Issue by afmarchetti** [swup/swup#271]
When animateScroll is true the scroll position is ok if i scroll from the same page, but if i have a link with an achor ex.

www.mysite.com/contacts/#mail 

the scroll position is not correct, any idea?

**Comment by philippdaun** [comment]
@afmarchetti I submitted a PR for an `offset` feature that would allow you to specify the header height and offset the scroll position accordingly. That might be what you want: https://github.com/swup/scroll-plugin/pull/5

**Comment by mindshaped** [comment]
Experiencing the same issue as @afmarchetti here. I'm using the Swup default options and Swup Scroll Plugin (animateScroll: true) and anchor links pointing to the current site are working fine – but as soon as they're pointing to another page/route, the scroll position is way off (not just the offset of the header height, but it looks rather like scroll plugin tries to calculate the distance too early/late).

Example: 

when on /home and clicking an anchor link that goes to /home/#section it works fine
when on /home and clicking anchor link that goes to /home/page2/#section the offset is wrong (scrolling stops way too early)

thanks
-N.

**Comment by mindshaped** [comment]
@afmarchetti my current workaround for the time being:

- remove the swup scroll plugin & use swup events and custom scroll functions instead

`swup.on('contentReplaced', function () {
      var hash = window.location.hash
      if (hash.length) {
        window.scrollTo(0, $(hash).offset().top - 60)
      }
    })`

`html {
  scroll-behavior: smooth;
}`

the above scrolls to your anchors when changing pages (that's what wasn't working properly before) and you can include offsets here too. as for smooth scrolling, I'm using the native css feature for this and you might add a polyfill for browsers that don't support it: https://github.com/iamdustan/smoothscroll

the only thing you still have to do then, is catching anchor links that point to the current page viewed, something like this (sure there's nicer vanilla ways of doing this):

`// test for anchor links  
    $('a').on('click', function () {  
      var link = $(this).attr('href')
      var hash = link.substring(link.indexOf('#') + 1)
      if (link.indexOf('#') !== -1 && link.indexOf('http') === -1) {
        if (hash.length && $('#' + hash).length) {
          window.scrollTo(0, $('#' + hash).offset().top - 60)
        }
      }
    })`

Hope this helps,
would be nice to use the clean & simple Swup Scroll Plugin for this though!

-N.

**Comment by afmarchetti** [comment]
@mindshaped cool, i will test it soon, many thanks!

**Comment by gmrchk** [comment]
I'm not able to replicate the issue. @mindshaped solution should work nicely, but an interesting thing is that it's exactly what the scroll plugin does as well, including using the `contentReplaced` event. Maybe the [calculation of offset is wrong](https://github.com/swup/scroll-plugin/blob/ac2b6a14305fc06a8baf88f64b6806428779094d/src/index.js#L114), but I don't think it is. 🤷‍♂️ 

If someone can, please provide a browser or a link where the issue is present. 

It's a bit of an old issue, so I will close as part of the cleanup. Please, feel free to (re)open if you're still digging into this.
