### ISSUE TITLE
Scrolling back to top before switching content with animateHistoryBrowsing

### ISSUE THREAD

**Issue by thevisualfox** [swup/swup#272]
Hi, 

I was wondering if someone could help me with the following option: animateHistoryBrowsing.
If you use the next/previous browser buttons the page first scrolls to the top before changing the content. This looks very jarring. I don't have any scrolling libraries nor any height/width styles on the html/body tags.

I tried to compensate with setting the window.scrollY position to the recorded value before changing the content, but that didn't work.

There's a closed related answer, but that does not answer my question sadly.

Thanks in advance.

**Comment by gmrchk** [comment]
Hey, this sounds like you're using the scroll plugin together with its option of `doScrollingRightAway` set to true. `animateHistoryBrowsing` option can have these negative effects on the Scroll plugin. There is even a disclaimer about scrolling in [option docs](https://swup.js.org/options#animate-history-browsing). Please, try to play with the scroll plugin options.

You can also change swup plugin options on the go if needed.
```javascript
swup.plugins.find(plugin => plugin.name === 'ScrollPlugin').options.doScrollingRightAway = true;
```

Closing as part of the cleanup of old issues. Please, feel free to (re)open if you're still digging into this.
