### ISSUE TITLE
JS Plugin Animation Only Running Once

### ISSUE THREAD

**Issue by dayneh88** [swup/swup#273]
Hi,

I'm not sure if this a question for SWUP or for GSAP but I'm using GSAP 3 to create some animations I'd like to use during certain pages.

I've created 1 of those animations and it's working really well.

You can view it here: https://makemodels.weareduo.com.au/

If you click 'What we do' in the top navigation you see that the animation works great and loads the new page, but when you try and click on a new page ('Projects' for example) the animation never loads again.

For some reason, trying to enter my JS from app.js isn't working so here is a link to the app.js file on my STAGING environment:

http://makemodels.weareduo.com.au/wp-content/themes/makemodels/components/app/index.js

Any help would be greatly appreciated. P.S. SWUP is so much better than barba.js haha

Thanks so much,
Dayne

**Comment by gmrchk** [comment]
Hey @dayneh88, sorry for the delay. I can see you already fixed your issue. Could you post what was wrong for future reference? 
Cheers!

**Comment by dayneh88** [comment]
Hi @gmrchk Thanks for getting back to me. I actually did manage to get this issue resolved. If you wouldn't mind looking at this issue if you have time: https://github.com/swup/swup/issues/275 

Would be greatly appreciated. Thanks
