### ISSUE TITLE
Really need  your help!

### ISSUE THREAD

**Issue by Clleo** [swup/swup#274]
Hello, Georgy.
I trying to put your script «Swipe» on my own websites.
But I get a mistake of loading some scripts.
I'm not a Java script expert
But I think it's a mistake because Swipe breaks
standard lifecycle of scripts.
Can you help me solve this problem.

I'd appreciate it if you could give me an example of the code
For correct loading of scripts.

Thank you very much for the answer, with respect from Konstantine of Russia.

Example of script  that makes a download error:

<script src="/js/swup.js"></script>

<script src="/js/jquery-3.5.0.min.js"></script>	

<script defer src="/js/aos_animate.min.js"></script>

<script src="../plugins/glide-3.4.1/dist/glide.min.js"></script>

<script>
new Glide('.glide', {

	type: 'carousel',
	perView: 5,
	focusAt: 'center', 
.mount()
</script>

How am I supposed to write the scripts of these scripts?

**Comment by AugustMiller** [comment]
Hey!

Please refer to the "[Reloading Javascript](https://swup.js.org/getting-started/reloading-javascript)" section of the documentation—it sounds like you need to make sure your slider code is initializing on the first page load, then _again_ after every Swup page transition:

```js
// Set up an "init" function to bootstrap your page scripts:
const init = () => {
  new Glide('.glide');
};

// Run the initializer once, for "cold-loads" (the first time your `script` tag is downloaded and executed: 
init();

// Set up Swup:
const swup = new Swup({
  containers: ['#swup']
});

// Then, use Swup events to trigger `init` again after every subsequent navigation:
swup.on('contentReplaced', init);
```

FYI, it looks like there are some significant formatting issues with the code you posted—I'm seeing unclosed brackets/parentheses that would definitely prevent your galleries from initializing properly.

Let us know if this helps!
