### ISSUE TITLE
Different transition page out and in

### ISSUE THREAD

**Issue by iamalessiopaoletti** [swup/swup#276]
Hi!

Sorry, I don't know where write for this help.

I'm trying to animate the page and out in different mode like this website:

[https://www.rezo-zero.com/](https://www.rezo-zero.com/)

I tried with css animation but nothing,
now I'm trying with JS plugin and anime.js, and I managed to have different animation for out #swup and in #swup containers,
but animations are always one after the other, so I tried to call the callback "next" at the beginning of the "out" animation, but "swup" skip directly at the "in" animation.

I would the animations must start together.
how can I do?

`
const options = [
                {
                from: '(.*)',
                to: '(.*)',
                in: function(next) {
                    
                        var animazione_swup_in = anime ({
                            targets: '#swup',
                            translateY: ['100vh','0vh'],
                            easing: 'linear',
                            duration: 1500,
                            complete: next
                        });
                },
                out: (next) => {
                    
                        var animazione_swup_out = anime ({
                            targets: '#swup',
                            translateY: ['0vh','-10vh'],
                            easing: 'linear',
                            duration: 3000,
                            complete: next
                        });
                }
                }
            ];`

Can anyone

**Comment by syntrix** [comment]
this is an example of my code with GSAP. It has a custom transition (using an attribute on a clickable link) and the default transition. hope it helps

`const swup = new Swup({
    plugins: [
        new SwupJsPlugin([{
            from: "(.*)",
            to: "(.*)",
            in: (next, context) => {
                const custom = context.transition.custom // custom transition name, or undefined

                if (custom === 'my-custom-transition') {
                    var tl = gsap.timeline();

                    tl.from(".test", {
                        duration: 1,
                        opacity: 0,
                        x: 250,
                    })
                    tl.from(".try", {
                        duration: 1,
                        opacity: 0,
                        x: 150,
                        onComplete: next,
                    });

                } else {
                    var tl = gsap.timeline();

                    tl.from(".test", {
                        duration: 1,
                        opacity: 0,
                        y: 100,
                        onComplete: next,
                    });
                }
            },
            out: (next, context) => {
                const custom = context.transition.custom // custom transition name, or undefined

                if (custom === 'my-custom-transition') {
                    var tl = gsap.timeline();
                    tl.to("#swup", {
                        duration: 0.3,
                        opacity: 0,
                    })

                    tl.from(".custom-transition", {
                        delay: 1,
                        duration: 0.6,
                        scaleY: 1,
                        transformOrigin: "bottom left",
                        opacity: 1,
                        onComplete: next,
                    });

                } else {
                    var tl = gsap.timeline();
                    tl.to(".test", {
                        duration: 1,
                        opacity: 0,
                        x: 100,
                        onComplete: next,
                    });
                }
            },
        }]),
    ],
});

`

**Comment by iamalessiopaoletti** [comment]
Hi syntrix!

Thanks for the reply, do you have an example link of this code?
And do you think I could use anime.js to do it?

**Comment by gmrchk** [comment]
Hi, yes, using anime is supported. However, swup doesn't support having current and next page containers at the same time. The only option is to go with some hack, where it looks like both containers exist at the same time, but are not. 

Closing as part of the cleanup of old issues. Please, feel free to (re)open if you're still digging into this.
