### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by dayneh88** [swup/swup#277]
Hi SWUP Community,

It would be awesome if there was a Slack Channel for SWUP. I know that Barba has one and it's incredibly valuable. Not sure if this is in the pipeline but would be an awesome addition to an already amazing library!

**Comment by gmrchk** [comment]
Hi, I've been playing with the idea of extending the community somehow more and introducing some kind of forum or something, but nothing clear yet. Maybe GH discussion could be a way, once it's out of beta. 

Anyways, I think the Slack channel is not the best format for a library like swup, but let's see. Thanks for the tip! 👍
