### ISSUE TITLE
I can't get the minified version through CDN to work

### ISSUE THREAD

**Issue by jelliedpizza** [swup/swup#280]
I think I've looked everywhere now, but I just cannot find a solution to my issue (This can be also because I'm a JS beginner)
  
I import swup with `<script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>`  

This is my script.js that I include in every page with `<script defer src="/script.js"></script>`:
```javascript
import Swup from 'swup';
const swup = new Swup();
```  
and I get this error:  

```javascript
Uncaught SyntaxError: Cannot use import statement outside a module
```

**Comment by gmrchk** [comment]
Hey @jelliedpizza, I see you already resolved your issue. Could you please post what was the problem, please?

**Comment by jelliedpizza** [comment]
Hey, I have tried everything on multiple machines, but for some odd reason the CDN version would not work for me. I solved the issue by installing the release with npm and that worked for some reason.

**Comment by gmrchk** [comment]
CDN version is actually fine, but it will create global object `window.Swup` that you can use without importing. You only need to import when you use the script from npm or such and are building your scripts with webpack, rollup, etc. Actually, you cannot import things directly in browser, hence the error.
