### ISSUE TITLE
Swup won't transition when used without the theme plugin

### ISSUE THREAD

**Issue by ronca85** [swup/swup#282]
Hello.

I was following the docs but was unable to get swup to work. Only after including the SwupFadeTheme plugin it worked. Is the theme plugin necessary to get it working? Without the theme plugin the debug plugin shows it stops on the swup:pageLoaded event.

I have three bare bones pages and i am using parceljs to compile. I've tried using npx serve but ran into different issues. The thing works when fade theme plugin is used. What does this plugin do that the core swup doesn't?

**Comment by gmrchk** [comment]
Could you please add your resolution? What was wrong?
