### ISSUE TITLE
I'm Sure I Made a Dumb Mistake

### ISSUE THREAD

**Issue by graywmitchell** [swup/swup#283]
**Describe your issue**:
I'm having a problem on the website I'm developing where the scroll position is retained from the previous page to the next. I created a demo to demonstrate the issue. When the link at the bottom is clicked, the scroll position will be at the bottom of the next page.

I saw on a different issue that swup does not affect scroll position so I cant figure out why this is happening.

**Swup config or any additional relevant code used**:

```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/swup@2.0.10/dist/swup.js"></script>
    <title>Document</title>
</head>
<body>
    <main id="swup" style="height: 5000px;" class="transition-fade">
        <a href="/test2.html">click here</a>
        <a href="/test2.html" style="bottom: -4000px; position: absolute;">click here</a>
    </main>
    <script>const swup = new Swup();</script>
    <style>.transition-fade {
        transition: 0.4s;
        opacity: 1;
      }
      
      html.is-animating .transition-fade {
        opacity: 0;
      }</style>
    
</body>
</html>
```
```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/swup@2.0.10/dist/swup.js"></script>
    <title>Document</title>
</head>
<body>
    <main id="swup" style="height: 5000px;" class="transition-fade">
        <a href="/test.html">then click here</a>
        <a href="/test.html" style="bottom: -4000px; position: absolute;">click here</a>

    </main>
    <script>const swup = new Swup();</script>
<style>.transition-fade {
    transition: 0.4s;
    opacity: 1;
  }
  
  html.is-animating .transition-fade {
    opacity: 0;
  }</style>
</body>
</html>
```

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better?

**Comment by AugustMiller** [comment]
Hey, @graywmitchell! You might be looking for the [scroll plugin](https://swup.js.org/plugins/scroll-plugin).

It's a pretty good drop-in extension for restoring scroll position (i.e. to the top of the next page, or the location on the previous page, when using the _back_ button).

Let me know if you have any issues implementing this!
