### ISSUE TITLE
Swup works on local server but fails to load on a host server ie. github pages

### ISSUE THREAD

**Issue by Goob-hub** [swup/swup#284]
gjs2002.github.io/:6 GET https://gjs2002.github.io/node_modules/swup/dist/swup.min.js net::ERR_ABORTED 404
gjs2002.github.io/:7 GET https://gjs2002.github.io/Static/js/app.js net::ERR_ABORTED 404

those are the errors I get, basically it cant find the folder even though its located in my code
idk what to do

**Comment by AugustMiller** [comment]
It appears as though this account and/or Pages site has been deleted—I suspect this is just a question about how relative URLs work with GitHub pages, not necessarily with Swup.

If you can identify a Swup-specific issue, please let us know!

**Comment by gmrchk** [comment]
Every project on GH pages is stored under some specific URL path (eg.  https://gjs2002.github.io/`your-repo-name`), not the root of the domain. The link to swup needs to be adjusted for that.
