### ISSUE TITLE
How to use the getPageData() method?

### ISSUE THREAD

**Issue by joh-sch** [swup/swup#285]
**Issue**:
I want to start experimenting with the `getPageData` method [mentioned in the SWUP docs](https://swup.js.org/api/methods). The docs do not give an example of how to use it, so I tried passing it a regular URL…

`swup.getPageData("http://my-site.com/my-page")`

…which throws an error:

<img width="939" alt="Screen Shot 2020-07-12 at 13 55 04" src="https://user-images.githubusercontent.com/39758027/87245650-64bc3700-c447-11ea-868e-6a30aa6fed86.png">

Could you provide a simple example of how the method is intended to be use?

**Comment by AugustMiller** [comment]
Hiya!

I can't speak to why this is exposed in the documentation. The method is used internally to transform a Response (from Swup's own `fetch()` helper implementation) into a Swup-specific data structure.

_In theory_, you could use it to parse an externally-fetched HTML fragment in the same way Swup would process it. _However_: as far as I can see, the implementation is dependent upon it being mounted as a method on the main Swup instance. With some quick hacking, I couldn't adequately mock the parts of Swup it depends on (to make it work as a pure function).

It looks like you've already tried using the helper attached to your Swup instance—this I can't explain.

Sorry for the non-answer! Overall, I'd recommend staying within the regular page lifecycle, and if you need to fetch + parse HTML outside of it, it's probably best to own that code. :v:

**Comment by gmrchk** [comment]
Heyou guys,

@AugustMiller you were actually very close. As you said, implementation depends on it being a method. I never wanted to make it an option, as it's not too obvious use case for most people, so this was the second-best thing to allow custom behavior. 

Let's jump right to the answer... In short, you need to rewrite the method with your own implementation. The method will receive request with whatever is returned by the server (normally an HTML page, but can be whatever you make it), and it should spit out the swup cache object. 

```javascript
{
    title: 'Page title', // title of the page    
    pageClass: 'body-class', // not needed by swup and can be empty, but some plugin might use it
    originalContent: 'html content of page', // not needed by swup and can be empty, but some plugin might use it
    blocks: ['<div id="swup"></div>'], // required same number of blocks for each page
    responseURL: '/redirected-url' // just in case page is redirected to another URL, this is where the actual URL is stored
}
```

You should be able to do the rewriting in a few ways.

```javascript
import Swup from 'swup';


class CustomSwup extends Swup {
    getPageData(xhrRequest) {
        // do your stuff
       return {title, pageClass, originalContent, blocks, responseURL}; 
    }
}

const swup = new CustomSwup();
```
or  simply by
```javascript
import Swup from 'swup';

const swup = new Swup();
swup.getPageData = ...;
```
---
I can specify this more clearly in docs, but you're both right - it's not too obvious, and for example, plugin that would accept function and overwrite the method in running swup instance would probably be much more simple to use and understand. It could also check the validity of the provided function somehow as well. 
Would some like to create a super simple plugin for that? Swup CLI should make that a piece of cake. Here's [how to](https://swup.js.org/plugins/create-plugin).

**Comment by gmrchk** [comment]
Yoyo, [here](https://swup.js.org/plugins/custom-payload-plugin) we go. Please consider the plugin as "beta" for now.
