### ISSUE TITLE
swup slider css error 

### ISSUE THREAD

**Issue by mesutuca33** [swup/swup#288]
hello I am using "swup" plugin. When I switched between pages, I noticed that the slider was not working because it was not working, when I refreshed the page, the slider was working, I noticed that this error was caused by not loading css and js. How can I load specific js and css after swup?
`
    const swup = new Swup({
        plugins: [new SwupScrollPlugin({doScrollingRightAway: false, animateScroll: true, scrollFriction: 0.3, scrollAcceleration: 0.04,})]
    });
`

[stackoverflow](https://stackoverflow.com/questions/63203740/html-swup-slider-css)

**Comment by AugustMiller** [comment]
Hey!

Please refer to the "[Reloading Javascript](https://swup.js.org/getting-started/reloading-javascript)" section of the documentation—it sounds like you need to make sure your slider code is initializing on the first page load, then _again_ after every Swup page transition:

```js
// Set up an "init" function to bootstrap your page scripts:
const init = () => {
  const $mySlider = $('.my-slider');
  $mySlider.someMethod();
};

// Run the initializer once, for "cold-loads" (the first time your `script` tag is downloaded and executed: 
init();

// Set up Swup:
const swup = new Swup({
  plugins: [
    new SwupScrollPlugin({
      doScrollingRightAway: false,
      animateScroll: true,
      scrollFriction: 0.3,
      scrollAcceleration: 0.04
    })
  ]
});

// Then, use Swup events to trigger `init` again after every subsequent navigation:
swup.on('contentReplaced', init);
```
