### ISSUE TITLE
Swup issue with reloading GSAP JS  (with oxygen wordpress) 😢 

### ISSUE THREAD

**Issue by maxence-svensson** [swup/swup#290]
Hello everyone, I'm currently making a site on wordpress using oxygen builder, I'm trying to put transitions between pages and for that I tried barba.js first but I quickly found myself facing a problem, my js scripts don't reload on each page. So I tried Swup and I found myself facing the same problem, my js scripts don't reload and moreover the videos under oxygen don't play anymore .... 

I use **SwupScriptsPlugin** to restart the scripts but it doesn't do anything.

```javascript
function anim() {
    var childSplit = new SplitText(".bloc_header--header", {type:"lines",  linesClass: "bloc_header--header-child"});
    var parentSplit = new SplitText(".bloc_header--header", { type: "lines", linesClass: "bloc_header--header-parent"});

    var w = window.innerWidth;
    var size = w > 1366 ? "big" : "small";
    if (size === "big") {
        gsap.from(childSplit.lines, {
            scrollTrigger: {
                trigger: ".bloc_header--header",
                toggleActions: "play pause pause pause"
            },
            delay: 1,
            duration: 0.5,
            yPercent: 100,
            ease: "power4",
            stagger: 0.1
        }, );
    }
}

const swup = new Swup({
    plugins: [
        new SwupScriptsPlugin({
            head: true,
            body: true
        }),
        new SwupOverlayTheme({
            color: '#f41d5e',
            duration: 600,
            direction: 'to-right',
        })
    ]
});

function init() {
    new anim();
}

document.addEventListener('swup:contentReplaced', function () {
    init();
});
```

Thank you in advance for your help. 🙏

**Comment by mesutuca33** [comment]
I understand that you want to run js again, I had this problem and stackoverflow opened a topic about it and found the answer myself.
If this is your problem, you can try it from the link below.
[Adress](https://stackoverflow.com/questions/63209630/html-barbajs-slider-transition)

**Comment by mabe2007** [comment]
i'm using swup with wordpress, bootstrap 4 and scrolltrigger/gsap. i've the same problem. when i navigate between pages no scrolltrigger container displays. as i'm not very familiar with js, i would appreciate a general solution to force swup to reload all scripts in my footer. any help? :)

**Comment by gmrchk** [comment]
Hi, [this](https://swup.js.org/getting-started/reloading-javascript) is the best explanation I can provide. In short, swup (or any other library doing a similar thing) can't ensure that all the other scripts work out of the box without a bit of extra work. 
[Script plugin](https://swup.js.org/plugins/scripts-plugin) is one of the options to solve it, but it's not a silver bullet and may or may not work (and it's kinda hacky, so I would avoid it anyway if you can). 
In that case, the solution differs per case, and I can't help with specific solutions. Please try SO or other forums for that.
