### ISSUE TITLE
Swup throws: Uncaught TypeError: S is not a constructor

### ISSUE THREAD

**Issue by mahish** [swup/swup#291]
**Describe your issue**:
Swup `2.0.8` does not work. It throws following error: `Uncaught TypeError: S is not a constructor`. It points to `plugins` listing in `swupOptions`. If I remove all plugins then it points to `new Swup(swupOptions)`. 

Im using latest `rollup` to bundle my javascript. See demo here: https://oak-ri0cz1k3e.vercel.app

**Swup config or any additional relevant code used**:

1. Swup init on `domLoad`:
```javascript
import Swup from 'swup';
import SwupBodyClassPlugin from '@swup/body-class-plugin';
import SwupDebugPlugin from '@swup/debug-plugin';
import SwupPreloadPlugin from '@swup/preload-plugin';

const swupOptions = {
    containers: [
      '[data-web-swup="header"]',
      '[data-web-swup="main"]',
      '[data-web-swup="footer"]',
    ],
    plugins: [
      new SwupBodyClassPlugin(),
      new SwupDebugPlugin(),
      new SwupPreloadPlugin(),
    ],
};

const swup = new Swup(swupOptions);
```

2. Rollup config:
```javascript
rollup: {
    app: {
      bundle: {
        input: 'src/js/app.js',
        plugins: [
          nodeResolve(),
          commonjs(),
          babel({ babelHelpers: 'bundled' }),
          terser(),
        ],
      },
      output: {
        file: 'dist/assets/js/app.build.js',
        format: 'iife',
        name: 'oak',
        sourcemap: true,
      },
    },
  },
```

3. Babel config
```json
{
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-template-literals",
    "@babel/plugin-transform-shorthand-properties",
    [
      "@babel/plugin-proposal-object-rest-spread",
      { "useBuiltIns": true }
    ]
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ]
  ]
}
```

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better?

**Comment by mahish** [comment]
I guess there is an issue with the way how rollup bundles code. I suppose the issue might be fixed by providing es6 version of the library.  See: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by mahish** [comment]
I manually copied source files from the swup itself and the plugins I need to my project directory, then bundled by myself with Rollup and it is working fine.

Is there way how to produce es6 bundle with Webpack?

**Comment by gmrchk** [comment]
Hey, version of swup in npm points to the version transpiled to es5 by Babel (not bundled). You can also import bundled version from `swup/dist/swup.js` (or similar for plugins) which, I think, should work anywhere out of the box. 

Swup (and plugins) currently don't provide es6 module format. However, none act as they do, so there is likely something wrong with the bundler setup on your side. I have limited experience with Rollup, so I'm not sure I can help without further research. Maybe `nodeResolve` looks suspicious for the browser app? 🤷‍♂️ 

Anyways, I would happily accept a PR to add support for "mjs" to swup. I don't think webpack supports this, (again, not sure) but adding a small Rollup setup just for this progressive standalone feature sounds alright too. I can later copy the solution to all the plugins on my side.

**Comment by mahish** [comment]
@gmrchk Thanks for the reply.

`nodeResolve` should simply resolve path to `node_modules`, I was more suspicious of `commonjs` which is responsible for imports of non-es6 modules (which is the case). I went through their [issues](https://github.com/rollup/plugins/issues?page=1&q=is%3Aissue+commonjs) and found [this one](https://github.com/rollup/plugins/issues/527) so I downgraded from 14 to 13 and it does work now, yay! They claim they fixed the issue and release it in next version of the plugin.

**Comment by mahish** [comment]
Regarding rollup setup for "mjs", I can create PR later this or next week. Should not be a problem.
