### ISSUE TITLE
Materialize CSS sidenav

### ISSUE THREAD

**Issue by joepvdm013** [swup/swup#292]
I used a very basic swup transition on my website but now when i go to a smaller screen my sidenav from Materialize doesn't work anymore. When I click on the hamburger menu everything is greyed out. Then when I navigate on full screen that navbar hamburger menu icon doesnt even open at all(so it only opens up at the first try). I checked and I gave the header the swup id and a transition-fade class. And the nav and sidenav are both located in there. 

Can this be a problem with Jquery? As the sidenav activates when the document is ready.

Is this a common issue or do I need to provide some code? Never asked for help online before tbh.

**Comment by AugustMiller** [comment]
This sounds like an issue with when your initialization code is being triggered. If your side-nav is replaced on each page transition, it won't re-initialize without a bit of work:

```js
swup.on('contentReplaced', (e) => {
  M.Sidenav.init(document.querySelector('.my-sidebar'));
});
```

Or, better yet, just extract all that into an `init` method:

```js
// Define initializer function:
const init = () => {
  M.Sidenav.init(document.querySelector('.my-sidebar'));
};

// Listen for subsequent page navigation events, using the `init` method as a callback:
swup.on('contentReplaced', init);

// Call once on the initial page load (or use `$(init)` in jQuery-land!):
window.addEventListener('load', init); 
```

**Comment by joepvdm013** [comment]
@AugustMiller First of all, thanks for your reply! I tried it but without success. Maybe I don't understand it very well. But this is what I got(my Javascript code).

 ` 
 const swup = new Swup();

  const init = () => {
  $('.sidenav').sidenav();
  };

  // Listen for subsequent page navigation events, using the `init` method as a callback:
  swup.on('contentReplaced', init);

  // Call once on the initial page load (or use `$(init)` in jQuery-land!):
  document.addEventListener('DOMContentLoaded', init);
`

My html code triggers the .sidenav class from Materialize

**Comment by AugustMiller** [comment]
Could you post the relevant parts of your template/HTML file (showing your Swup container, as well as the location within the `head` or `body` were you're including this script)? I can't say why it's not working without a better picture of your setup.

I'd also recommend adding a `console.log();` or `debugger;` statement to your `init()` method so you can tell when it's running (instead of relying on side-effects of instantiating the nav, via Materialize).
