### ISSUE TITLE
How to make form clickable on page? 

### ISSUE THREAD

**Issue by gamenic-kapil** [swup/swup#296]
I used WordPress plugin to develop the form which is in ajax call. I could not click on the form input value on swup but with reloading the page I can input the check field on the form. What should I do?

**Comment by AugustMiller** [comment]
Hey!

Swup doesn't automatically re-initialize scripts after the initial page load. Chances are, Wordpress is injecting extra `script` content in your document—locate those, and then refer to the documentation on [Reloading Javascript](https://swup.js.org/getting-started/reloading-javascript) to adapt the scripts to initialize on load _and_ on subsequent Swup navigations.

See #292 for an example of how to accomplish this, with a third-party library. Supporting Wordpress (including how to manage javascript output by plugins) is out Swup's purview, but you should be able to continue looking in the WP community with our documentation on-hand!
