### ISSUE TITLE
Override scrollTo plugin

### ISSUE THREAD

**Issue by psntr** [swup/swup#298]
Hi there,

I don't understand how to override the scrollTo plugin behaviour. By default when the page changes, the scrollTo plugin scroll to the top of the page, after the `swup:contentReplaced` event.

My question is, how to use the method `swup.scrollTo(document.body, 2000)` for a specific page?

To trigger action on my page I use a "date-template" attached to my `<main data-template="project">` HTML and in my javascript I have something like that:

```
swup.on('contentReplaced', init);

function init() {
    document.querySelectorAll('[data-swup]').forEach(function (container) {
        switch (container.dataset.template) {
            case 'project':
                // Here I don't want to scrollTo 0,0 from the default scroll Plugin
            break;
        }
    )}
}
```
I try to randomly add the `swup.scrollTo(document.body, 2000)` in different parts of the code, but every time it's scrolling back to the top.

**Comment by aleclarson** [comment]
Can you share your solution, @psntr ?
