### ISSUE TITLE
swup break site using quantcast choice script

### ISSUE THREAD

**Issue by vincenzocasu** [swup/swup#301]
Hi everyone,
i am having trouble with swup using it in conjunction with the quantcast choice script.

Until before using this script to manage consent on cookies, everything worked perfectly.

Once this script was inserted, the layout broke on loading each page.

I inserted the container class of the interfering element in containers within the swup configuration options and now the layout is preserved.

In the meantime, however, with each click on the website links, the pages reload completely and swup does not work as it should.

How can I solve?

**Comment by vincenzocasu** [comment]
In the console is reported this error: 

swup.min.js:1 Uncaught TypeError: Cannot set property 'responseURL' of null
    at e (swup.min.js:1)
    at new e (swup.min.js:1)
    at scripts-v8.js:95

**Comment by vincenzocasu** [comment]
I think it is due to the fact that the element is loaded at a later time than the page load, and therefore swup cannot find the container element because at that moment it is not yet present in the document ...

I tried to put the initialization in a timeout, but it doesn't fix the problem.

**Comment by daun** [comment]
I think it's safe to assume that swup only works if all the content containers are present on load and on each visit.

Do you have an example of the markup on load and what's inserted/changed by the external script?

**Comment by vincenzocasu** [comment]
Yes, this is my code that works well only first time...

[....]

`
setTimeout(function(){

      let containers = [
         '#main-menu',
         '#swup'
      ];

      if($('#wpadminbar').length){
         containers.push('#wpadminbar');
      }

      let swup_options = {
         linkSelector: 'a[href^="'+document.location.origin+'"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]), a[href^="'+document.location.origin+'?#"]:not([data-no-swup])',
         containers: containers,
         animationSelector: '[class^="a-"]',
         cache: false,
         plugins: [
            new SwupScrollPlugin({
                doScrollingRightAway: true,
                animateScroll: false,
                scrollFriction: 0.3,
                scrollAcceleration: 0.04,
            }),
            new SwupBodyClassPlugin(),
            new SwupFormsPlugin({formSelector: '.my-custom-form'}),
            new SwupHeadPlugin(),
         ],
         skipPopStateHandling: function(event){
            if (event.state && event.state.source == "swup") {
               return false;
            }
            return true;
         },
      }

      const swup = new Swup(swup_options);

      // load scripts for replaced elements
      document.addEventListener('swup:contentReplaced', event => {

         //close menu on reload content mobile
         if( !$('.navbar-toggler').hasClass('collapsed')){
            $('.navbar-toggler').addClass('collapsed');
         };

         $('.navbar-collapse').removeClass('show');

         //reinitialize all scripts
         init_theme();

      });
   }, 500);

`

[...]

`
function init_quantcast(){

      var host = window.location.hostname;
      var element = document.createElement('script');
      var firstScript = document.getElementsByTagName('script')[0];
      var url = 'https://quantcast.mgr.consensu.org'
      .concat('/choice/', '3eEquhNUqeTMD', '/', host, '/choice.js')
      var uspTries = 0;
      var uspTriesLimit = 3;
      element.async = true;
      element.type = 'text/javascript';
      element.src = url;

      firstScript.parentNode.insertBefore(element, firstScript);

      function makeStub() {
         var TCF_LOCATOR_NAME = '__tcfapiLocator';
         var queue = [];
         var win = window;
         var cmpFrame;

         function addFrame() {
            var doc = win.document;
            var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

            if (!otherCMP) {
               if (doc.body) {
                  var iframe = doc.createElement('iframe');

                  iframe.style.cssText = 'display:none';
                  iframe.name = TCF_LOCATOR_NAME;
                  doc.body.appendChild(iframe);
               } else {
                  setTimeout(addFrame, 5);
               }
            }
            return !otherCMP;
         }

         function tcfAPIHandler() {
            var gdprApplies;
            var args = arguments;

            if (!args.length) {
               return queue;
            } else if (args[0] === 'setGdprApplies') {
               if (
                  args.length > 3 &&
                  args[2] === 2 &&
                  typeof args[3] === 'boolean'
               ) {
                  gdprApplies = args[3];
                  if (typeof args[2] === 'function') {
                     args[2]('set', true);
                  }
               }
            } else if (args[0] === 'ping') {
               var retr = {
                  gdprApplies: gdprApplies,
                  cmpLoaded: false,
                  cmpStatus: 'stub'
               };

               if (typeof args[2] === 'function') {
                  args[2](retr);
               }
            } else {
               queue.push(args);
            }
         }

         function postMessageEventHandler(event) {
            var msgIsString = typeof event.data === 'string';
            var json = {};

            try {
               if (msgIsString) {
                  json = JSON.parse(event.data);
               } else {
                  json = event.data;
               }
            } catch (ignore) {}

            var payload = json.__tcfapiCall;

            if (payload) {
               window.__tcfapi(
                  payload.command,
                  payload.version,
                  function(retValue, success) {
                     var returnMsg = {
                        __tcfapiReturn: {
                           returnValue: retValue,
                           success: success,
                           callId: payload.callId
                        }
                     };
                     if (msgIsString) {
                        returnMsg = JSON.stringify(returnMsg);
                     }
                     event.source.postMessage(returnMsg, '*');
                  },
                  payload.parameter
               );
            }
         }

         while (win) {
            try {
               if (win.frames[TCF_LOCATOR_NAME]) {
                  cmpFrame = win;
                  break;
               }
            } catch (ignore) {}

            if (win === window.top) {
               break;
            }
            win = win.parent;
         }
         if (!cmpFrame) {
            addFrame();
            win.__tcfapi = tcfAPIHandler;
            win.addEventListener('message', postMessageEventHandler, false);
         }
      };

      makeStub();

      var uspStubFunction = function() {
         var arg = arguments;
         if (typeof window.__uspapi !== uspStubFunction) {
            setTimeout(function() {
               if (typeof window.__uspapi !== 'undefined') {
                  window.__uspapi.apply(window.__uspapi, arg);
               }
            }, 500);
         }
      };

      var checkIfUspIsReady = function() {
         uspTries++;
         if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
            console.warn('USP is not accessible');
         } else {
            clearInterval(uspInterval);
         }
      };

      if (typeof window.__uspapi === 'undefined') {
         window.__uspapi = uspStubFunction;
         var uspInterval = setInterval(checkIfUspIsReady, 6000);
      }

   }

`

[...]

`

function init_theme(){

      init_quantcast();

      // Other inits below are omitted...

}

// First-time init
init_theme();

`

[...]

**Comment by daun** [comment]
I suspect the `SwupHeadPlugin` might be at odds with `init_quantcast()` inserting a custom script tag. The head plugin will remove that script again since it isn't present in the original HTML response from the server.

Two suggestions:

1. Try the current setup without `SwupHeadPlugin`
2. Try to run `init_quantcast()` only once, and not after every `swup:contentReplaced` event

**Comment by vincenzocasu** [comment]
Oh great!!!! This fix the issues... Thank you!!!
