### ISSUE TITLE
Swup not working

### ISSUE THREAD

**Issue by talaing** [swup/swup#302]
I don't know what I did incorrectly in this website...

Here's how I import swup:

```
<script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>
<script src="assets/js/run.js"></script>
<link rel="stylesheet" href="assets/css/transition.css">
```

and this is my main tag:
`<main id="swup" class="transition-fade">`

this is my transition.css file:
```
.transition-fade {
  opacity: 1;
  transition: 850ms;
}

html.is-animating .transition-fade {
  opacity: 0;
}
```

and this is my run.js file:
`const swup = new Swup();`

I see that error in console
`swup.min.js:1 Uncaught TypeError: Cannot set property 'responseURL' of null`

I have no idea how to fix it
Can anyone help me?

**Comment by elisabetperez** [comment]
try adding a `containers: ["#swup"]`, right after you init Swup

**Comment by gmrchk** [comment]
Closing as part of the cleanup of old issues. 

This error means that swup is unable to parse the page (the original one as it tries to cache it) or the next one it tries to transition to. It fails when a structure is invalid, for example, it can't find any container. 

I think you're initializing swup before the `#swup` element exists (eg. your swup init is in the `head` tag). Move it to the end of the file.
