### ISSUE TITLE
Body Class plugin

### ISSUE THREAD

**Issue by syntrix** [swup/swup#303]
Hello, firstly great job with Swup. I have been testing BarbaJS, HighwayJS and Swup. I love your documentation and repositories showing examples. It makes it so much easier to learn when I can see a working example. It's great that I'm able to use both  CSS and JS for animations.

I am having trouble with the CSS body plugin. It's supposed to add the page name as a class to the body when moving from page to page? For the life of me, I cannot get this to work. Do you have a working example I can view or suggestions on how to implement this as I have gone through the step by step instructions?

Thanks
Steve

**Comment by AugustMiller** [comment]
The `SwupBodyClassPlugin` just makes sure that classes on the incoming `body` element are added (or removed) from the persistent `body` element.

So, if your homepage had something like this:

```html
<html>
  <head>…</head>
  <body class="document document--home">
    <div id="swup">
      <!-- Home Page Content -->
    </div>
  </body>
</html>
```

…and the next page you visit looks like this:

```html
<html>
  <head>…</head>
  <body class="document document--about">
    <div id="swup">
      <!-- About Page Content -->
    </div>
  </body>
</html>
```

…Swup will make sure the classes on `body` are synchronized (`document document--about`), even though they live _outside_ your Swup container(s). It won't automatically apply anything except what comes over the network.

**Comment by syntrix** [comment]
Hey @AugustMiller I appreciate your help. Sorry, it took me a while to get back to you, I must have missed it. I have done exactly as you said but it does not update the body class. Do you have a very basic working example? I can show you my Swup boilerplate if you like doing as you suggested. Thanks again!

**Comment by gmrchk** [comment]
Closing as part of a cleanup, as the answer provided is perfect. 👌 

However, if you're still having a problem with this, please provide a link with a demo. 
A working example of the plugin can be seen on [swup docs](https://swup.js.org/), where the initial page has a body class, while no other does, and that is being updated by the Body Class plugin. Docs source is [here](https://github.com/swup/docs) FYI.
