### ISSUE TITLE
Custom transition for clickable link

### ISSUE THREAD

**Issue by syntrix** [swup/swup#304]
Sorry, I'm learning js and cannot seem to apply a custom js/GSAP transition for a specific link. I wondered if you are able to help? I currently have out/in transitions working using GSAP for all page transitions. Is there an example you/anyone could provide for a specific link?

**Comment by daun** [comment]
Are you using the JS animation plugin? You can either directly map routes to transitions or use the `data-swup-transition` attribute on the link to specify a custom transition name you can check for in the animation function. See the [docs on choosing transitions](https://github.com/swup/js-plugin#choosing-the-animation).

**Comment by syntrix** [comment]
> Are you using the JS animation plugin? You can either directly map routes to transitions or use the `data-swup-transition` attribute on the link to specify a custom transition name you can check for in the animation function. See the [docs on choosing transitions](https://github.com/swup/js-plugin#choosing-the-animation).

Yes GSAP js animation. How do i reference an animation to the name of the link? Where do i put it? Do you have an example i could view? The docs are not easy for me in this case. Thanks, greatly appreciated.

**Comment by daun** [comment]
I don't have any code ready to share, but there's [example code in the readme of the SwupJsPlugin](https://github.com/swup/js-plugin#animation-function) which you should be using for any GSAP stuff.

**Comment by syntrix** [comment]
Ive been through your documentation thoroughly but not sure how to set it up. How do  i assign a name to the gsap animation which i can apply as an attribute to a clickable link.

Can i give you some code to provide a basic  example? Add it to your repo Perhaps. Others might like know how to do this if  they’re just getting started.  

Thanks
Steve

**Comment by daun** [comment]
It's easier to help if you share what you already have. What have you tried so far? Did you get the [example GSAP code](https://github.com/swup/js-plugin#animation-function) from the docs to run?

**Comment by syntrix** [comment]
Yeah everything is working great except for not being able to create a custom transition when clicking on a specific link using an attribute. I will send a link to what i have in the next 24 hours. I appreciate your help.

**Comment by syntrix** [comment]
okay here is a link to show you what I have thus far. Please read the README.MD file for further explanation.

https://drive.google.com/file/d/1Y7gyXYRPXlroXPASGx2rWwyNdsRgQiOn/view?usp=sharing

**Comment by daun** [comment]
You can get the name of the custom transition from the second parameter to the in/out functions. Your transition definition would have to check for that and then determine what to do. Note the `context` parameter.

```js
{
  from: "(.*)",
  to: "(.*)",
  in: (next, context) => {
    const custom = context.transition.custom // custom transition name, or undefined

    if (custom === 'my-custom-transition') {
      // Run custom transition
    } else {
      // Run default transition
    }
  },
  out: (next, context) => {
    // Same as above
  },
}
```

**Comment by daun** [comment]
As to the body classes: your html files don't have any classes on the body tag, so there's nothing to apply. The plugin will take the body classes of the new page and replace the current ones. In your case, both are empty.

**Comment by syntrix** [comment]
Thanks for your suggestion however, I just tried giving each page it's own name in the body i.e <body class="page-home">, <body class="page-about">, etc. It still didn't change the class when navigating to the new page, unfortunately.

**Comment by syntrix** [comment]
> You can get the name of the custom transition from the second parameter to the in/out functions. Your transition definition would have to check for that and then determine what to do. Note the `context` parameter.
> 
> ```js
> {
>   from: "(.*)",
>   to: "(.*)",
>   in: (next, context) => {
>     const custom = context.transition.custom // custom transition name, or undefined
> 
>     if (custom === 'my-custom-transition') {
>       // Run custom transition
>     } else {
>       // Run default transition
>     }
>   },
>   out: (next, context) => {
>     // Same as above
>   },
> }
> ```

So where does this go in the code? I thought you might have added it to my sample code to show me a working example?

Thanks anyway

**Comment by daun** [comment]
> I finally got this working... yay!!!

Good to know!

> When I view a new page using the Chrome inspect, the body class doesn't change, but when I view the page source it has the new page class applied. Is this the expected behaviour?

As far as I could tell from those files, they didn't have a body class applied. It needs to be present in the raw HTML for swup to recognize the new body class.

**Comment by syntrix** [comment]
You’re right they didn't have a body class in each of those pages I sent you. Based on your advice i added a body class on each page. This did not work either. Any working example or suggestions?

**Comment by daun** [comment]
If you added the `SwupBodyClassPlugin` as suggested in the docs, you should be good. No further config necessary. Feel free to open another issue in the plugin's repo so somebody might chime in who's more familiar with it.

**Comment by syntrix** [comment]
Yeah did all that. No joy.

Thanks for your help
