### ISSUE TITLE
prevents the load sea script from infinite-scroll

### ISSUE THREAD

**Issue by thefubon** [swup/swup#305]
**prevents the load sea script from infinite-scroll**:
prevents the load sea script from  infinite-scroll, after going to the blog it does not load. only after page refresh.

https://fubon.uk  
blog links > reloadpage

**Comment by gmrchk** [comment]
Hey, the link doesn't seem to work anymore. However, the problem you're describing is a topic discussed many times in the issues. The solution to it is described [here](https://swup.js.org/getting-started/reloading-javascript).
