### ISSUE TITLE
Transition works only after the first pageload

### ISSUE THREAD

**Issue by artware-vagos** [swup/swup#306]
If you visit this site for the first time, the transition between pages (by clicking the image) is very very clunky, it's not even look like transition.

But afterwards, if you go back to homepage and click the image again, the transition is smooth. Probably because the browser has loaded all the contents of the second page.

Am I doing something wrong, or this is a normal behavior?
If you want to look the problem many times, try viewing the page in Incognito Mode.

This is the page: https://artware.gr/swup/

**Comment by daun** [comment]
You're right. That's because the browser needs to load the image first. The only way around this would be for you to manually pre-load the contents of the next page **before** navigating there. swup doesn't know that contents you need on the next page. I'd probably look into service workers or preloader scripts to do what you want.

**Comment by artware-vagos** [comment]
But the image in page 1 is the same as in page 2. So there is no need to re-reload it.

**Comment by daun** [comment]
The HTML itself takes a while to load, which is the delay you're noticing. The second and third times, it's already in swup's cache, that's why it's transitioning immediately.

**Comment by daun** [comment]
Notice that swup will replace the content of your main element completely once the new page is loaded. If you start any transitions on the elements inside before the new page is loaded (which it appears you're doing), they will stop and/or restart those transitions and become janky.

**Comment by artware-vagos** [comment]
Oh ok so if it's the HTML code, how could I preload that? I already preload every js and every css file in header. Plus, if you see the page it's totally empty. This is just a demo site. If we are able to see such glitch here, what will happen in a normal site where it has lots of HTML elements?

**Comment by artware-vagos** [comment]
> Notice that swup will replace the content of your main element completely once the new page is loaded. If you start any transitions on the elements inside before the new page is loaded (which it appears you're doing), they will stop and/or restart those transitions and become janky.

```
swup.on('transitionEnd', function(){
	about();
});
```

I run the animation here. When the `transitionEnd` event kicks in, I am running the gsap animation. This is placed in the footer.

**Comment by artware-vagos** [comment]
I added a `jQuery(document).ready(function()` before running the `swup.on` because u mentioned that any transition before the page loading from swup is making the transitions restart, resulting in clunky animations. It is a little better as I see it, but I wanna check from non-cached browsers. Can you please give me your input too? How do you see the animation now from an incognito mode browser? Is it still clunky or smooth? Thanks!!

**Comment by daun** [comment]
If you're not using swup for CSS transitions, I'd suggest using the [JSPlugin](https://github.com/swup/js-plugin) which is a lot clearer in how the lifecycle works in combination with external animation libraries like GSAP.

**Comment by artware-vagos** [comment]
Oh, nice suggestion. I wasnt aware that SWUP has a specific plugin for JS animations. I will try it, thanks!

**Comment by daun** [comment]
As it stands, the transition is still clunky in the above link — I think the jquery `.ready()` call won't have an effect here since it will run only once on page load.

**Comment by artware-vagos** [comment]
> As it stands, the transition is still clunky in the above link — I think the jquery `.ready()` call won't have an effect here since it will run only once on page load.

But isn't that what we want? For the animation to run only once page loads?

**Comment by daun** [comment]
Yeah, sorry, I was a bit vague on the terminology here 👽 The `$.ready` function will run once the browser loaded the page HTML. It will not re-run when swup has fetched a new page since jquery doesn't know what swup is. That's why swup has its own event cycle with `replaced`, `transitionEnd`, etc.

**Comment by gmrchk** [comment]
A little late to the party, but still gonna leave a note. From what I see, there is no problem with swup, but the animation itself could use some optimization. 

Mainly, you're replacing the element (or let swup do that) at the same time you start doing the animation on the same element. + it's a pretty huge image. This combination can't be smooth. 
Such an image takes a bit of time to render in the first place, and while the browser is trying to take care of that, you're already doing animation on it (and it's also the animation of width, etc., which are heavier on the browser).

I've tried to do a similar effect in the past, and that kinda worked was:
1. on click, copy the image into a standalone fixed container
2. wait for it to be ready 
3. replace the content to a new page, but hide the actual same image in the new position so it's not visible
4. animate the image in the standalone container to a correct calculated place 
5. display the actual image on the new page and remove the container image, which the user won't notice as they are in the same place

Just my two cents...
