### ISSUE TITLE
Google analytics example

### ISSUE THREAD

**Issue by syntrix** [swup/swup#307]
I would like to see an example using the code in the text file to implement google analytics using the swupJS GA plugin. 

Please view text file

[google-analytics-embedded.txt](https://github.com/swup/swup/files/5315903/google-analytics-embedded.txt)

**Comment by AugustMiller** [comment]
The [Google Analytics plugin](https://github.com/swup/ga-plugin) is installed like this:

```js
import Swup from 'swup';
import SwupGaPlugin from '@swup/ga-plugin';

const swup = new Swup({
    containers: ['#my-container'],
    plugins: [
        new SwupGaPlugin
    ]
});
```

Swup takes care of the rest, so long as `window.ga` is available. Your snippet basically looks like the source of this plugin—but you shouldn't need to copy it into your repo.

In theory, the original snippet that Google provided you with takes care of registering the tracking code:

```js
ga('create', 'UA-XXXXX-Y', 'auto');
```

Subsequent calls to `window.ga('send', 'pageview');` use the preexisting config to tag the page view events.

**Comment by gmrchk** [comment]
As pointed out, the usage of the plugin is already present for each plugin. 

However, I've hit a problem recently where the GA plugin stopped working for me. I'm guessing Google is changing how those APIs work. Anyhow, doing some tweaks to how I load GA and switching to [Gtag plugin](https://github.com/joshuaHallee/swup-gtag-plugin) instead helped. I also added a mention about this to [docs](https://swup.js.org/plugins/google-analytics-plugin) and [plugin repo](https://github.com/swup/ga-plugin).
