### ISSUE TITLE
Having new and old content on site together

### ISSUE THREAD

**Issue by uncikmarek** [swup/swup#308]
Hi, so my issue is that I've looked everywhere but I still cant find any good answer to my question, I need page animation where when you go to page which is in menu to the right of you actual active page, new content of header must apear from right and old content must slowly go to the left.

I have managed to do this:

`.transition-slide {
    opacity: 1;
    transition: .3s linear;
    transform: translateX(0);
    transform-origin: left;
}

html.is-animating {
    &.to-left .transition-slide {
        transform: translateX(-100vw);
        opacity: 1;
    }
    .transition-slide {
        transform: translateX(100vw);
        opacity: 1;
    }
}

html.is-leaving{
    &.to-left .transition-slide {
        transform: translateX(50vw);
        opacity: 0;
    }
    .transition-slide {
        transform: translateX(-50vw);
        opacity: 0;
    }
}`
it moves content to sides where it is supposed to, but I cant manage to slow down old content so new content can came up before old one disappear,  It seems like its not possible to have simultaneously old and new content, if it is possible then please tell me how

**Comment by daun** [comment]
That's not possible by default. Swup works by animating the content containers out, then updating the content before animating them back in. Old and new content are never in the DOM at the same time.

You could manage to do this manually, hooking into [swup events](https://swup.js.org/events) and keeping a copy of the old content around.

**Comment by uncikmarek** [comment]
@daun something like animationOutStart somehow make copy right after that trigger animationOutDone so In animation can start and then somehow animate old content out and somehow destroy it?

**Comment by daun** [comment]
Along those lines, yeah. I've never tried what you're trying to achieve, but I'd suggest taking a look at some of the core plugins to get an idea of how they manage additional state. The [head plugin](https://github.com/swup/head-plugin) might have some pointers.

**Comment by uncikmarek** [comment]
@daun I cant seem to emit that event, maybe I dont know how it works, shall I emit animationOutDone on element #swup or on something else?

**Comment by daun** [comment]
You'll probably need to **listen** to events, not emit them, if I understood your use case correctly.

**Comment by uncikmarek** [comment]
I tought that if I emit animationOutDone, old content will destroy and new will come in, and as you said right before I will create a copy of old element and slowly animate it out

**Comment by uncikmarek** [comment]
finally I made some step forward so my js looks like this:

swup.on('animationOutStart', function() {
    let slideOut = $(".transition-slide").clone().removeClass("transition-slide").addClass("slide-out");
    $(".transition-slide").remove();
    swup.on('animationInStart', function() {
        slideOut.appendTo("header");
        if (swup.transition.custom && swup.transition.custom == "left") {
            gsap.to(".slide-out", {duration: 1, x: "60vw", opacity: 0})
        } else {
            gsap.to(".slide-out", {duration: 1, x: "-60vw", opacity: 0})
        }
    })
    swup.on('animationInDone', function() {
        $(".slide-out").remove();
    })
});

And its almost perfect, only issue now is that I need to somehow skip or what transition out, because its right now too drastic, when you change site there is like 1 sec nothing to show and then when new comes In then its good
