### ISSUE TITLE
how to get event emitter ?

### ISSUE THREAD

**Issue by charles-tainui** [swup/swup#310]
**Describe your issue**:
Hi there, 
i'd like to know from which link a click is emitted, is it possible, and how please ?

The aim is to get the id of the link that is clicked for exemple.

Regards

**Comment by AugustMiller** [comment]
The event is passed directly through, so you should be able to treat it like any other `click` event:

```js
import Swup from 'swup';

const swup = new Swup({
    containers: ['#my-container']
});

swup.on('clickLink', (e) => {
    const $element = e.target;

    // Look in your console for all the other available properties:
    console.log(e);
});
```

**Comment by charles-tainui** [comment]
i was trying to do so, but i was certainly doing something wrong because now it is ok... thanks for your time
