### ISSUE TITLE
Swup and Oxygen (wp) - Loading mobile site?

### ISSUE THREAD

**Issue by johanalmsandstrom** [swup/swup#314]
I'm trying to implement Swup into a site in Oxygen for Wordpress.  For some reason, the responsive version of the page is loaded when I click the links. Here is the link to the page: https://testswup.kastanjeskolan.nu/ If you go to Our Services, you get the responsive version. But if you update/reload, you get the correct desktop version. I'll attach a video to show what I mean. 
![2020-10-08 15 06 12](https://user-images.githubusercontent.com/64969630/95500429-17e4ef80-09a7-11eb-9150-c21cafe00562.gif)

Does anyone have any idea why this is happening?

Thanks for any help.

**Comment by AugustMiller** [comment]
It looks like your theme or page builder is injecting extra stylesheets into the page that are probably pre-generated and designed to match hyper-specific `id` attributes.

I recommend adding the [`head` plugin](https://github.com/swup/head-plugin) to see if it can dynamically update the `link` elements required for each page.

**Comment by gmrchk** [comment]
If the Oxygen editor (or other WP plugin on top of that) has some kind of option for putting all styles into one file that would be included on all pages, it would be the best option. 

If not, I'm afraid the suggested swup head plugin is the best option, tho it might still not be ideal. Please, let us know if the plugin works reliably for Oxygen sites.
