### ISSUE TITLE
Fixed Navbar is no longer fixed when using swup

### ISSUE THREAD

**Issue by joepvdm013** [swup/swup#317]
So I am making a portfolio for myself and I wanted to use swup cause it looks really cool. But when I implemented swup I noticed that my navbar is no longer in a fixed position. I am using materialize as well. 

I noticed that when I disabled swup my navbar was fixed again. I removed the swup id and class and the js files. Below is a fiddle of my code.
https://jsfiddle.net/joepvdm013/8wfpbvh6/

Is there a way to fix this issue?

**Comment by daun** [comment]
You're nesting a fixed nav inside a container with a transform applied. That creates a new coordinate system which will position the nav relative to that container. That's correct behavior and to be expected. See [transform3d not working with position: fixed children](https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children/15256339#15256339).

I'd suggest animating the nav and the content itself separately as two swup containers at the same hierarchy. You're applying the `transform` and the `position: fixed` to the same element then which solves your issue.

**Comment by joepvdm013** [comment]
Alright so correct me if I am wrong. But you're saying something like this? 

```
<nav id="swup" class="transition-fade"> 
nav content
</nav>

<main id="swup" class="transition-fade">
main content
</main> 
```

If not can you give me an example? I am still learning javascript and it seems a bit complicated to me.

**Comment by daun** [comment]
Yes, but you can have any ID only once:

```html
<nav id="nav" class="transition-fade"> 
nav content
</nav>

<main id="main" class="transition-fade">
main content
</main> 
```

And then tell swup to look for those IDs instead:

```js
const swup = new Swup({ containers: ['#nav', '#main'] });
```

**Comment by joepvdm013** [comment]
Thank you so much! I finally got it working. If you would be so kind to help me with a little follow up question. When I transition to another page using my sidenav(for mobile devices for example) the sidenav stays open when i am on the next page. It used to close straight after the transition. Any ideas?

**Comment by daun** [comment]
You can use an event to close the menu:

```js
swup.on('contentReplaced', () => {
  // Manually close the menu
})
```

**Comment by suhaylmv** [comment]
Hey @daun, the content in my main page is structured this way:
```html
<body>
<Navbar id="nav" />
<main id="main">
some content
</main>
</body>
```
and this is inside the script tag:
```javascript
      import Swup from "swup";
      // @ts-ignore
      import SwupSlideTheme from "@swup/slide-theme";
      const swup = new Swup({
        plugins: [new SwupSlideTheme()],
        containers: ["#nav", "#main"],
      });
```
But the transitions disappear when I do this. What am I doing wrong?

**Comment by hirasso** [comment]
You have to call your main container `#swup` when using s theme.
