### ISSUE TITLE
Quick question about anchors

### ISSUE THREAD

**Issue by joepvdm013** [swup/swup#318]
So I was always told to put my pages into a separate folder. And link my anchors to that folder. And when i want to go from page A to page B it would look something like this:  

```<a href="../pages/pageb">Page B</a> ```

But I heard somewhere swup needs the anchors to start with a "/".
So i thought fine by me and uploaded my site onto a server. And none of my pages were found. And when I added the "../" the swup animation stopped working.

Any tips? So far SWUP has only caused problems for me

**Comment by daun** [comment]
The issue is with relative URLs. Replace them with absolute ones and you're good.

Say you're at `example.com/sub/` and want to link to `example.com/pages/pageb`. Instead of `../pages/pageb` you'll use `/pages/pageb`. That way, swup won't get confused trying to parse the relative `...`.

**Comment by daun** [comment]
> So far SWUP has only caused problems for me

Seems like you should be focussing on the basics. Libraries like swup introduce their own way of doing things, which might be counter-intuitive if you're not used to doing them that way.

**Comment by joepvdm013** [comment]
I see where I went wrong. Seeing as my website is in its own directory on the server it couldn't find any of the files. So I included the folder name in the path and now its working. I hope that it is the right solution ;)

**Comment by gmrchk** [comment]
Similar problem to [this issue with additional suggestion](https://github.com/swup/swup/issues/319#issuecomment-733948007) as well, for future reference...
