### ISSUE TITLE
animationSelector "swup-" namespace conflict

### ISSUE THREAD

**Issue by davidwebca** [swup/swup#320]
**Describe your issue**:
I ran into an issue where transitionEnd was never detected because of a conflict with a custom animationSelector specified. I wanted to namespace transitions used for swup specifically with "swup-" but it never goes past "pageLoaded". It might be because of a super evident reason, but nevertheless I think it should be fixed and thought about submitting this issue in case someone else runs into this. 👀

**Swup config or any additional relevant code used**:

**I made these two pages that load the CDNs current version to show the bug replicated**

```
<!DOCTYPE html>
<html lang="fr-ca" class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <title>asdf</title>
    
    <style>
        .swup-fade {
            transition: 0.4s;
            opacity: 1;
        }

        html.is-animating .swup-fade {
            opacity: 0;
        }
    </style>    
</head>

<body>
    <a href="/page.html">Test</a>
    <div class="swup-fade" id="swup">
        <h1>PAGE 1</h1>
    </div>
    <script src="https://unpkg.com/swup@2.0.11/dist/swup.min.js"></script>  
    <script>
        const swup = new Swup({
            cache: false,
            animationSelector: '[class*="swup-"]'
        });
    </script>
</body>

</html>
```
```
<!DOCTYPE html>
<html lang="fr-ca" class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <title>asdf2</title>
</head>

<body>
    <div class="swup-fade" id="swup">
        <h1>PAGE 2</h1>
    </div>
</body>

</html>
```

**Before creating this issue, did you think of...**:
- [✅] Have you checked closed issues for similar/related problems.
- [✅] Have you provided all helpful information available? 
- [✅] Have you considered creating a demo so we can help you better?

**Comment by gmrchk** [comment]
Hi, class `swup-...` is also used internally by swup (for example `swup-enabled`), so setting the option to [class*='swup-'] won’t work. Use `[class*='swup-transition-']` or other instead.

I have added a [note about this to the docs](https://swup.js.org/options#animation-selector) as well. Thanks for reporting! 👏
