### ISSUE TITLE
CSS Styles for animationOut and animationIn

### ISSUE THREAD

**Issue by possible-is** [swup/swup#322]
I can't find it anywhere, but is there a way to define the animation for In and Out separately?
I would like to have a page slide out to the left and the next page coming in from the right...

**Comment by gmrchk** [comment]
Hi, you can use the `is-leaving` and `is-rendering` classes for that. They are described over [here](https://swup.js.org/getting-started/how-it-works). In fact, that's exactly what the swup docs do as well for its to-bottom/from-top animation.

**Comment by possible-is** [comment]
Many thanks, @gmrchk .
With this, i was able to aim at in and out animations...
