### ISSUE TITLE
Section navigation no longer works when using swup?

### ISSUE THREAD

**Issue by joepvdm013** [swup/swup#323]
**Describe your issue**:
I have been working on a pretty long webpage. And because it contains so much content I want to add navigation into it. So I implemented a navigation sidebar. But the navigation doesn't work? I used sections and within those sections I got some paragraphs and images. But when I click on a link to the section nothing happens. It just adds the section name to the website url.

I think this is a stupid question and might be something really obvious but I cant figure it out.

**Comment by talaing** [comment]
It doesnt work for me too :( Anyone got a solution for that?

**Comment by gmrchk** [comment]
Hi, swup takes over all clicks on links that satisfy the [link selector option](https://swup.js.org/options#link-selector), and runs `event.preventDefault()` on those, so this is expected. 

You have to options:
* Add [scroll plugin](https://swup.js.org/plugins/scroll-plugin). That will add the functionality you are looking for automatically with some nice spring animations.
* Use [swup events](https://swup.js.org/events) to implement the logic yourself.
