### ISSUE TITLE
Components unmount animation/async

### ISSUE THREAD

**Issue by hartwm** [swup/swup#324]
**Components unmount functionality**:
I have built my website using components via Gia framework as suggested. I am using this to init various functions related to that component, including animation. On page load/transition (mount) they animate in. I use g-ref to select proper elements, so I don't have to keep track of css naming schemes. However, if I want them to animate out I have to do that globally? That kind of defeats the purpose of components.  Is there a way to async unmount and run an animation? Anyone else solve this issue or use components in a similar fashion? 

Using GSAP for animation

**Comment by gmrchk** [comment]
Hi @hartwm, [JS plugin](https://swup.js.org/plugins/js-plugin) could help with that, where you could wait for the animations for each component to run first. Something like the following is what I have in mind, but it's just an untested example.

```javascript
import getComponentFromElement from 'gia/getComponentFromElement';

const jsPluginOptions = [
  {
    from: '(.*)',
    to: '(.*)', 
    out: (next) => {
        const allElementsWithComponentAttached = document.querySelectorAll('[g-component]');
        
        const animateOutPromises  = allElementsWithComponentAttached.map((element) => {
            const component = getComponentFromElement(element);
            return component.animateOut(); // this would be async method
        });
 
        Promise.all(animateOutPromises).then(next);
    },
    in: (next) => next()
  }
];

const swup = new Swup({
  plugins: [new SwupJsPlugin(jsPluginOptions)]
})
```

You could also just go with some fixed timing. This way you would avoid unexpected bugs, where a mistake in some small component could stop the whole page from navigating. The animations of the components are likely pretty much the same timing anyway, but you probably have some specific use case that I don't.
