### ISSUE TITLE
Load new page from the position of the previous page

### ISSUE THREAD

**Issue by nicooh** [swup/swup#325]
Thank you for this beautiful plugin but I wanted to ask if it is when I scroll the page and click on the link, on the page displayed I find myself in the same position compared to the previous page. Isn’t it possible to get to the top of the page?

**To Reproduce**
1. View a page 
2. Scroll the content and get to the center of the content
3. Click the link in the navbar
4. You will see the new page starting from the same offset with respect to the top.

way it really is
![image](https://user-images.githubusercontent.com/40459534/99989667-2ea6a080-2db3-11eb-94fc-37f5d7cd9056.png)

as I would like
![image](https://user-images.githubusercontent.com/40459534/99990054-a83e8e80-2db3-11eb-8f40-1ed0663a75a0.png)

 - OS: Windows
 - Browser : Chrome

**Comment by gmrchk** [comment]
Hi @nicooh, [scroll plugin](https://swup.js.org/plugins/scroll-plugin) is what you're looking for.
