### ISSUE TITLE
Window property undefined in contentReplaced event

### ISSUE THREAD

**Issue by bjarnef** [swup/swup#327]
**Describe your issue**:
I have a page with a map using Google Maps, where it on this page set a property on window object like this:

```
<script>
    window.mapData = {
        apiKey: '@ConfigSettings.GoogleMaps.ApiKey',
        markers: @Html.Raw(json)
    };
</script>
```

These details are passed into a `map.init()` function, which work fine most of the time, but not always after `contentReplaced` where the `mapData` property is undefined, but not the `window` object itself.

**Swup config or any additional relevant code used**:

```javascript
'use strict';

var myProject = myProject || {};

const swupOptions = {
        animationSelector: '[class*="transition-fade"]',
        animateHistoryBrowsing: true,
        containers: ["#swup", "#main-menu"],
        plugins: [
            new SwupBodyClassPlugin(),
            new SwupGtmPlugin(),
            new SwupScrollPlugin({
                animateScroll: false
            }),
        ]
};

const swup = new Swup(swupOptions);

swup.on('contentReplaced', initSwup);

function initSwup() {

    if (document.querySelector('#map')) {
        window.scrollTo(window.scrollX, window.scrollY + 1);

        initMap();
    }
}

function initMap() {

    var md = window["mapData"]; // sometimes return undefined
    if (md) {
        myProject.map.init({
            selector: '#map',
            apiKey: md.apiKey,
            markers: md.markers
        });
    }
}
```

It seems to happen when doing a regular page load of e.g. home page and navigating to a stores page (which the map and script block).

**Comment by bjarnef** [comment]
If I set an id on the `<script>` in `initMap` and output this I get the following:

var mapScriptElem = document.getElementById("mapData");
console.log("mapScriptElem", mapScriptElem.innerText); // json data
var md = window["mapData"];
console.log("md", md); // undefined

**Comment by bjarnef** [comment]
Not pretty, but it seems this workaround did it:

```
function initMap() {

    var mapScriptElem = document.getElementById("mapScriptElem");
    var text = mapScriptElem.innerText;
    var data = text.substring(text.indexOf("{"), text.lastIndexOf("}") + 1).trim();

    var obj = JSON.parse(data);

    window["mapData"] = window["mapData"] || obj;

    var md = window["mapData"];
    if (md) {
        myProject.map.init({
            selector: '#map',
            apiKey: md.apiKey,
            markers: md.markers
        });
    }
}
```

although I am getting another error regarding `MarkerClusterer` which are included on the page itself:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js"></script>
```

**Comment by bjarnef** [comment]
I solved the MarkerClusterer error by removing the script from the page and loaded it asynchronous as part of my `load()` function.

```
 function load() {

    // Async load the GMaps API and run "initialize"
    var script = document.createElement('script');
    script.id = "mapScript";
    script.type = 'text/javascript';
    script.src = `https://maps.googleapis.com/maps/api/js?callback=myProject.map.initMap&key=${options.apiKey}&libraries=geometry,places`;

    var mapScript = document.getElementById("mapScript");
    if (mapScript) {
        mapScript.remove();
    }

    var mcScript = document.createElement('script');
    mcScript.id = "mcScript";
    mcScript.type = 'text/javascript';
    mcScript.src = "https://cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js";

    window.google = {};

    document.body.appendChild(script);
    document.body.appendChild(mcScript);
}
```

**Comment by gmrchk** [comment]
Little late to the party, since you seem to get to the bottom of it on your own, but still want to leave a short comment. Swup does not run and `<script>` tags when it's replacing content on a page. You will see it in HTML, but the code itself won't be executed. The is a [script plugin](https://swup.js.org/plugins/scripts-plugin) that can help with that, but your programmatic solution is better. 👍 

Here's some general info on the topic https://swup.js.org/getting-started/reloading-javascript.
