### ISSUE TITLE
Detecting backward or forward with popState

### ISSUE THREAD

**Issue by psntr** [swup/swup#328]
Hello, thanks for this amazing tool.

I'm using Swup to handle page transition, but for one page, I'm using `fetch` to retrieve some article and then show them inside a lightbox. I'm doing that manually and updating the URL with `history.pushState`. So far so good. But the problem happens when I trigger the back button and then the forward button. 

I try to implement some state inside the `history.pushState`, but when I hit the back button, `Swup` seems to take over hence, I'm loosing my custom state and can't verify whether the user is triggering back or forward button.

Is there a way to check that without interfering with swup?

(also, if someone has experience with SPA and lightbox, would love to hear how you handling this)

**Comment by gmrchk** [comment]
This [option](https://swup.js.org/options#skip-popstate-handling) might be helpful. Basically, by default swup only reacts to popstates to historical records it has created, but the option can be changed to completely custom logic and prevent swup from doing anything on back/forward.

**Comment by pixelprogrammer** [comment]
@psntr I am late to the party but SWUP has an internal helper that you can use to record history state that SWUP understands.

https://github.com/swup/swup/blob/master/src/helpers/createHistoryRecord.js

Simple Example:
```javascript
import { createHistoryRecord } from 'swup/lib/helpers';

// a button that modifies content on the page but doesn't trigger a page transition
const button = document.querySelector('#my-button');
button.addEventListener('click', handleButtonClick);

function handleButtonClick(e) {
  e.preventDefault();

  // api request for data and update data on page
  // ....

  // update the url so we can visit this page later
  // we can just use a relative url as an example
  const url = '?arg=value';
  createHistoryRecord(url); // swup understands this url in its history now
}
```

The back button should now work with SWUP.

**Comment by dev-ofty** [comment]
@pixelprogrammer Thank you for the detailed answer I wasn't aware of the `createHistoryRecord` method. I will try this next time I'm facing this issue.
