### ISSUE TITLE
When replacing head, first load is stuck.

### ISSUE THREAD

**Issue by ItayAssouline** [swup/swup#330]
i have different stylesheets on multiple pages.
when i use the head plugin, the first load of pages(even if cached) feels like normal ugly page moving, and not like awesome swupping

**Comment by gmrchk** [comment]
Swup replaces the style/link tags, meaning the browser needs to load the next file, parse it, and apply it to the page. That takes some time and will show an ugly page in the process. 
For this to work, any general styles like the layout or swup transition styles need to be in a separate file, included on all pages. We simply can't afford to lose all styles of the page even for a split second. Including the same file on all pages will make head plugin not manipulate this one style/link tag at all. Alternatively, you can place all the styles in one file, but that depends on the project.

**Comment by daun** [comment]
Closing this since it's been inactive for a while.
