### ISSUE TITLE
Sync Option like Barba?

### ISSUE THREAD

**Issue by twd3** [swup/swup#337]
I'm getting white backgrounds in between transitions and I was wondering if there is any option like the "sync" option from Barba? If not can you point me in the right direction? I don't want to see the white background on transition.

https://user-images.githubusercontent.com/16004958/105781202-5d660200-5f2f-11eb-9a17-ff578944751f.mp4

**Comment by daun** [comment]
Kindly explain what the `sync` option does? As far as I remember, barba keeps both the old and the new content around between animations which would make your problem easier to solve there.

**Comment by twd3** [comment]
Yes, that. I was just wondering if there was something similar or some kind of workaround for a JS novice like me.

**Comment by gmrchk** [comment]
Swup doesn't have both page contents (current+future) on the page at the same time, so you would probably be better off with Barba if that is a requirement. 

But there are options... you can use [Body Class plugin](https://swup.js.org/plugins/body-class-plugin) to make the body background the right color, so the white blink is not there, and only the text would appear/fade in. Alternatively, you can surely have both contents at the same time on the page by pulling it out of swup cache (and probably using the [JS plugin](https://swup.js.org/plugins/js-plugin) for better control), but that's some advanced stuff that I would not recommend a novice without some deeper guidance.

**Comment by daun** [comment]
**Update**: the recently released [swup 4](https://swup.js.org/announcements/swup-4/) supports [parallel animations](https://swup.js.org/plugins/parallel-plugin/).
