### ISSUE TITLE
Keep old page visible while transitioning

### ISSUE THREAD

**Issue by LeoDav22** [swup/swup#338]
Hi, I'd like to make a transition where the old page remains visible while the new page slides on top of it. Is it possible with Swup ?

Thanks

**Comment by daun** [comment]
Not out of the box, no. The best approach would be to listen for the `transitionStart` event, create a copy of the existing content, and keep that around until the `transitionEnd` event fires.

**Comment by daun** [comment]
Commenting here for future visitors: Swup now has an official [Parallel Plugin](https://github.com/swup/parallel-plugin) that allows animating both the outgoing and the incoming containers at the same time. This allows crossfades, slide animations, etc., that weren't possible before.
