### ISSUE TITLE
Visit link with request header

### ISSUE THREAD

**Issue by ionurboz** [swup/swup#339]
### Question
- **Is it possible to visit links with request header / payloads or form data?**
- Is there a dependency on keeping our javascript files like Turbolinks inside the `<head>` tag?
- Does it automatically add files such as `js, css, font` that exist on the new page and are not on the current page?

Note: The project looks very good. I hope I get positive answers for my questions above. I absolutely liked it.

**Comment by gmrchk** [comment]
Hey, you probably know by now, but...
* [loadPage](https://swup.js.org/api/methods), 
* scripts can be anywhere but you probably want to read [this](https://swup.js.org/getting-started/reloading-javascript), 
* [Head plugin](https://swup.js.org/plugins/head-plugin)

For any further questions, please use [Discussion](https://github.com/swup/swup/discussions).
