### ISSUE TITLE
 The transition between 2 pages works, but the same CSS is always used for both pages

### ISSUE THREAD

**Issue by AntonioMennuni** [swup/swup#340]
Hi I was experimenting with the main swup.js animation directly taken from the official site. But there's a problem. The effect works, but the same css file is always loaded for 2 or more different pages even if on the second page I indicate a different css file.

I leave you the snippet to make you understand. If you know how to avoid this behavior please let me know. I wish the same css file didn't always load.

I left you the link of the code on pastebin:
https://pastebin.com/12rLD5N2

You will see that the page translation works, but the page1.css file is always applied as css. I would like each page to have its own css.

**Comment by daun** [comment]
You can use the [head plugin](https://github.com/swup/head-plugin) to update linked stylesheets after page transitions.

**Comment by AntonioMennuni** [comment]
Hei @daun , i have tried and even managed to implement it, but it has a very bad effect. Basically, while you go to the next page you see the next page without a style so ugly and then immediately after you load the CSS file of the page. It has a very bad effect. Do you know how to solve?

**Comment by daun** [comment]
That's to be expected since the new stylesheet loads asynchronously after the page transition. You could inline the css into the head which is simple to do and solves the problem immediately. For a more involved solution you could use swup's JS plugin to wait for newly added stylesheets to finish loading before starting the in-transition of the new page.

**Comment by AntonioMennuni** [comment]
okok, I try. I hope I have no further problems. If you still have problems, do you know if it is possible to contact each other privately here on github?

**Comment by daun** [comment]
The best place to post any further questions is the repo's [Discussions section](https://github.com/swup/swup/discussions).
