### ISSUE TITLE
Combining multiple events and dispatch new one

### ISSUE THREAD

**Issue by onur-km** [swup/swup#346]
## Combining multiple events and dispatch new one

```js
document.addEventListener('init', function(){
  // Init the ecosystem with local events or the event belonging to the swup.
});

function dispatchInit()
{
   const event = new Event('init');
   document.dispatchEvent(event);
}

window.addEventListener('load', dispatchInit);
document.addEventListener('swup:contentReplaced', dispatchInit);
```

In the example above, is there more than one possibility that the 'init' event will fire? I mean, there is an error like both local and swup running consecutively and running the event twice?

In short, would this be code healthy? Thanks

**Comment by gmrchk** [comment]
Swup won't call it the first time, but will on every next (fake) page reload, and your `window.addEventListener` will call it the first time, so I guess it's all good.
Seems like overcomplicating things, but I'm not sure when/how you use the init event further, so maybe I'm just missing a context.
