### ISSUE TITLE
Contact Form 7 + Swup don't work

### ISSUE THREAD

**Issue by Manitta1998** [swup/swup#352]
Hi! I have a website with swup.js and contact form doesn't work.. When i press submit the page reload with this new url : 
            
?_wpcf7=87&_wpcf7_version=5.4&_wpcf7_locale=it_IT&_wpcf7_unit_tag=wpcf7-f87-o1&_wpcf7_container_post=0&_wpcf7_posted_data_hash=&name-mail=asdad&email=dasdsad%40gmail.com&_nl4wp_subscribe_contact-form-7=0&_nl4wp_subscribe_contact-form-7=1

I have also tried to add FormsPlugin and inizialized with FORM_SELECTOR: 'form.wpcf7-form',
But nothing... Is there a solution? Thank you

**Comment by gmrchk** [comment]
Forms plugin serves this exact purpose. If it doesn't work and reloads the page instead, something is wrong, but you need to provide more info for anyone to be able to help. Swup config, console errors, etc.

**Comment by matteightarms** [comment]
In the past I have managed to get contact form 7 to work with Swup with the following:

```
function contactForm() {
  var contactForm = document.querySelector(".wpcf7-form");
  if (contactForm) {
    wpcf7.initForm(contactForm);
  }
}
```

```
swup.on("contentReplaced", function() {
   contactForm();
});

```

**Comment by daun** [comment]
@Manitta1998 Did the solution provided by @matteightarms solve your issue? I'm closing this for now but feel free to chime in with more info on your specific setup if not.
