### ISSUE TITLE
Browser ESM module for loading Swup

### ISSUE THREAD

**Issue by ghost** [swup/swup#361]
**Describe your issue**:
There is no ESM-module form of swup for loading in a browser.

Someone I know, and I, were working on a website and were interested in using this library for our site, while setting it up, we had both independently checked for an ESM module to import, yet there is only a plain script version that is intended to be loaded in via a plain script tag and pollute the global scope.

Can one be provided and distributed?

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.

**Comment by EpicGamer007** [comment]
A temporary solution for this would be something like
```html
<script type="module" src="swup.js"></script>
```
Then `swup.js` has
```js

// swup.js code

const swup = new Swup(); // Below Swup code
// Add all the swup config stuff here
```

This way, there will be no polluting of the global scope and keep all swup code in one file, however, having an ES-module version of swup would be good.

**Comment by metaline** [comment]
I agree with the request. I cannot use Swup for this reason. :(

**Comment by daun** [comment]
The next swup version 3.0 will have an ESM export and won't pollute the global namespace. Closing this in favor of #487 where it's currently tracked.
