### ISSUE TITLE
Pages stuck transitioning, only root / page replaces content

### ISSUE THREAD

**Issue by rushsteve1** [swup/swup#364]
**Describe your issue**:
After adding some dynamic content to the `<head>` of my site Swup stopped loading pages properly. The transition begins, the page fades out, but the content is not replaced and it is stuck in the `is-animating` state. I thought to add the Head Plugin, which *partially* fixed the issue. Now I can navigate *to* the root `/` page from any other page and the content replaces and loads, but I can't navigate *from* it.

I nailed down the issue [to this commit in my repo](https://github.com/rushsteve1/RateTheDub/commit/53f60cea78521bb0a8e14f51b02ae51ff4722ea6), before this commit everything worked. I tried adding the head plugin after this, which is what allowed the root page to load, but other pages still aren't loading properly.

This might be related to https://github.com/swup/head-plugin/issues/13, however my styles aren't changing (only one stylesheet for the whole site) and I'm not left with an unstyled page.
Apologies if I made this issue on the wrong repo, it seemed more general than just the Head Plugin.

Edit:
I just noticed that going from certain pages to certain others also seems to work, but I can't figure out why.

**Swup config or any additional relevant code used**:

```javascript
import Swup from "swup";
import SwupFormsPlugin from "@swup/forms-plugin";
import SwupHeadPlugin from "@swup/head-plugin";
import SwupPreloadPlugin from "@swup/preload-plugin";
import SwupProgressPlugin from "@swup/progress-plugin";

const swup = new Swup({
  plugins: [
    new SwupFormsPlugin(),
    new SwupHeadPlugin({
      persistAssets: true,
      persistTags: "link[rel=stylesheet], link[rel=icon], script[src]",
    }),
    new SwupPreloadPlugin(),
    new SwupProgressPlugin({ delay: 500 }),
  ],
});
```

Commit that broke things: https://github.com/rushsteve1/RateTheDub/commit/53f60cea78521bb0a8e14f51b02ae51ff4722ea6

**Comment by daun** [comment]
The linked commit is a bit hard to make sense of but I would guess you're either hiding the container via css or not loading the 
stylesheet on all pages. The stuck transition means there's no transition to listen for. That's usually because the container element is missing, hidden via css or unstyled.

**Comment by rushsteve1** [comment]
Apologies on the commit being a bit opaque, it's using Elixir templates pretty heavily which are kinda funky to to get used to.

I can verify that the container element is present on each page. It's not that it's just stuck transitioning, it's that the DOM content is never swapped out. Everything is unchanged when I inspect the page in the browser.
The page that it is navigating to loads properly if I skip Swup and navigate to it directly, and there are no errors on the backend either.

**Comment by daun** [comment]
The content isn't replaced precisely because swup thinks the out-transition hasn't taken place. The lifecycle goes like this:  
click → add html class → wait for out-transition → swap content → remove html class → in-transition happens

Somewhere along the line the out-transition is failing to finish properly. Maybe switching back to the previous transition catchall shorthand will help (even though it's less performant): `transition: 0.5s`.

**Comment by daun** [comment]
Maybe check the validity of the generated HTML. Unclosed or wrongly nested closing tags can turn into a problem every once in a while.

**Comment by rushsteve1** [comment]
Oh my god I've got it and it's a weird issue that I never would have considered until you mentioned exactly the things you did.

I'm using TailwindCSS, which has a bunch of [classes for setting transitions](https://tailwindcss.com/docs/transition-property).
Which uuuh... [Swup uses the same naming scheme](https://swup.js.org/other/common-issues) **and waits for the transition to finish** (which it never does).

I only figured this out because you mentioned HTML validation, so I went and checked which exposed a few minor issues. Out of laziness I just commented the line out, *and suddenly everything worked*.
Process of elimination revealed it to be the `transition-shadow` class. Then exactly because you mentioned the lifecycle (which was super helpful BTW, that should be added to the docs if it isn't) I checked for the word "transition" in the Swup docs and found it.
Turns out my solution was in "Common Issues" this whole time and I didn't realize it because my symptoms were different.

**Comment by rushsteve1** [comment]
Having figured this out I'll close this, and put the solution for the next unlucky soul:

Anyone using Tailwind, [change the Swup animation selector](https://swup.js.org/options#animation-selector) to avoid issues.

If someone feels like adding a note about this to the docs that would be greatly appreciated.

**Comment by daun** [comment]
Great. The Common Issues page in the docs does have a section on this issue and a working example to resolve it, but if you feel it can be improved, please open a pull request on the docs repo! We should probably make the Common Issues page more prominent in the navigation to encourage people skimming it before getting too deep in the woods.

**Comment by jesserosenfield** [comment]
@gmrchk this should be changed in the source code. It's far too common a naming scheme to have it break the entire plugin. should make the plugin look for a class of `.swup-transition-container` or equivalent

thanks!
