### ISSUE TITLE
JS Date object gets stuck

### ISSUE THREAD

**Issue by jaszfalvitamas** [swup/swup#365]
Hi there!

Swup is amazing, I love it! But I might have a minor problem, which is not specifically swup's fault. In my application I use datepickers, which as we know, rely on the JS Date object. Now, if a page is opened for a long time, and let's say I put the computer to sleep, then the Date object gers stuck at one particular date. 
Let's say now is 05.12, and if I put my PC to sleep, boot it up the next day, it still thinks it 05.12, instead of 05.13. To reproduce this issue easily, change system time. The issue is fixed with a reload of the page.
It's more like a browser/JS thing, which wouldn't be a thing if pages would fully load each time (without swup). But since I'm using swup (and quite fond of it), does anyone have a working workaround for this?

**Comment by daun** [comment]
Apart from listening to the [visiblitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) event, you can build your own [wake-from-sleep event](https://stackoverflow.com/q/4079115) and re-initialize the date object when either of them occurs.

**Comment by daun** [comment]
Closing this since it seems unrelated to swup. Feel free to comment if you require further help or if you've found a solution in the meantime.
