### ISSUE TITLE
Some page styling from previous page is applied to new transitioned/linked page.

### ISSUE THREAD

**Issue by HunterHolthaus** [swup/swup#369]
Hey I'm a total beginner so sorry, But I love your Plugin and did get it working on a test site, however, when trying it on my site I'm running into trouble since I am using another plugin along with it. I am using a JS library called fullpage.js on my homepage and it basically applies a class to the body element of that page. When I use Swup and transition to a new page I notice that the classes applied to the body on my homepage are being applied to the body of the new page I have transitioned to (even though they're not in my markup for that one) and its messing with the page styling. I added a video of the issue, the new page shouldn't have the dots on the right side and there's some styling issues. 

https://user-images.githubusercontent.com/49177233/122006240-73078700-cd6b-11eb-886e-cb10e7247f18.mov

I'm wondering if you know of any ways around this? Is there a way to clear the previous pages body classes before transitioning to the new page so they aren't applied to it? Is there a certain plugin I should be using to revolve this? 
<img width="865" alt="Screen Shot 2021-06-14 at 11 37 08 PM" src="https://user-images.githubusercontent.com/49177233/122005979-215efc80-cd6b-11eb-8a23-40eb9970515f.png">

**Comment by daun** [comment]
Fullpage should have a teardown method to redo all the changes it made to the body and any container elements. I'd run that right before swup replaces the content. See [Events](https://swup.js.org/events) in the docs for details. `willReplaceContent` is the one you want.

**Comment by HunterHolthaus** [comment]
Hi Philipp! Thanks for the info, I'll give that a shot, really appreciate it!

**Comment by HunterHolthaus** [comment]
Thank you so much for the tip Philipp it worked! I got fullpage successfully destroyed after transitioning to the new page while using the willReplaceContent event in Swup and I no longer see the Fullpage being attached to any elements on the new transitioned page. 

However, it looks like I'm still having some issues with getting the styling on the transitioned page correct. For some reason it looks like the new transitioned page isn't including all of the proper css styles in the markup for the new page. I'm wondering if you know if there is a way to make sure all of the new pages css styles are loaded while ignoring all of the previous pages styles? I'm using both inline styles and linked stylesheets on the new transitioned page, it looks like some of my inline styles are not being included in the transitioned page. 

I added a video toggling between what the styles should look like versus what I'm seeing. The page with the padding above and below the video is the correct layout.


https://user-images.githubusercontent.com/49177233/122167347-b297a700-ce2f-11eb-9d25-de98da56039a.mov


https://user-images.githubusercontent.com/49177233/122167752-3ea9ce80-ce30-11eb-8b7a-4311ac6e3583.mov

**Comment by daun** [comment]
Separate stylesheets per page get messy with a solution like swup. I'd avoid them as much as possible and just load one stylesheet.

If that's not an option, the [head plugin](https://github.com/swup/head-plugin) can update/replace style tags and stylesheets, depending on how you configure it. Be aware that it's an imperfect solution especially for dynamic `link` tags: it won't wait for the stylesheet to load and you might get a flash of unstyled content.

**Comment by HunterHolthaus** [comment]
Philipp! You totally rock and have solved almost all of my Swup issues! I got it working and just put all my page styles into a single document. One thing I am noticing and I'm not sure if this would be directly related to Swup or fullpage.js or if there are any possible solves that would exist but basically after clicking through to a new page from my homepage I've noticed that using the back button to my homepage breaks the page, do you know if there is something I can leverage in swup to solve this?

https://user-images.githubusercontent.com/49177233/124074074-d219fc80-d9f7-11eb-8f89-dca5a1b3570f.mov

**Comment by daun** [comment]
You might need to disable fullpage‘s history option as well. I‘m sure there‘s a way of making them play nice, though — you could start by looking through existing issues related to the browser history api.

**Comment by HunterHolthaus** [comment]
Having some additional plugin-in issues, basically Im trying to use another js library (scroll magic) on a page after a transition but noticing that the js is not working after a swup transition, only when I refresh the page does it work so I know the script works but not after a swup transition. I believe that the issue is related to  [this](https://swup.js.org/getting-started/reloading-javascript), however, I cant seem to get it working properly and am a little confused about what the full js should look and if it should be in my main.js file? Also wondering where exactly I need to place my script? Does anyone k

https://user-images.githubusercontent.com/49177233/131266752-3fad6c5e-f7c6-4b40-8738-564fa75e9829.mov

now of any full example anywhere? Obviously I'm such a noob at this so really appreciate the help/patience since I absolutely love designing with swup!! 

This is the script I want to have run on the new page (I know its messy and may not make much sense :/ ) : 
<script>
        $mainText = $('#mainText');
        
        // init
        var ctrl = new ScrollMagic.Controller({
        globalSceneOptions: {
        triggerHook: 'onEnter'
        }
        });
        
        // Create scene
        $("section").each(function() {
        
        new ScrollMagic.Scene({
        triggerElement: this,
        duration: '100%'
        })

        .addTo(ctrl);
        });
        
        var sectionOne = new TimelineMax();
        sectionOne
        .to($mainText, 0.5, { yPercent: -80, ease: Power4.ease}, '.05');

        new ScrollMagic.Scene({
        duration: '600px'
        })

        .setTween(sectionOne)
        .triggerElement($('#body')[0])
        .addTo(ctrl);                       
</script>

Current code in my main.js file for getting swup to work:

<script>
const swup = new Swup({
  plugins: [new SwupHeadPlugin()]
});

const options = {
    cache: true
  };

  document.addEventListener('swup:willReplaceContent', (event) => {
    fullpage_api.destroy('all');
  });

</script>

**Comment by daun** [comment]
Swup doesn't pick up new inline `script` tags, you'll need to put the code into a function in a JS file, include that file, and call the function once on init and after each `contentReplaced` event, as detailed in the Reloading JS guide you linked to.
