### ISSUE TITLE
Im just started working with SWUP, and am having a couple issues,

### ISSUE THREAD

**Issue by rohansingh20** [swup/swup#372]
Im just started working with SWUP, and am having a couple issues, 

I am having some of my CSS styles not load in, and have to refresh each time for it to work. I also have to refresh to be able to click buttons. This was not happening before I used SWUP.

Also, do I have to use the main tags in swup or can I add the `id="swup" class="transition-fade"` into the body tag?

Thanks

_Originally posted by @rohansingh20 in https://github.com/swup/swup/discussions/371_

**Comment by daun** [comment]
Hi, do you have a public link or a reproducible demo people can take a look at?
