### ISSUE TITLE
swup and other js plugins on wordpress

### ISSUE THREAD

**Issue by Caffeinedesign** [swup/swup#373]
Good morning, i'm trying to use swup with wordpress and oxygen builder, and i was succesful making it work (i installed both head and body plugin), my problems are with other js plugins i'm trying to make work together with swup, they work in the first instance, but they sto working when i change page and go back

Exactly i'm tryng to make it work with midnight.js and fullpage.js

this is the code i've added to wordpress to load plugins

a temporary page i'm working on is here:
https://portfolio.caffeinedesign.rocks/

```
wp_enqueue_script( 'swupJs', plugin_dir_url( __FILE__ ) . 'assets/js/swup.min.js', '', '1.0.2', true );
	wp_enqueue_script( 'swupJs-slide-theme', plugin_dir_url( __FILE__ ) . 'assets/js/SwupSlideTheme.min.js', '', '1.0.2', true );
	/*wp_enqueue_script( 'midnightJS', plugin_dir_url( __FILE__ ) . 'assets/js/particles.min.js', '', '1.0.2', true );*/
	/*wp_enqueue_script( 'fullpageJs', plugin_dir_url( __FILE__ ) . 'assets/js/fullpage.min.js', '', '1.0.2', true );*/
	wp_enqueue_script( 'midnightJS', plugin_dir_url( __FILE__ ) . 'assets/js/midnight.jquery.min.js', '', '1.0.2', true );
	wp_enqueue_script( 'swupHeadJs', plugin_dir_url( __FILE__ ) . 'assets/js/SwupHeadPlugin.min.js', '', '1.0.6', true );
	wp_enqueue_script( 'swupBodyJs', plugin_dir_url( __FILE__ ) . 'assets/js/SwupBodyClassPlugin.min.js', '', '1.0.6', true );
		wp_enqueue_script( 'customJs', plugin_dir_url( __FILE__ ) . 'assets/js/customJs.js', '', '1.0.2', true );
```

this is the custom js code to initialize plugins ( i initialize them sitewide as an assets of a custom plugin)

```
const swup = new Swup({
	 plugins: [
        new SwupSlideTheme(),
		new SwupBodyClassPlugin(),
        new SwupHeadPlugin({
  persistAssets: true
})
    ],
  });

// Start midnight
jQuery(document).ready(function(){
  // Change this to the correct selector.
  jQuery('#section-14-13').midnight();
});
```

some suggestions?

thanks

**Comment by daun** [comment]
Closing this for now. I'm assuming you've found a solution by now. If not, there's an issue about [using swup with Fullpage](https://github.com/swup/swup/issues/402) with a working code snippet.
