### ISSUE TITLE
Documentation: Explain the recommendation to use one transition class earlier.

### ISSUE THREAD

**Issue by kezabelle** [swup/swup#380]
Given the following **common issues**:

> In case the styles are missing and the element does not transition to any other state, swup will still wait for the element to finish the transition. However, the transition will never finish (as it never even starts) and swup gets stuck at willReplaceContent event of the lifecycle.

and 

> People tend to use a class with a format of transition-[something] on any element that is animating, which is not necessary and often leads to bugs. For example, misspelled class name would lead to styles not being defined for that element (see issue above).

It would seem prudent to move this general suggestion:

> It is recommended to use one element with class with a format transition-[something] to set a transition duration for swup and make any other transition happen independently.

to far earlier in the docs, on either the **example** or **how it works** page. Everything prior to the common issues page very much suggests that because the animation selector is an array, it's expected to define many of them, on each transitionable element. Ideally the example page (probably a new section, **multiple transitions**) would show off how to use **one** transition class but multiple individual element transitions, to get the point across.

**Comment by daun** [comment]
This is now part of the [How it works](https://swup.js.org/getting-started/how-it-works) section of the docs. Thanks for the suggestion!
