### ISSUE TITLE
Feature request: logging of found transitions

### ISSUE THREAD

**Issue by kezabelle** [swup/swup#381]
Given the following common issues:

> In case the styles are missing and the element does not transition to any other state, swup will still wait for the element to finish the transition. However, the transition will never finish (as it never even starts) and swup gets stuck at willReplaceContent event of the lifecycle.

and

> People tend to use a class with a format of transition-[something] on any element that is animating, which is not necessary and often leads to bugs. For example, misspelled class name would lead to styles not being defined for that element (see issue above).

it would be helpful if, at least when the `SwupDebugPlugin` is in use (as one might expect in development), elements which were selected (eg: in `getAnimationPromises`) were logged to the browser console, so that you end up with something like:
```
> swup:animationOutStart
> Found out transition for <my element here>
> Found out transition for <my other element here>
> swup:pageLoaded
> swup:animationOutDone
> Resolved out transition for  <my element here>
> Resolved out transition for  <my other element here>
```
This would help massively where you might end up with, eg:
```
> swup:contentReplaced
> swup:pageView
> Got in transition for <my element here>
> swup:animationInStart
> .... nothing further.
```
I can see the `<my element here>` transition has caused an issue in some fashion, because I can tally up which ones were found and which ones never finished. I sit here _right now_ in that scenario, and I'm not entirely sure what's gone wrong, because the logging doesn't give me any indication.

Note that if the recommendation is to have 1 transition class (see #380) then at worst the debug log will only contain 2 extra lines per in/out pair, but if you've got multiple it'll help settle which ones aren't finishing.

**Comment by daun** [comment]
The latest release 2.0.17 has added warnings for missing containers and missing transitions and will gracefully handle containers without transitions. That should give people some pointers about where things went wrong.
