### ISSUE TITLE
Different Transition for Certain Pages

### ISSUE THREAD

**Issue by daniellelecomte** [swup/swup#382]
Hello! Love Swup - thanks so much for such a nice tool.

Is it possible to not have a transition occur when you are linking from one specific page to another? For instance, I am sliding in a background color on two pages on my site. BUT if I am on one of those two pages and click to the other one, I'd like the background to not exit or slide out, but rather stay in place. Here is an example of what I mean:

https://www.figma.com/proto/bWHeUvvRde9Wmpw8D5PUOS/Website?node-id=296%3A677&scaling=min-zoom&page-id=296%3A423&starting-point-node-id=296%3A475&show-proto-sidebar=1

You can see that when you are **Ideas** already and click to **Work**, the background stays in place.

I tried using the `to-[route of next page in URL friendly form]` option but  my page freezes if I then attempt to target the div with my transition class on it.

```
<a href="/work" class="anim-link" data-swup-transition="no-bg">Work</a>
<a href="/ideas" class="anim-link" data-swup-transition="no-bg">Ideas</a>

<div id="myBackground" class="my-transition-slide"></div>

.my-transition-slide {
    transition: 0.7s;
    right: calc(0% - 1.5rem);
    @apply w-full;
}

html.is-animating .my-transition-slide {
    @apply right-0 w-6;
}

html.is-leaving .my-transition-slide {
    transition: 0.7s;
    @apply right-0 w-5;
}

html.to-no-bg .my-transition-slide {  // same as static state
     right: calc(0% - 1.5rem);
     @apply w-full;
}
```

Any suggestions would be greatly appreciated! TIA.

**Comment by daun** [comment]
Not sure if you've found a solution by now — I'd suggest handling this outside of the swup lifecycle, i.e. use one separate div not used by swup for the background, add a simple css transition on its width, and then show or hide that background div depending on a body class like `template-work` or `template-ideas`.

**Comment by daun** [comment]
This is now possible using the official [route name plugin](https://github.com/swup/route-name-plugin). By default, it will add a `to-same-route` class to the `html` tag that will allow you to modify or disable your transitions when navigating between two pages of identical types.
