### ISSUE TITLE
Load stylesheet from body on contentReplaced

### ISSUE THREAD

**Issue by MathiasOxholm** [swup/swup#388]
Hi, Im having a problem with loading stylesheets on contentReplaced in Swup.js in WordPress.

**A quick background for the problem:**
- I'm using WordPress + ACF Gutenberg Blocks
- Every block uses wp_enqueue_style(), which loads only the CSS stylesheet if the block is used on a given page.

The problem is the fact that ACF injects the stylesheet right before the body closing tag, and not in the head. So the Swup head plugin does not load it on contentReplaced. There is currently no support in ACF for changing where the stylesheet is injected.

![Screenshot 2021-10-13 at 15 42 02](https://user-images.githubusercontent.com/17880711/137144559-e977daca-8c62-447f-9ca4-853ee8c9f0af.png)

Any ideas on how to load the stylesheets on contentReplaced?

**Comment by AugustMiller** [comment]
I can't find any evidence of `wp_enqueue_style()` outputting stylesheets outside the `head` element… so there may be a larger issue in play than we can diagnose, here. As best I can tell, styles are output during the `wp_head` hook, which is (usually) right before the closing `<head>` tag. Is this present in your theme/template's `header.php` file?

That said, `link` tags that are injected as part of a container/fragment ought to be evaluated just fine. Are you able to use the entire `body` as your container?

**Comment by daun** [comment]
Closing this since the problem seems to lie with Wordpress. Feel free to comment if you found a solution.
