### ISSUE TITLE
Cannot set properties of null (setting 'responseURL')

### ISSUE THREAD

**Issue by CHolitas** [swup/swup#397]
So I was using Swup and for some strange reason it decided to stop working, I used the exact thing that the Demo page told me but anything works, on my `<html>` tag, doesn't appear the `class="swup-enabled"` and if I enter a link the page animates but the content doesn't appear until I refresh

**Here is what the console told me**:
`Cannot set properties of null (setting 'responseURL')`

This is the js file
```javascript
const swup = Swup();
```
Can someone help me please?

**Comment by daun** [comment]
Usually that's because the container element is missing a `transition-*` class or it's missing completely from the new page's html response.
