### ISSUE TITLE
Trying to work with Fullpage,js

### ISSUE THREAD

**Issue by TisMeStoobo** [swup/swup#402]
I'm using Swup with Fullpage.js, and boy, do they not play nice!

Is there a way to use Swup enabled on a div inside the body rather than on the HTML tag? I think this will resolve a lot of my issues as Fullpage uses height from the DOM, but Swup creates a fake DOM?

Thank you :D

**Comment by daun** [comment]
If you read through the swup docs again, you'll notice that swup doesn't operate on the html tag nor does it create a fake dom. Getting fullpage.js to work with ajax-powered transition libraries like swup is a bit messy but it's definitely doable. Check out issue #369 for some pointers.

**Comment by sonicgeoffmonkey** [comment]
For completeness and to help anyone else attempting something similar, I worked with @TisMeStoobo to get a basic demo running. After many variations here's the code we ended up with:
```
function init_fullpage() {
	$('#fullpage').fullpage({
		//options here
	});
};

$(document).ready(function() {
	init_fullpage();
});

const swup = new Swup();

swup.on('willReplaceContent', function() {
	fullpage_api.destroy('all');
});

swup.on('contentReplaced', function() {
	init_fullpage();
});
```
As @daun mentioned on the link above it helped to put this code in an external JS file (it's neater that way anyway) and to wrap the init code in a function which can be called on page load and after the content has been replaced by SWUP.

**Comment by daun** [comment]
Good to know you've made it work and thanks for the example!
