### ISSUE TITLE
Event for the first load of a site

### ISSUE THREAD

**Issue by laleikeCO** [swup/swup#404]
hi there,

is there an event for the very first load of a site, when no transition has fired at this point. I want create a kind of automatic presentation and for the first load via swup.loadPage() i need this event.

pageLoaded works not for me.

Thanks, Thomas

**Comment by AugustMiller** [comment]
Unless I'm mistaken, this can just be handled in a regular JS event listener, or even colocated with your Swup initialization logic?

Swup will apply (and remove) an `is-animating` class to the `<html>` element when performing a navigation—you can also add this class to your HTML document and remove it as soon as you've initialized the page:

```html
<html class="is-animating">
    <head>
        <title>Example</title>
        <script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>

        <style>
            .transition-fade {
                transition: 0.4s;
                opacity: 1;
            }

            html.is-animating .transition-fade {
                opacity: 0;
            }
        </style>
    </head>

    <body>
        <div id="swup" class="transition-fade">Hello, world!</div>
    </body>

    <script>
        // Initialize Swup:
        const swup = new Swup();

        // Pull class off of the root element whenever you're ready, to unhide the page (or start any other animation):
        window.setTimeout(() => {
            document.documentElement.classList.remove('is-animating');
        }, 1000);
    </script>
</html>
```
