### ISSUE TITLE
Variable value is not displayed in the tag after Swup Transition.

### ISSUE THREAD

**Issue by CodersRage** [swup/swup#405]
Hello Brothers,
I am a newbie 17 year old web designer and facing some issue with my content been not completely been loaded after page transition. What I have been designing was an input taking system in the form of a quiz game. The problem is that when the user reaches the result page, the result is being processed correctly but not displayed after the swup page transition and when i reload the same page, it displays the calculated variable value in the form of a string in my p-tag been targeted by its id in javascript. What i want is that the result value should be displayed normally after the page transition not requiring a page reload to make it happen. Being a newbie to use this library. The problem I can think of is that onload function is not trigerring on page transition but when i reload the page it works and displays the result, on contrary to this i want the result to be displayed just after the transitioning instead of reloading the page or adding an onclick function on a button and then displaying the result, i dont want this as it doesn't suit my needs. So i need some help in this matter. Anybody's collaboration is highly appreciated.
I specially want @gmrchk brother to take a look into this, hope i get his assist in this matter.

**Comment by AugustMiller** [comment]
Please have a look through [these references and issues](https://github.com/swup/swup/discussions/334) about Swup's requirements for reloading or re-initializing Javascript, and let us know if you need any more guidance!
