### ISSUE TITLE
Swup caches rendered state of Alpine.js components instead of initial html

### ISSUE THREAD

**Issue by hirasso** [swup/swup#419]
**Describe your issue**:

Swup's cache is caching the rendered state of my [Alpine.js](https://alpinejs.dev/) components instead of the initial one. That makes them break badly if I navigate back to them (through either `popState` or `linkClick`). Here's a very simple component that doesn't make much sense, but illustrates the issue quite well I think. It renders the three entries of it's Alpine-`x-data` directive:

```html
<!-- ... -->
<div id="swup">
  <ul x-data="{ entries: ['entry1', 'entry2', 'entry3' ]}">
    <template x-for="entry in entries"> 
      <li x-text="entry"></li>
    </template>
  </ul>
</div>
<!-- ... -->
```
I would expect to see exactly that inside `swup.cache.getCurrentPage().originalContent`, but I see this instead:

```html
<!-- ... -->
<div id="swup">
  <ul x-data="{ entries: ['entry1', 'entry2', 'entry3' ]}">
    <template x-for="entry in entries"> 
      <li x-text="entry"></li>
    </template><li x-text="entry">entry1</li><li x-text="entry">entry2</li><li x-text="entry">entry3</li>
  </ul>
</div>
<!-- ... -->
```
See how the rendered content from alpine is there in the cache (last line before the closing `</ul>` tag)?

If set `{cache: false}`, it works as expected, but I would really like to be able to use the cache...

**Swup config or any additional relevant code used**:

This is how I initialize my script:
```js
import Swup from 'swup';
import Alpine from 'alpinejs';
window.Alpine = Alpine
Alpine.start()
const swup = Swup({
  cache: true
});
```

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better? *If it really helps, I could set up an example on my server. But I think the issue should be easily reproducible.*

**Comment by hirasso** [comment]
Found the issue. Swup needs to be initialized before anything else alters the `DOM`:

```js
import Swup from 'swup';
import Alpine from 'alpinejs';
// first initialize Swup:
const swup = Swup({
  cache: true
});
// ...then initialize Alpine and anything else that would alter the DOM:
window.Alpine = Alpine
Alpine.start()
```

**Comment by daun** [comment]
@hirasso Another option is to empty the cache manually after the initial page load. That way, the order of initialisation doesn't matter and you can still e.g. load swup in an async bundle to optimize Time to Interactive.

```js
  // Create new swup instance
  const swup = new Swup({
    ...defaults,
    ...options
  })

  // Empty cache so the first view isn't cached with modified dom
  swup.cache.empty()
```
