### ISSUE TITLE
Formidable Forms with swup (no ajax submission or validation)

### ISSUE THREAD

**Issue by dayneh88** [swup/swup#420]
Hi,

Not sure if anyone has run into this issue or could maybe provide some solutions but I am running the excellent form builder, Formidable Forms on a Wordpress website.

I've successfully integrated swup and everything is working fine except for the contact form.

Formidable Forms has an option to submit the form with AJAX  and to also validate the form with javascript. This works fine if the page which contains the form is the 1st page loaded, but if the user loads the homepage and then goes to the Contact page the validation and submission via ajax no longer works. It reloads the page on submission.

Here is an example site: https://soocd.com.au/ where you can test out the experience for yourself.

I've seen examples of getting other form builders like Ninja Forms, Gravity Forms and Contact Form 7 to work as they have an init function in javascript.

You can also add a google captcha field to your forms but it doesn't show unless the page with the form is the page that is initially loaded.

Any help would be greatly appreciated.

Thanks,
Dayne

**Comment by daun** [comment]
@dayneh88 Did you find a solution to your problem? Sounds like you need more control over how and when the form plugin initiates and re-initiates.

**Comment by dayneh88** [comment]
@daun Nope. Still no solution. There doesn't seem to be any manual init() function for Formidable Forms like there is with Ninja/Gravity Forms. Very very frustrating.

**Comment by daun** [comment]
:(

**Comment by daun** [comment]
I'll go a head and close this since this is not a problem specific to swup. Feel free to comment here if you find a solution in case anyone else stumbles onto this issue.
