### ISSUE TITLE
Wordpress + swup.js

### ISSUE THREAD

**Issue by Paweuek** [swup/swup#429]
Hello,

I have ran into an issue when I have separate javascript file for every page. On page load it loads js files only for that specific page and when i go onto other it doesn't load js files enqueued for next page.

Right now the only solution I can see is to enqueue all libraries for the whole page and combine all custom js files into one. I'd rather not do that. Is there any other solution?

**Comment by daun** [comment]
Not sure if you've come across the [Q&A on reloading javascript](https://github.com/swup/swup/discussions/334), but that might give you some pointers.
