### ISSUE TITLE
Swup not working :/

### ISSUE THREAD

**Issue by FatKappa** [swup/swup#431]
My animation isn't working. May i have your help?

HTML

![image](https://user-images.githubusercontent.com/59336336/168928578-97fcabc6-1031-4104-bee4-10bb1309b918.png)

CSS

![image](https://user-images.githubusercontent.com/59336336/168928601-b768d9fd-6829-422d-8992-83e62021b333.png)

**Comment by sparrow001** [comment]
"a" link elements have to start with "/".  Your links do not have this and instead just list the file name. If you want to change this, check out [https://swup.js.org/options#link-selector](this)
