### ISSUE TITLE
does swup work with tailwind css?

### ISSUE THREAD

**Issue by GabrielPedroza** [swup/swup#439]
Very straightforward question: does swup work with tailwind css?

**Comment by daun** [comment]
Sure. Since Tailwind uses `transition-*` utility classes, you have to use a different naming scheme for your page transition classes in swup. See the docs on the [animation selector option](https://swup.js.org/options#animation-selector).

``` js
// Configure swup to use page-transition-* classes to avoid clashes with Tailwind's transition-* classes
const swup = new Swup({
  animationSelector: '[class*="page-transition-"]'
});
```
