### ISSUE TITLE
Swup breaks when animation-class and directory named the same

### ISSUE THREAD

**Issue by tobisalad** [swup/swup#444]
I just spent several hours trying to find out why my very minimalistic swup-setup didn't work until I finally found what I believe is a very weird and apparently unknown bug: 
**When the directory your files are in is named the same as your animation-class then swup breaks.**
(by break I mean it fades out but never gets to the AnimationOutDone-Event and thus never transitions to another page)

In my case I had my files in a webroot-subdirectory `/transition/`, thus my links were of the form `href="/transition/page.html"`, and I was working with the default animation-class `transition-*`. I confirmed this behavior by renaming both my directory and animation-class to something else and it was still broken, as soon as the two are not named the same it would work again.

**Comment by daun** [comment]
That's definitely a bug. Swup adds `to-*` classes to the `html` tag to allow switching animations between different subpages. If the URL of the next page contains the word _transition_, it will find the class it just added itself and wait for a transition on the `html` tag — which will never happen.

Setting a custom selector for the animations should solve this however. If you add `html` before the actual selector, swup will only look for transitioned elements inside the `html` tag.

```js
const swup = new Swup({
  animationSelector: 'html [class*="transition-"]'
})
```

**Comment by daun** [comment]
Fixed in [2.0.17](https://github.com/swup/swup/releases/tag/2.0.17)

**Comment by daun** [comment]
@tobisalad The workaround above will stop working in the new version as all selectors will now be scoped to the `body`.

**Comment by tobisalad** [comment]
Thanks! :-)
