### ISSUE TITLE
2 types of transitions for other link selectors

### ISSUE THREAD

**Issue by bielze** [swup/swup#451]
I'm loving Swup so far, very slick! I made a pretty cool page transition with swup.js but I want to use it only for specific links. I want another more basic transition, like the standard one for the rest of the links on my site. I'm trying two swup constants but it's not working. I'm not sure if it's even possible. Here's the js:

```
const options = {
    containers: ['.site-content'],
    animationSelector: '[class*="transition-"]'
};
const swup = new Swup(options);

const optionsB = {
    linkSelector: '#menu-item a',
    containers: ['.site-content'],
    animationSelector: '[class*="simpletrans-"]'
};
const swupB = new Swup(optionsB);
```

**Comment by gmrchk** [comment]
Great to hear @bielze, thanks! 

You can do that using the combination of [route specific classnames](https://swup.js.org/getting-started/how-it-works) assigned to the HTML tag by swup automatically, and the page specific classes on body replaced by the [body class plugin](https://swup.js.org/plugins/body-class-plugin). It usually works the best to setup the basic transition for all the pages, and then overwrite it for specific pages.

**Comment by daun** [comment]
I'll close this for now; let us know if the route classnames and the body classes haven't been enough to solve your issue.

**Comment by bielze** [comment]
Thanks for the reply and suggestion and sorry for taking so long to respond. I was trying to solve it myself but I think I'm stuck on the CSS part.

I'm using the body swap plugin:
```
const options = {
	plugins: [new SwupBodyClassPlugin()]
};
const swup = new Swup(options);
```

And have a link with 
`data-swup-transition="forest"`

I see the difference in the body when clicking the link with the forest data attribute but I'm not sure how to override the default transition with css..

**Comment by daun** [comment]
You'll want to check for a `to-forest` class on the html tag and change your transition type and duration based on that. I'll quote the docs:

> Custom class can be also added by adding `data-swup-transition` to the link, where `to-[content of data-swup-transition attribute]` is added to html. Class can be used to change animation for different URLs.
