### ISSUE TITLE
This library is a bit of a nonesense!

### ISSUE THREAD

**Issue by hn1** [swup/swup#456]
Try an use this library with **ANY** framework and **ALL** comes crashing down like 1000 nuclear bombs!
What a waste of time!!!

**Comment by daun** [comment]
Your comment is a bit of a nonsense 🤡 I'll go ahead and close this for trolling. Feel free to come back when you're ready to contribute productively.

**Comment by hn1** [comment]
Sorry you don't like honest criticism. But when you put out stuff like this, people like us actually trust your integrity and devote time to trying and using it only to find out that it was a COMPLETE waste of time!

It may be better if you found yourself another profession. Coding is definitely not your calling. Again sorry for the honesty.
