### ISSUE TITLE
Simplify code formatting

### ISSUE THREAD

**Issue by daun** [swup/swup#468]
- [x] Add npm script for running prettier (#470)
- [x] Create .editorconfig for whitespace (#470)
- [x] Autoformat incoming PRs in CI

**Comment by hirasso** [comment]
Great work! Maybe we could save ourselves the autoformatting in the CI if we just call `npm run lint` from the `build` script?

**Comment by daun** [comment]
@hirasso Not sure about adding the lint step to the build script. Ideally, we'd be able to enforce the lint as a pre-commit step. That way, incoming PRs without built dist files would be linted as well.

Incidentally, I'd love to get rid of the build step altogether, i.e. we could stop tracking the dist files in the repo and generate them before npm publish. That way, only npm and unpkg have them and we can stop worrying.

**Comment by hirasso** [comment]
This sounds like a very good plan. 👍
