### ISSUE TITLE
TypeScript definitions 

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#486]
Ideally, first-class support for TS would be implemented, not just manually defined types. 

https://github.com/swup/swup/issues/238

**Comment by hirasso** [comment]
To be able to reason about the best way of doing this, I added a draft PR for the `scroll-plugin`, that generates a declaration file based on JSDoc comments: https://github.com/swup/scroll-plugin/pull/35

**Comment by daun** [comment]
I'll add it here as a sidenote but will include it in the PR: microbundle has TS support built in with no extra setup, should we decide to take that route in the future.

**Comment by hirasso** [comment]
Comment about porting directly to TypeScript: https://github.com/swup/scroll-plugin/pull/35#issuecomment-1222159318

**Comment by pTinosq** [comment]
Any updates on this? Would love to implement Swup into my Electron + TS project.

**Comment by daun** [comment]
@pTinosq Yes, this is currently being worked on and should be released later this week as part of swup 3.0
