### ISSUE TITLE
New Re-captcha plugin

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#489]
Plugin to refresh/fill reCaptcha on the transitioned-to pages.

**Comment by phederal** [comment]
+

**Comment by daun** [comment]
A loader library like [AurityLab/recaptcha-v3](https://github.com/AurityLab/recaptcha-v3) could be a way to get up and running quickly.

**Comment by daun** [comment]
Closing this for now as there doesn't seem to be a strong requirement for implementation.
