### ISSUE TITLE
New bundler

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#490]
We've talked about replacing the bundler to allow some easier work. The webpack setup is also outdated in basically all repositories including Swup core and plugins. 

We've agreed that we would try:
- [x] @gmrchk to create PR with updated webpack config in the Swup core. 
- [x] @daun to create PR with replaced bundler providing some more straightforward setup.

**Comment by gmrchk** [comment]
This would ideally also solve #487.

**Comment by daun** [comment]
@gmrchk I've created two draft PRs for both versions: #492 and #493. Feel free to check out both locally and test them. We can also move the discussion to slack.

**Comment by daun** [comment]
Waiting for release in 3.0
