### ISSUE TITLE
Issue between version 2.0.16 and 2.0.18

### ISSUE THREAD

**Issue by aragorn-be** [swup/swup#494]
Hi,
For an unknown reason, a part of my website does not work anymore with the "latest" version 2.0.18... After having clicked on a hyperlink, the pointing page was loaded but not rendered by the web engine (tested with Chrome and Edge). Clicking on F5 does the job however.
Finally I had to force my web page to use version 2.0.16...
You can test it here: https://ipeswavre.be/jpov/se_former/secteurs/index.html

**Comment by daun** [comment]
I think not all of your pages have the swup container `#swup` defined. The index page has `<main id="swup">`, but the following pages have only `<main>` without the id. Swup has always required that the number of containers stay the same across all pages, but we've recently changed how this is handled, sometimes forcing a reload, sometimes aborting. Can you confirm that the problem goes away if you add the `swup` id everywhere?

**Comment by daun** [comment]
@aragorn-be I'll close this for now, pending confirmation that you're still seeing the issue after making the suggested adjustments.

**Comment by aragorn-be** [comment]
Yes !! Sorry for the late answer. Not tested the suggested solution but
this sounds logic for me.

Thanks a lot

Jean-Marc


Le lun. 29 août 2022 à 19:35, Philipp Daun ***@***.***> a
écrit :
