### ISSUE TITLE
Can't get svg xlink working

### ISSUE THREAD

**Issue by bielze** [swup/swup#500]
Sorry for creating a issue for this but I can't seem to find how to include xlink in the link selector. Found some pointers here on github and stackoverflow but it's not working for me.

I have this as the link selector:
`linkSelector: 'a[href=".."], a[href^="' + window.location.origin + '"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]), a[xlink\\:href]'`

And this is a link inside the svg:
`<a xlink:href="/link"></a>`

**Comment by daun** [comment]
SVG links are tricky since the `xlink:` is a valid namespace and needs special treatment.

`[*|href]` should work here.

**Comment by bielze** [comment]
Perfect, would not have figured that on out myself, thanks!
