### ISSUE TITLE
console logs `A soft navigation has been detected.`, even without `DebugPlugin`

### ISSUE THREAD

**Issue by Enteleform** [swup/swup#509]
**Description of the issue**

![image](https://user-images.githubusercontent.com/10906415/188480743-b253dccd-6dcb-473a-ac9b-77fd2727ab2c.png)

**How to reproduce the issue**
- Clone [swup/swup-gia-demo](https://github.com/swup/swup-gia-demo)
- Remove `DebugPlugin` from `./src/js/app.js`
- Build & Run

**Context and environment**
- Windows 10
- Chrome
- Edge

**Comment by daun** [comment]
That log statement is from [Chromium](https://github.com/D3PSI/vivaldi/blob/3d6b16a2d3f31e7cd02f0620cf7097644c44e9f5/chromium/third_party/blink/renderer/core/timing/soft_navigation_heuristics.cc#L111), not swup or a plugin. Not sure how to disable it, I guess adjusting the debug level should work.

**Comment by Enteleform** [comment]
@daun Ah, gotcha. How did you find that?

I tried quoting it @ Google but got:
> No results found for "A soft navigation has been detected".

**Comment by daun** [comment]
> Ah, gotcha. How did you find that?

GitHub search returned 2 results 🤠

**Comment by Enteleform** [comment]
> GitHub search returned 2 results 🤠

Oh weird... that was showing 0 results too, but it did load the 2 results you mentioned after clicking it anyway 🤔.

![image](https://user-images.githubusercontent.com/10906415/188496012-7f105868-3629-4bed-94cc-55dfc4d568c7.png)

Just ran the search a few times and it's finally showing the correct result count 🙃.

Welp... thanks for the info!
