### ISSUE TITLE
Script at bottom of the page not being added/executed

### ISSUE THREAD

**Issue by timcensus** [swup/swup#517]
I have a website with Swup, it works great except for one problem. When I navigate to a page with different scripts in the bottom of the page (just before closing the body tag), they won't load. 

I have implemented the SwupScriptsPlugin, but this doesn't fix the problem.
How can I force Swup to load the new scripts?

```js
const swup = new Swup({
    plugins: [
        new SwupBodyClassPlugin(),
        new SwupHeadPlugin(),
        new SwupScrollPlugin({
            doScrollingRightAway: true,
            animateScroll: false,
            scrollFriction: 0,
            scrollAcceleration: 0,
        }),
        new SwupScriptsPlugin(),
    ],
    linkSelector:
    'a[href^="' + window.location.origin +'"]:not([data-no-swup]):not([href^="#"])'
});
```

**Comment by daun** [comment]
Hi @timcensus, this is a common issue that has been answered a number of times. I'll close this as a duplicate and refer you to a Q&A discussion about the topic of [Reloading JavaScript](https://github.com/swup/swup/discussions/334). If you think this is a problem with the scripts plugin, please open an issue on its repository with a full example. Feel free to fork this [CodeSandbox test case template](https://codesandbox.io/s/swup-test-case-template-6ci5si) to create a reproducible test case.
