### ISSUE TITLE
Update cache with changes made to the DOM

### ISSUE THREAD

**Issue by drivebass** [swup/swup#530]
1. I'm using ajax requests to load html content into div containers. 
2. Upon success of the ajax request I'm trying to update swup cache with `cacheUrl()` to keep the changes.
3. When i leave the page and go back the changes are gone and it loads without the previously added content.

Is it possible to update the current page cache with the changes made to the DOM so they'll be available when going back to the page? 

`success: function (e) {
	$current = swup.cache.getCurrentPage();
	swup.cache.cacheUrl($current);
}`

**Comment by daun** [comment]
Have you tried the above code? I think it should work as expected.

**Comment by drivebass** [comment]
Hey @daun thank for your feedback. 
Unfortunately I've spent the past 2 days trying to make this work. 
I have seen mentioned here that swup is caching from the server but according to @gmrchk comment here [https://github.com/swup/swup/issues/316#issuecomment-733956234](url)  it is possible to update the cache manually, but there are no further details. 

From what I understand you have to remove the page cached from the server by swup. 
And then cache the exisiting content. I noticed that the helper getDataFromHtml is possibly the solution to include like this: 

`			const page = getDataFromHtml(
				document.documentElement.outerHTML,
				this.options.containers
			);
			page.url = page.responseURL = getCurrentUrl();
			this.cache.cacheUrl(page);`

But it doesn't work, as I get an error that getDataFromHtml is not a function or it is undefined. Furthermore there is no detailed documentation for the helpers and specifically for getDataFromHtml.

**Comment by drivebass** [comment]
This is where I'm stuck now:

`success: function (e) {
	swup.cache.remove(swup.getCurrentUrl());
	const page = getDataFromHtml( document.documentElement.outerHTML, swup.options.containers ); 
	page.url = page.responseURL = getCurrentUrl();
	swup.cache.cacheUrl(page);
}`

**Comment by daun** [comment]
Swup had something similar until a while ago, manually saving the current DOM state into the cache on first load. We disabled it to avoid caching modified DOM, but it sounds like that's exactly what you're aiming for. Try this:

```js
import swup from 'swup';
import { getDataFromHtml, getCurrentUrl }  from 'swup/lib/helpers';

const page = getDataFromHtml(document.documentElement.outerHTML, swup.options.containers);
page.url = page.responseURL = getCurrentUrl();
swup.cache.cacheUrl(page);
```

As you can see, it's an obscure helper and not something that should be documented until we make it easier to use.

**Comment by daun** [comment]
Ah, yes, you're close, just missing the helper imports.

**Comment by drivebass** [comment]
Hey @daun,
Many thanks for the follow up!
I'm a bit lost with the "imports" because I just use jquery and include minified swup in a plugins folder. I haven't used imports before. Isn't 'getDataFromHtml' included in swup.min.js? 'getCurrentUrl' works fine without imports. 
Thanks in advance!

**Comment by daun** [comment]
They're both [exported](https://github.com/swup/swup/blob/master/dist/swup.js#L157), so if `getCurrentUrl` is available as a global function, `getDataFromHtml` should be as well. That said, I haven't used the UMD version of swup in a long while so you're probably right that it isn't there.

**Comment by drivebass** [comment]
getCurrentUrl is working fine.


getDataFromHtml is returning “not a function” error though.

**Comment by drivebass** [comment]
getCurrentUrl is working fine.
getDataFromHtml is returning a “not a function” error though.

**Comment by drivebass** [comment]
I finally made it to work by including the required helper files' code in addition to swup.min.js code.
I noticed that when i included the gethtmldata.js code in my plugins.js file after the swup.min.js, I had an error of undefined query and queryAll. I included those from utils folder and gethtmldata worked perfectly. getCurrentUrl broke though and I had to also include add the required js too. 

It's strange how it doesn't recognize the function via the main code swup.min.js and it needs everything additionaly. 
I'll have to check further but for now this worked, it even saves the last scrollposition out of the box!

```
const getCurrentUrl = () => {
  return window.location.pathname + window.location.search;
};

const getDataFromHtml = (html, containers) => {
  let fakeDom = document.createElement('html');
  fakeDom.innerHTML = html;
  let blocks = [];

  containers.forEach((selector) => {
    if (query(selector, fakeDom) == null) {
      console.warn(`[swup] Container ${selector} not found on page.`);
      return null;
    } else {
      if (queryAll(selector).length !== queryAll(selector, fakeDom).length) {
        console.warn(`[swup] Mismatched number of containers found on new page.`);
      }
      queryAll(selector).forEach((item, index) => {
        queryAll(selector, fakeDom)[index].setAttribute('data-swup', blocks.length);
        blocks.push(queryAll(selector, fakeDom)[index].outerHTML);
      });
    }
  });

  const json = {
    title: (fakeDom.querySelector('title') || {}).innerText,
    pageClass: fakeDom.querySelector('body').className,
    originalContent: html,
    blocks: blocks
  };

  // to prevent memory leaks
  fakeDom.innerHTML = '';
  fakeDom = null;

  return json;
};

const query = (selector, context = document) => {
  if (typeof selector !== 'string') {
    return selector;
  }

  return context.querySelector(selector);
};

const queryAll = (selector, context = document) => {
  if (typeof selector !== 'string') {
    return selector;
  }

  return Array.prototype.slice.call(context.querySelectorAll(selector));
};
```

**Comment by daun** [comment]
Great! I'll close this as done and will brainstorm a way to make this easier to accomplish out of the box. Might become a useful plugin to cache modified DOM as well.
