### ISSUE TITLE
Javascript wait for css animations to finish

### ISSUE THREAD

**Issue by kaspost** [swup/swup#558]
### Discussed in https://github.com/swup/swup/discussions/557

<div type='discussions-op-text'>

<sup>Originally posted by **kaspost** December 27, 2022</sup>
Basically, I'm coding an app with swup that primarily consists of transitions done through pure css. However, there are a few cases where some css properties need to be calculated through javascript before they are animated in. To solve this, my approach was to add the swup js plugin and use it like this:

  `
  new SwupJsPlugin([
      {
          from: '(.*)',
          to: '(.*)',
          in: prepareTransitions,
          out: prepareTransitions,
      },
  ])
  `

And the prepareTransitions function basically looks like this:

  `
  const prepareTransitions = next => {
      calcAndSetCssProperties();
      next();
  }
  `
  
The problem here becomes that swup doesn't wait for the animations to finish when switching between pages. This obviously has to do with the fact that next is invoked instantly after calcAndSetCssProperties. In order to solve this, is there a swup method that I can utilize to wait for all animations to finish and then invoke the next function?</div>

**Comment by hirasso** [comment]
You need to use `setTimeout(next, yourTransitionDurationInMilliseconds)` to wait for your transitions to finish.

**Comment by hirasso** [comment]
Closing this in favor of #557
