### ISSUE TITLE
Make swup agnostic of preload plugin

### ISSUE THREAD

**Issue by hirasso** [swup/swup#575]

**Comment by daun** [comment]
- Option A: Extract a `swup.getPageFetchPromise(url)` method (or similar) that the preload plugin can overwrite
- Option B: Turn `swup.preloadPromise` into a `swup.fetchPromises` array that the preload plugin can append to

Option A is much more flexible and has the advantages of making the fetch mechanism pluggable (e.g. replace `xhr` with `fetch` or `axios`) and allowing custom cache implementations.
