### ISSUE TITLE
Update plugins for v3

### ISSUE THREAD

**Issue by daun** [swup/swup#590]
**Description**

- Some plugins use helpers exported from swup
- We'll need to update those to require the next version
- Also port the plugin base class to microbundle

**Required update for compatibility**

All these require helpers and have to be ported on launch:

- [x] [plugin base class](https://github.com/swup/plugin) → [PR](https://github.com/swup/plugin/pull/13)
- [x] [forms-plugin](https://github.com/swup/forms-plugin) → [PR](https://github.com/swup/forms-plugin/pull/40)
- [x] [preload-plugin](https://github.com/swup/preload-plugin) → [PR](https://github.com/swup/preload-plugin/pull/57)
- [x] [route-name-plugin](https://github.com/swup/route-name-plugin) → [PR](https://github.com/swup/route-name-plugin/pull/6)
- [x] [scroll-plugin](https://github.com/swup/scroll-plugin) → [PR](https://github.com/swup/scroll-plugin/pull/44)

**Not required now**

These only use events and don't directly import anything from swup.

- [ ] [head-plugin](https://github.com/swup/head-plugin)
- [ ] [matomo-plugin](https://github.com/swup/matomo-plugin)
- [ ] [a11y-plugin](https://github.com/swup/a11y-plugin)
- [ ] [progress-plugin](https://github.com/swup/progress-plugin)
- [ ] [scripts-plugin](https://github.com/swup/scripts-plugin)
- [ ] [js-plugin](https://github.com/swup/js-plugin)
- [ ] [gia-plugin](https://github.com/swup/gia-plugin)
- [ ] [body-class-plugin](https://github.com/swup/body-class-plugin)
- [ ] [debug-plugin](https://github.com/swup/debug-plugin)
- [ ] [ga-plugin](https://github.com/swup/ga-plugin)
- [ ] [gtm-plugin](https://github.com/swup/gtm-plugin)
- [ ] [livewire-plugin](https://github.com/swup/livewire-plugin)
- [ ] [custom-payload-plugin](https://github.com/swup/custom-payload-plugin)
- [ ] [recaptcha-plugin](https://github.com/swup/recaptcha-plugin)

**Example checklist for porting over a plugin**

- [ ] Switch `Link` class to `Location` class
- [ ] Use `swup.delegateEvent` helper
- [ ] Specify version requirements: `requires = { swup: '>=3.0.0' };`
- [ ] Add swup to `peerDependencies`
- [ ] Update package.json for output bundles
- [ ] Update dev dependencies: 
  - [ ] `npm remove @swup/webpack-config babel-cli babel-loader babel-preset-es2015 babel-preset-stage-0 webpack webpack-cli`
  - [ ] `npm install swup@plugin@2.0.0-rc.1`
- [ ] Add `swup` as peer dependency

**Comment by lpalombo** [comment]
Congrats on launch! I appreciate all of the hard work the team has put in to modernize this library. Can I request an update on @swup/head-plugin as well? The [PR opened by you](https://github.com/swup/head-plugin/pull/30) is working great on my side, but it'd make my little dev brain happy to be able to use a package rather than the dist. As far as I can tell that PR hadn't been merged because v3 hadn't been released yet.

**Comment by daun** [comment]
@lpalombo Working on it!

**Comment by daun** [comment]
@lpalombo Released 1.3.0 of the head plugin.

**Comment by lpalombo** [comment]
Thanks!
