### ISSUE TITLE
Improve encapsulation of swup core class

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#598]
**Description of the issue**

https://github.com/swup/swup/pull/597#discussion_r1082567170

Many of [these methods](https://github.com/swup/swup/blob/master/src/Swup.ts#L97-L118) are not intended to be used by the user, meaning they should be defined as `private` to the outside consumer. 

At the same time, we [use those methods in other](https://github.com/swup/swup/blob/master/src/modules/enterPage.ts#L7) files which are attached to the Swup instance. Unfortunately, TS considers that an outside usage, so we would be making the methods private for internal use also. 

There should be a better outside-facing API that is not that tightly connected with how we work with the Swup instance internally. 

**How to reproduce the issue**

**Context and environment**

**Before creating this issue...**

- [ ] Have you provided all helpful information available?
- [ ] Have you checked closed issues for similar/related problems?
- [ ] Have you considered creating a demo so we can help you better?

**Comment by daun** [comment]
Another idea could be to create a central [state machine](https://github.com/statelyai/xstate) for the whole page lifecycle that dispatches any calls to private methods. In that case, the private functions can be private and don't need to call any other private classes. They just update the state, and the state machine handles the required next step. One advantage would be less bugs and straightforward dealing with things like timeouts, aborted requests and server errors.

**Comment by gmrchk** [comment]
It's probably a bit of a TS limitation. The whole [first argument being this](https://github.com/swup/swup/blob/master/src/modules/enterPage.ts#L5) seems like a workaround to assigning the methods to the class from outside while telling TS what the `this` will be. I think the behavior is wrong, or at least limited, from the TS side - since this is the way to tell TS the method will be part of another instance, it should be basically assumed you can use the private methods just like from inside of class.

There was some [discussion about it](https://github.com/microsoft/TypeScript/issues/17694) previously, but I don't think they got to the bottom go it. 

I like the idea of the state machine; tho it's a bit hard to imagine how the implementation would look like.
