### ISSUE TITLE
Update version GH action gets stuck sometimes and doesn't run PR checks

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#614]
**Description of the issue**

Nothing more to add, not sure why would that happen. Pushing a new commit to the branch fixes it and triggers the GH workflows for checks. 

**How to reproduce the issue**

-

**Context and environment**

-

**Before creating this issue...**

- [ ] Have you provided all helpful information available?
- [ ] Have you checked closed issues for similar/related problems?
- [ ] Have you considered creating a demo so we can help you better?

**Comment by daun** [comment]
I think this got introduced with the recent addition of the lint step. Did we change anything about which GH actions are allowed to run or which and how they're required to run before a PR can be merged?

**Comment by gmrchk** [comment]
Nope don't remember changing anything other than separating the runs into two separate scripts in the GH action file. Let's take a look at what failed next time it happens.

**Comment by daun** [comment]
@hirasso This is solved, correct?

**Comment by hirasso** [comment]
I don't know really... haven't released a new version since the attempted fix

**Comment by daun** [comment]
I think this is working again.
