### ISSUE TITLE
Invalid referer header

### ISSUE THREAD

**Issue by mskocik** [swup/swup#616]
**Description of the issue**

Due to history handling logic, `referer` header is _always_ set to the current page being loaded.

As on image below I am requesting `/examples` from different page
![image](https://user-images.githubusercontent.com/25513620/216842139-533f6b76-140e-4d8a-b8cc-f3fdbab1b459.png)

**How to reproduce the issue**

Issue is clearly visible on swup homepage with javascipt enabled (you can compare with JS disabled, what headers are being sent)

Issue is present in v2-v3.

**Issue cause**

I believe that creating history record should be moved after the page fetch. But I haven't studied the rest of the code to fully understand the reasoning behind current implementation.
https://github.com/swup/swup/blob/343319c986d10506b2ee402c17d8b16cf49a5e1a/src/modules/loadPage.ts#L45-L52

**Severity**

Annoyance, one would expect to behave correctly. But can be worked around with custom request setting on `clickLink` event

**Comment by hirasso** [comment]
Hi @mskocik , I can confirm the described behavior on my end. This looks incorrect to me, too, I will look into it.

**Comment by hirasso** [comment]
@mskocik would you mind giving [this attempted fix](https://github.com/swup/swup/pull/617) a try? You can install the branch locally like this:
```
npm i swup/swup#fix-request-header-referer --save
```

**Comment by mskocik** [comment]
@hirasso any ETA on releasing this?

**Comment by hirasso** [comment]
@mskocik This has been fixed in [v3.0.5](https://github.com/swup/swup/releases/tag/3.0.5)
