### ISSUE TITLE
A few plugins are throwing an error on initialization

### ISSUE THREAD

**Issue by hirasso** [swup/swup#618]
I just noticed that when freshly installing one of `SwupBodyClassPlugin`, `SwupA11yPlugin` or `SwupProgressPlugin`, I am getting an error thrown in my console for each plugin, e.g.:

> Uncaught TypeError: _swup_body_class_plugin__WEBPACK_IMPORTED_MODULE_13__ is not a constructor

**Description of the issue**

Something seems to not be right with these plugins, I can't tell what yet. ScrollPlugin and PreloadPlugin don't throw the error.

**How to reproduce the issue**
```
npm i swup @swup/progress-plugin
```
```js
import Swup from "swup";
import SwupProgressPlugin from "@swup/progress-plugin";
new Swup({
  plugins: [new SwupProgressPlugin()],
});
```

**Context and environment**

WebPack 5, package `"type": "module"`. As a temporary workaround, this works without errors:

```js
import SwupProgressPlugin from "@swup/progress-plugin/dist/SwupProgressPlugin.js";
```
@gmrchk I guess this is happening due to the plugins still pointing towards `lib/index.js` in their `package.json`?

I also noticed that there are no GH releases for these plugins – how do we set them up exactly like ScrollPlugin and PreloadPlugin (automatic publish to NPM on release)?

**Comment by daun** [comment]
Seems to be an issue between microbundled core and non-microbundled plugins. I've tried that combination in webpack 4 and 5 successfully, so no idea what it might be. Could it be the "module" type in your project? Does it work without that?

**Comment by hirasso** [comment]
@daun just tested it, it really is related to `"type": "module"` in `package.json`! Do you have any idea how to fix it?

**Comment by daun** [comment]
In that case, it's an issue with the old plugin bundling method, so interop between webpack 4 and webpack 5 with module type resilution. No real idea how to solve this. Is there some kind of webpack interop setting or plugin to load "legacy" modules?

**Comment by hirasso** [comment]
Fun Fact: In another project that is also `"type": "module"` no errors are being thrown 🌀🤷‍♂️ ...I'm completely out of ideas here, maybe we should meet for a quick debugging session?

**Comment by daun** [comment]
@hirasso Have you been able to figure this one out?

**Comment by hirasso** [comment]
@daun not yet, have been quite busy with other things... Will check again tomorrow

**Comment by daun** [comment]
@hirasso Shall we close this?

**Comment by hirasso** [comment]
Yes
