### ISSUE TITLE
Auto-merge dependabot PRs

### ISSUE THREAD

**Issue by hirasso** [swup/swup#625]
What do you guys think about introducing a GH action for auto-merging dependabot PRs?

https://github.com/marketplace/actions/dependabot-auto-merge

A bit more work once, no more work later.

**Comment by daun** [comment]
Totally, I've been wanting to do this for a while. However, it seems like the dependabot alerts have become significantly less since switching away from the webpack setup? No harm done either way.

**Comment by daun** [comment]
Closing this for now as dependabot alerts have become very rare recently.
