### ISSUE TITLE
Should `createHistoryRecord` allow duplicate entries for the same URL?

### ISSUE THREAD

**Issue by hirasso** [swup/swup#634]
Right now, calling `createHistoryRecord` multiple times with the same URL will create multiple history records: 

```js
createHistoryRecord(getCurrentUrl());
console.log(window.history.length); // 3
createHistoryRecord(getCurrentUrl());
console.log(window.history.length); // 4
createHistoryRecord(getCurrentUrl());
console.log(window.history.length); // 5
```

To me this feels unintended. Should the function maybe check first if the URL was the same as in the browser before executing `pushState`? Or is there some valid use case I can't think of right now to allow history entries that will basically disable the browser history back button (it won't change the URL for all duplicate entries)?

**Comment by gmrchk** [comment]
This function doesn't seem to have any conditions on it, but we do seem to have certain conditions applied elsewhere before calling the function itself, like [here](https://github.com/swup/swup/blob/master/src/Swup.ts#L264). 
Did you encounter this "disabled back button" behaviour in some situations? 

While the function could have a safety-check like suggested, I think looking into the prerequisites would make better sense. Maybe there is a bigger problem/better fix in the code calling `createHistoryRecord`, and by applying the safety-check within, we would just hide the original problem instead.

**Comment by daun** [comment]
I tend to agree with @gmrchk. We should aim to keep this a small utility function that can be used and abused freely. I think calling history.pushstate without our helper would lead to the same result, in which case we're providing a plain wrapper function.

**Comment by hirasso** [comment]
> This function doesn't seem to have any conditions on it, but we do seem to have certain conditions applied elsewhere before calling the function itself, like [here](https://github.com/swup/swup/blob/master/src/Swup.ts#L264).
Did you encounter this "disabled back button" behavior in some situations?

I forgot to mention that I stumbled upon this problem when using `createHistoryRecord` directly in one of my sites. 

> I think calling history.pushstate without our helper would lead to the same result, in which case we're providing a plain wrapper function.

I'm also only guessing here – @gmrchk can you recall why you included the `state.random` key in the `pushState`? I read somewhere that this makes sure that `popState` will be fired even when staying on the same URL between two states that where pushed using `pushState`. I find this *very* hard to debug, since I have to open up a fresh browser window each time to start fresh...

Anyways, if both of you think that this should not be included in swup itself, I'll just do the check in my own code:

```js
import { createHistoryRecord, getCurrentUrl } from "swup";
/**
 * Creates a new history record only if the URL has changed
 * @param {string} url
 * @returns {boolean}
 */
function maybeCreateHistoryRecord(url) {
  // Bail early if the new url hasn't changed
  if (getCurrentUrl() === url) return false;
  createHistoryRecord(url);
  return true;
}
```

**Comment by daun** [comment]
Using `getCurrentUrl` is a bit dangerous here as it wouldn't include the hash, if I remember correctly.

**Comment by hirasso** [comment]
Right - to be sure one could use `getCurrentUrl(true)`
