### ISSUE TITLE
Plugins should extend types if they add methods

### ISSUE THREAD

**Issue by gmrchk** [swup/swup#640]
**Describe the proposed solution**

When using Swup, some plugins add methods on the instance with extra functionality. An example of this is `preloadPages ` method added by Preload Plugin. When such a method is added, the types of the instance don't reflect that, so the following will show a TS error.

```ts
const swup = new Swup({
  new SwupPreloadPlugin(),
});

// @ts-ignore needs to be ignored
swup.preloadPages(); 
```

The types of instance could be extended with the types defined in the plugin, so the instance reflects the true implementation. 

**Alternatives considered**

-

**How important is this feature to you?**

- [ ] Nice to have
- [ ] Would make my life a lot easier
- [ ] I cannot use swup without it

**Comment by daun** [comment]
Just stumbled upon this example repo as a demonstration how plugins can extend the types of a core library: alcuadrado/ts-plugin-system](https://github.com/alcuadrado/ts-plugin-system). The trick seems to be re-declaring the module:

https://github.com/alcuadrado/ts-plugin-system/blob/02b72119350799f24f1d9e48f83bae675e64ea2e/packages/plugin/src/type-extensions.ts#LL1C1-L13C2

This probably isn't news to @gmrchk, just leaving this here in case another maintainer decides to tackle this.

**Comment by daun** [comment]
This is solved in a technical sense: the two new modules written in TypeScript do this and it's working correctly.

```ts
declare module 'swup' {
  export interface VisitAnimation {
    /** Parallel visit: run in and out animation at the same time */
    parallel?: boolean;
  }
}
```

The part that's left open is porting all existing plugins over to TypeScript. That's another issue we can open.
