### ISSUE TITLE
`:target` not being applied during `samePageWithHash`

### ISSUE THREAD

**Issue by hirasso** [swup/swup#659]
**Description of the issue**

When clicking a hash link on a page, swup scrolls to the matching target element. But the `:target` selector doesn't have any effect.

**How to reproduce the issue**

This will paint the element `#my-element` red without swup enabled, but won't do anything with swup.

```html
<a href="#my-element">Scroll to my element</a>
<div id="my-element">This is my Element!</div>
<style>
:target {
    background: red;
}
</style>
```

I don't know if there is a solution for that. Google results are sparse. But thought I would note it here, in case someone stumbles upon a solution.

**Comment by daun** [comment]
I don't think you can specify an element to serve as `:target` via JS. Pushing a new history state entry might help. That would actually get swup closer to default browser behaviour which usually creates a new history entry for each anchor jump.

**Comment by hirasso** [comment]
Would you like to give that a try @daun?

**Comment by daun** [comment]
Honestly, no 🤡 I'm currently trying to breathe new life into the upgraded events/hooks system and potentially the fragment feature as well. Looking into this would just prove a distraction, I'm afraid.

**Comment by hirasso** [comment]
Haha ok fair enough. These other things sound far more interesting, indeed 👀

**Comment by hirasso** [comment]
Using `history.pushState` doesn't solve this either.

**Comment by daun** [comment]
:(

**Comment by hirasso** [comment]
Ended up emulating it using swup events: https://github.com/swup/docs/pull/117/commits/3301b8835e62ecdea2c756d17aa57b4c4afc043f

**Comment by daun** [comment]
Nice. I can imagine this becoming part of the scroll plugin. Maybe using `aria-current` but not sure if it supports made-up values like `aria-current="scroll-target"`...

**Comment by hirasso** [comment]
Right! Or maybe the a11y plugin?

**Comment by daun** [comment]
Good question — if we're making up a new property for styling, it's more on the scroll plugin side; if it has semantic value, I could see it in both.

This brings up another questions: do browsers move focus to the new anchor when anchor-jumping on a page?

**Comment by hirasso** [comment]
Seems like fitting `aria-current` values could be `location` or simply `true`. I worry that using that attribute could interfere with consumer-scripts, though (they may be using the `aria-current` attribute already to mark an active tab or the like). 

Maybe a simple `swup-scroll-target` or `swup-current-target` or `swup-hash-target` attribute would be less intrusive? In that case, it should be part of the Scroll Plugin, as you first suggested.

**Comment by hirasso** [comment]
All of the above with a `data-` prefix, of course :)

**Comment by daun** [comment]
Closing this in favor of [issue #53 on the scroll plugin](https://github.com/swup/scroll-plugin/issues/53).
