### ISSUE TITLE
Allow navigation to current location

### ISSUE THREAD

**Issue by opencoca** [swup/swup#735]
When users are handling forms, it would be elegant to allow both POSTing the same URL and clearing of form data by just visiting a link to the form. 

**Alternatives considered**

Developers can implement both form-clearing js code and have forms submitted to slightly different URLs than the forms.  IE using a ?dummy_key in the URL and/or a #optional_anchor allows for this functionality without any changes but is a little kludgy. 

**How important is this feature to me?**

- [x] Nice to have
- [x] Would make using swup lot easier for people who are getting started

**Comment by daun** [comment]
Welcome! This makes sense to support, I think. Just to understand your use case: how would you manage 'visiting a link to the form' and have it do a POST request? I assume by using `swup.loadPage()` as the same-page limitation is only in place when clicking links.

**Comment by daun** [comment]
I just had a look at the complexity of this and it's not very likely we'll implement this for the upcoming v4. The concept of ignoring visits to the current URL on link clicks is sort of baked into swup and not very easy to make configurable. This will likely end up in the next major release, though.

In the meantime: this should work as well, although you might end up seeing a scroll to the top, followed by a navigation:

```js
swup.on("samePage", () => {
  swup.loadPage({ url: window.location.href })
})
```

**Comment by daun** [comment]
We've given this a try and it turns out it's very doable! In the upcoming swup v4, you will be able to make swup following links to the current page by replacing the internal handler of the `link:self` hook:

```js
// Make swup follow links to current page
swup.hooks.replace('link:self', (visit) => swup.navigate(visit.to.url))

// Force browser to load links to current page
swup.hooks.replace('link:self', (visit) => window.location.href = visit.to.url)
```

In swup v3, the following should work, although you might end up seeing a scroll to the top, followed by a navigation:

```js
swup.on("samePage", () => swup.loadPage({ url: window.location.href }))
```

I'll close this as implemented.

**Comment by opencoca** [comment]
Thank you for this!
