### ISSUE TITLE
Suggest changes to this page links from the Documentation result in a 404 on GitHub

### ISSUE THREAD

**Issue by ovenum** [swup/swup#813]
**Description of the issue**
Clicking on the [Suggest changes to this page](https://github.com/swup/preload-plugin/blob/master/readme.md) on the Swup Preload plugin documentation will result in 404 on GitHub. 

The Url points to readme.md (lowercase) which does not exist inside the repo. Pointing to README.md will work as expected. I think the convention is to use the uppercase filename for README.md. So all Suggest changes links should point to that file?

Just checked a few more links from Plugin documentations, non of the contains a lowercase readme.md file.

**Comment by hirasso** [comment]
Thanks! Fix incoming :)
