### ISSUE TITLE
Rethink tests setup for official plugins

### ISSUE THREAD

**Issue by hirasso** [swup/swup#815]
**Describe the problem**

Right now, tests for plugins are included in swup's main package. This has the downside that it's hard to refactor plugins or create new features with confidence, as they can only be tested as soon as...

- the plugin is released
- some PR is being created for swup itself

I'd like to get together in a call and think about better solutions.

**Comment by hirasso** [comment]
After writing a test suite for [fragment-plugin](https://github.com/swup/fragment-plugin), I have developed a strong preference for doing the same for the other more complex plugins instead of testing them from the swup core. @daun what do you think?

**Comment by daun** [comment]
@hirasso 100%!

**Comment by daun** [comment]
I'm wondering — should we implement this by copy-pasting the setup from Fragment Plugin for now? Or should we think about a way of abstracting some of the setup/helpers/installation into re-usable actions and modules?

**Comment by hirasso** [comment]
Lets meet in a call and talk it through:)

**Comment by daun** [comment]
I'll close this in favor of #880 with a list of plugins to create tests for.
