### ISSUE TITLE
History navigation ignored when using custom link selector

### ISSUE THREAD

**Issue by mevanloon** [swup/swup#853]
### What did you expect? 🧐

I would have expected the page to load. 

### What actually happened? 😵‍💫

The anchor works, and navigating to the next page works. However, navigating *back* does not. It changed the URL to the one with the hash, but the contents remains the old.

### Swup and plugin versions 📝

- swup: 4.5.0

Note that this can be any link selector. *Including* a hash in the custom link selector seems to work around the issue.

### What browsers are you seeing the problem on? 🧭

Safari 17.2 (latest as of December 2023), Edge 120.

### URL to minimal reproduction 🔗

https://swup-reproduction-of-safari-bug.mevanloon.repl.co/

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by mevanloon** [comment]
A workaround is to add `a[href^="#"]` to your list of link selectors. Though that does mess up my scroll history.

**Comment by daun** [comment]
I think this is related to using a `linkSelector` of `.swup-link` and not applying it to every link. The first link in your markup doesn't have that class name, whereas the other link does. That would mean that the first anchor link will create a history entry whichswup doesn't recognize as its own, and hence ignores, not loading the content.

**Comment by daun** [comment]
To rephrase this a bit: if you set a custom link selector, any links that don't match that selector will be handled by the browser, and the browser will create the corresponding history entries. Swup only handles history entries it has created itself, to allow you as a developer to create custom history entries and handle them yourself. Going back in the history to an entry not created by swup will make swup ignore that history visit, as it could be one you want to handle yourself.

You have three options here:

1. Make sure every link on your site has a class of `swup-link`
2. Remove the custom link selector and use the [ignoreVisit](https://swup.js.org/options/#ignorevisit) option to opt some links out of swup navigations
3. Tell swup to handle all history entries by adjusting the [skipPopStateHandling](https://swup.js.org/options/#skippopstatehandling) option to `() => false`

**Comment by mevanloon** [comment]
That's a good point, and I understand the _why_ of this now; we explicitly tell Swup to not select links without the selector, so why would they even be looked at?

What I did was add a `a[href^="#"]` to my admittedly long list of selectors (it's full of `:not([data-no-swup]):not([href$="svg"]):not([href$="jpg"])`, maybe for legacy reasons by this point) to be able to handle it.

I did read the common issues page, but somehow must've skimmed over the part about history skipping. Can I request this case (links with anchors/hashes) be added to that section of the docs? If someone who skims over it sees a `#anchor-link`, they might recognize their issue faster.

**Comment by daun** [comment]
Yeah, I've tried to come up with a wording for what you're seeing to include in the docs. Mentioning anchor links directly is probably too specific – the main issue is link selectors that leave out part of the links on the page. Feel free to close this issue if the wording makes sense and once it's merged 🙃

By the way: here's an example for a slightly more "up-to-date" implementation of how to include and exclude certain links:

```js

const excludeUrls = [
  /^\/admin\//,
  /\.(pdf|zip|rar|docx?)$/i
]

const excludeSelectors = [
  '[data-no-swup]',
  '[target="_blank"]',
  '[download]'
]

const swup = new Swup({
  ignoreVisit: (href, { el } = {}) => {
    return excludeUrls.some((pattern) => pattern.test(href)) || el?.matches(excludeSelectors.join(', '))
  }
})
```

**Comment by daun** [comment]
We've updated the docs with this specific scenario. Thanks for helping us clarify this. I'll go ahead and close this issue, feel free to add your comments if something is unclear.
