### ISSUE TITLE
[Bug]: URL in `visit:start` inconsistent between normal and history visits

### ISSUE THREAD

**Issue by hirasso** [swup/swup#855]
### What did you expect? 🧐

`window.location` should be equal during `visit:start`, no matter if it's a normal or a history visit.

### What actually happened? 😵‍💫

Currently, the URL is being updated too late in the visit. That causes `window.location.pathname + window.location.search` during `visit:start` to be

- equal to `visit.from.url` for normal visits
- equal to `visit.to.url` for history visits

That can lead to logic errors in userland, since forgetting about history navigation is a common pitfall I cam imagine.

I noticed this while reviewing #850 .

### Proposed solution 💡

I'd like to move the history updating logic in `performNavigation` up, right before `visit:start`. To make it still possible to update the visit's `hash` on the fly as [done in this test](https://github.com/swup/swup/blob/c2107c67876d51acdf961909ce02dee4dff22db5/tests/functional/scrolling.spec.ts#L64), we'd need to update the hash after `visit:start` if it was changed.

Code from a quick test (takes care of updating the hash after `visit:start`):
```js
// store the original hash
const { hash } = visit.to;

// Create/update history record if this is not a popstate call or leads to the same URL
if (!visit.history.popstate) {
	// Add the hash directly from the trigger element
	const newUrl = visit.to.url + hash;
	if (visit.history.action === 'replace' || visit.to.url === this.currentPageUrl) {
		updateHistoryRecord(newUrl, { visit: visit.id });
	} else {
		this.currentHistoryIndex++;
		createHistoryRecord(newUrl, { visit: visit.id, index: this.currentHistoryIndex });
	}
}

await this.hooks.call('visit:start', visit, undefined);
visit.state = VisitState.STARTED;

// bail early if the visit was aborted
if (visit.done) return;

// Update the URL if the hash was changed on the fly
if (visit.to.hash !== hash) {
	updateHistoryRecord(visit.to.url + visit.to.hash);
}
```

### Swup and plugin versions 📝

- swup: 4.5

### URL to minimal reproduction 🔗

http://swup-test-url-during-visitstart.hirasso.repl.co/

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
I like the idea of having it behave the same in both scenarios. Ideally, it'd the other way around, with the current url always matching the `visit.from.url` -- which is impossible from how popstate events work, right?

This is going to be tough, given that we allow/encourage modifying the visit object on the fly. I'm currently working on project where I rewrite the url and decide whether to push or replace the url on a visit by the current history state and some attributes of the trigger element I have no control over. Need to check if this will break that behavior.

**Comment by daun** [comment]
What I dislike about this is that aborting a visit will always create orphaned history entries. Undoing the visit then becomes mandatory to avoid confusion from a url mismatch, whereas ideally aborting in or before visit:start would not modify anything.

**Comment by hirasso** [comment]
> I like the idea of having it behave the same in both scenarios. Ideally, it'd the other way around, with the current url always matching the visit.from.url -- which is impossible from how popstate events work, right?

Correct, sadly the URL will always already be the new one in `popstate`. Really feels a bit like a missing piece in the browser API, in my opinion. 

> What I dislike about this is that aborting a visit will always create orphaned history entries. Undoing the visit then becomes mandatory to avoid confusion from a url mismatch, whereas ideally aborting in or before visit:start would not modify anything.

I wouldn't worry about orphaned history entries too much, as the visit would be undone sometime during `animation:out` most of the time, anyways. And it would be the expected behavior anyways I'd suppose when undoing a visit.

> I'm currently working on project where I rewrite the url and decide whether to push or replace the url on a visit by the current history state and some attributes of the trigger element I have no control over. Need to check if this will break that behavior.

If that is the case, we should really keep the order as-is (history mutation after `visit:start`). I haven't heard of anyone complaining about it anyways, the information is all there in `visit.from` and `visit.to`, after all. I'll close this.

**Comment by daun** [comment]
Makes sense :) Interestingly, we're correctly mirroring the browser behavior, it's just unfortunately not very intuitive or useful.
