### ISSUE TITLE
[Bug]: New values in <head> are not updated

### ISSUE THREAD

**Issue by k16e-me** [swup/swup#874]
### What did you expect? 🧐

When navigating into a new page, I expect things like Title, Description, Canonical, and other Meta whose values are changing from page to page to change to reflect the values for the new page. 

### What actually happened? 😵‍💫

Now except for the title tag, none of these other values change unless the page is fully refreshed, bypassing Swup. This is not ideal. Since Swup knows to change the title tag and other dynamic contents, it should be able to detect same change for other tags and adjust their values accordingly. 

### Swup and plugin versions 📝

"swup": "^4.6.0"

### What browsers are you seeing the problem on? 🧭

Chrome

### URL to minimal reproduction 🔗

https://komponents-v2.netlify.app/

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment]
Have a look at head plugin: https://swup.js.org/plugins/head-plugin/

**Comment by k16e-me** [comment]
O, that was the solution after all. Thanks very much. [SOLVED]
