### ISSUE TITLE
[Bug]: [data-swup-ignore-script] issue with Contact Form 7 in Wordpress

### ISSUE THREAD

**Issue by NereaFontecha** [swup/swup#877]
### What did you expect? 🧐

I would like to add this [data-swup-ignore-script] to my contact-form-7 script , so i can access to the wpcf7 in each page. 
<img width="1490" alt="Screenshot 2024-02-15 at 15 45 12" src="https://github.com/swup/swup/assets/52252556/4fccee65-2dde-4228-9d63-165459372eff">

### What actually happened? 😵‍💫

I get this error when I change from one page without form to another page with form.
<img width="557" alt="Screenshot 2024-02-15 at 15 44 16" src="https://github.com/swup/swup/assets/52252556/639a57be-88a5-4481-ad40-600547ba82d2">

### Swup and plugin versions 📝

- swup: 4.5.1
-  swup/head-plugin: ^2.1.2

### Relevant log output 🤓

```shell
Swup.modern.js:22 Error in hook 'content:replace': DOMException: Failed to execute 'setAttribute' on 'Element': '[data-swup-ignore-script]' is not a valid attribute name.
    at r.runScript (webpack://rcs-wp-theme/./node_modules/@swup/scripts-plugin/dist/index.modern.js?:6:921)
    at eval (webpack://rcs-wp-theme/./node_modules/@swup/scripts-plugin/dist/index.modern.js?:6:763)
    at Array.forEach (<anonymous>)
    at r.runScripts (webpack://rcs-wp-theme/./node_modules/@swup/scripts-plugin/dist/index.modern.js?:6:747)
    at eval (webpack://rcs-wp-theme/./node_modules/swup/dist/Swup.modern.js?:22:3706)
    at new Promise (<anonymous>)
    at f (webpack://rcs-wp-theme/./node_modules/swup/dist/Swup.modern.js?:22:3678)
    at P.run (webpack://rcs-wp-theme/./node_modules/swup/dist/Swup.modern.js?:22:7461)
    at P.call (webpack://rcs-wp-theme/./node_modules/swup/dist/Swup.modern.js?:22:6930)
    at async _.N [as renderPage] (webpack://rcs-wp-theme/./node_modules/swup/dist/Swup.modern.js?:22:14822)
```

### URL to minimal reproduction 🔗

https://renewalclaistg.wpenginepowered.com/

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Removing the `[` and `]` should be enough here, the required attribute is just `data-ignore-script`.

**Comment by NereaFontecha** [comment]
If I remove it, the wpcf7 does not work.It does not work as it should the swup with Contact form 7

**Comment by daun** [comment]
The brackets aren't valid html markup and the browser is correct in throwing this error. I'll close this as it isn't a bug in the library. If you're having trouble getting the forms to submit, feel free to [create a new discussion](https://github.com/orgs/swup/discussions) describing your situation so others can help. If you suspect there's a bug with the forms plugin, feel free to create an issue on the [forms plugin repo](https://github.com/swup/forms-plugin).

**Comment by daun** [comment]
I'll point you to a few resources regarding the contact form 7 plugin: [issue 117](https://github.com/swup/swup/issues/117), [issue 352](https://github.com/swup/swup/issues/352), [wordpress support topic](https://wordpress.org/support/topic/not-compatible-with-swup/). Let us know if any of the proposed solutions helped solve your issue.
