### ISSUE TITLE
[Feature Request]: Add drop-in attribute to swap/replace content of elements outside the swup container

### ISSUE THREAD

**Issue by k16e-me** [swup/swup#884]
### Describe the problem 🧐

Currently, only contents within the swup container are swapped/replaced on new page entry. Anything outside is typically left alone. If the head plugin is used, things like title tag and other meta with changing contents get updated. But other than those, there isn't a way to just drop an attribute on a markup which then instructs Swup to watch for it when page changes and swap its content, much like you can drop in a "persist" attribute on an element and Swup knows to leave it alone when swapping pages. 

### Describe the propsed solution 😎

Provide a way with a simple attribute such as `data-swup-swap` or something along that line for Swup to watch for it when page changes and swap its content.

### Alternatives considered 🤔

None

### How important is this feature to you? 🧭

Would make my life a lot easier

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
You can have as many containers as needed: the [containers](https://swup.js.org/options/#containers) option accepts multiple selectors and isn't limited to a single one. Replacing a main content area as well as a navigation would look like this:

```js
const swup = new Swup({ containers: ['main', 'nav'] })
```

This would require that both containers are always available on all pages. To replace some containers only in certain conditions, you can [modify the containers](https://swup.js.org/visit/#dynamic-containers) for each visit in a hook:

```js
swup.hooks.on('visit:start', (visit) => {
  if (visit.to.url === '/about') {
    visit.containers.push('#sidebar')
  }
})
```

I'll close this as already implemented, but let me know if I misunderstood your feature request.

**Comment by k16e-me** [comment]
Yes, that explains it. So, it's to define in the script where you want Swup to "swap" content, etc. While doing `containers: ['#swup', '#page-title']` works inside the swup call. It'd still be nice to just drop a class/attribute inside the element and voila. But thanks for seeing me through.

**Comment by daun** [comment]
@k16e-me Exactly. The [morph plugin](https://github.com/daun/swup-morph-plugin) comes close to what you're suggesting, it also replaces parts of the pages marked with data attributes. The only "downside" is that it updates elements without animation. Depending on your use case, that might be okay however. It's mostly meant for permanent elements that need to update state or classes, like menus and footers.

```html
<nav data-swup-morph="nav">
  <!-- Morphed by the morph plugin -->
</nav>
<main id="swup">
  <!-- Replaced normally by swup -->
</main>
```

**Comment by k16e-me** [comment]
O, I'll look more into morph but might not use it for this case (especially needing to avoid any downsides).
