### ISSUE TITLE
[Idea]: New plugin for all route-related stuff

### ISSUE THREAD

**Issue by hirasso** [swup/swup#890]
### Describe the problem 🧐

Currently, we have three core plugins that are related to modifying the `visit` object based on routes. In order of complexity:

- [fragment-plugin](https://github.com/swup/fragment-plugin)
- [js-plugin](https://github.com/swup/js-plugin)
- [route-name-plugin](https://github.com/swup/route-name-plugin)

I see two issues with this situation:

- tedious setup for end users
- need for test duplication between the plugins

The two PROs I see: 

- bigger control over the bundle size for consumers.
- each plugin's task is clear and therefor easier to contribute to

### Describe the propsed solution 😎

Merge the three plugins into one: `@swup/routes-plugin`

```js
import Swup from "swup";
import SwupRoutesPlugin from "@swup/routes-plugin";

new Swup({
  plugins: [
    new SwupRoutesPlugin({
      routes: [
        {
          from: "(.*)",
          to: "(.*)",
          //... containers, name, scroll, focus, animations, ...
        }
      ]
    })
  ]
});
```

### Alternatives considered 🤔

Leave it as it is.

### How important is this feature to you? 🧭

Nice to have

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Interesting! I haven't yet used all three of them together, but I agree the overlap in routing functionality is a bit unfortunate. I'm not sure collapsing them into a single plugin would make it easier to explain this plugin to users (it now does animations + urls + dom fragments), but I'd love to explore this on a call sometimes and see where it takes us 🚀

**Comment by daun** [comment]
@hirasso After some time thinking about it, I'd vote for leaving these as three different plugins. It's quite convenient to point people in the right direction whenever they need JS animations, route classes or dynamic containers — merging them into a single plugin would make it harder for consumers to evaluate if this is the plugin they need for a specific task.

**Comment by hirasso** [comment]
Also, it would mean a lot of busywork on our end... I'm absolutely fine with leaving everything as-is.
