### ISSUE TITLE
[Feature Request]: Allow to control `options.linkToSelf` via callback function

### ISSUE THREAD

**Issue by hirasso** [swup/swup#900]
### Describe the problem 🧐

In more complex scenarios it can be beneficial to be able to control what behavior `options.linkToSelf` should have on a per-case basis. This is kind of related to https://github.com/swup/fragment-plugin/issues/80

The use case I'm having right now: I have a list of links on the left that open a detail on the right. If I click any link outside of `#detail` that leads to the already open detail, I want the detail to be reloaded. Otherwise, I want to scroll to the top.

### Describe the propsed solution 😎

```js
{
  linkToSelf: (visit) => visit.trigger.el?.closest('#detail') ? 'scroll' : 'navigate'
}
```

### Alternatives considered 🤔

---

### How important is this feature to you? 🧭

Would make my life a lot easier

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Interesting! Looks like we had that option and [decided to remove it](https://github.com/swup/swup/pull/759). Looking back, I still agree about removing this one — it seems like an edge case that ideally can be solved by a hook or two. Would the example below work in your use case?

```js
swup.hooks.before('link:self', (visit) => {
  swup.options.linkToSelf = visit.trigger.el?.closest('#detail') ? 'scroll' : 'navigate'
})
```

**Comment by hirasso** [comment]
Oops haha, that PR was even from myself 😅

Ok ok, I'm sure there was some good reasoning behind leaving it out.
