### ISSUE TITLE
[Bug]: Anchor link (href="#main") for skip to content functionality doesn't give focus to the linked element

### ISSUE THREAD

**Issue by Sidstumple** [swup/swup#954]
### What did you expect? 🧐

Simplified example:
```html
<body>
  <a href="#main-content" class="screen-reader-text">Skip to main content
  </a>

  <header class="site-header">
    <!-- Rest of your header code, like navigation menus, goes here -->
  </header>

  <main id="main-content">

    <h1>Heading</h1>
    <p>This is the first paragraph</p>

  </main>

</body>
``` 
(example from: https://www.a11y-collective.com/blog/skip-to-main-content/) 

I want to add a skip to content link for screenreader and keyboard dependent users; when I have swup activated the site will scroll to the main content but focus is not added to the main-content element, which means that the main navigation is still the next thing to focus.

### What actually happened? 😵‍💫

In this screenrecording you can see me first using a skip to content link **with** swup, after utilizing the skip to content link the focus is returned to the header. After I remove the swup initialization the skip to content link works as expected; after 'clicking' it it gives focus the first link inside the #main-content element, the codrops link.
https://github.com/user-attachments/assets/9528e93d-a3a4-477e-a9aa-c78755f79deb

### Swup and plugin versions 📝

- swup: 4.7.0

### What browsers are you seeing the problem on? 🧭

Chrome

### URL to minimal reproduction 🔗

https://codesandbox.io/p/devbox/great-ellis-3jmqxd

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Hi! We‘ve recently rewritten the official Accessibility Plugin to correctly focus anchor link targets. Can you try with that and report back?

**Comment by Sidstumple** [comment]
Hi Daun,

Thanks that seems to work! :) 

It seems to me that this is not just an accessibility enhancement, it's default behaviour for anchor links. Are there any plans to implement this everywhere?

**Comment by daun** [comment]
The „fix“ for this is rather complex to pull off cross-browser and reliably for screen readers, so we moved it into the Accessibility Plugin for now to keep the core bundle size in check. 

Long-term however we‘d love to bundle all the accessibility features into the core, also as a signal that they aren‘t considered optional.

**Comment by daun** [comment]
By the way, you can hook into `scroll:anchor` to make this work without using the a11y plugin:

```ts
swup.hooks.on("scroll:anchor", (visit, { hash }) => {
  const anchor = swup.getAnchorElement(hash);
  if (anchor instanceof HTMLElement) {
    focusElement(anchor);
  }
});
```

The `focusElement` function involves setting and restoring a tabindex:

```ts
function focusElement(el: HTMLElement) {
  // Apply a tabindex attribute to allow focusing non-focusable elements
  const tabindex = el.getAttribute("tabindex");
  el.setAttribute("tabindex", "-1");
  el.focus({ preventScroll: true });
  if (tabindex !== null) {
    el.setAttribute("tabindex", tabindex);
  } else {
    // Removing the tabindex will reset screen reader position, so we'll keep it
    // el.removeAttribute('tabindex');
  }
}
```

**Comment by daun** [comment]
I'll close this since the official way of enabling this at the moment is via the [Accessibility Plugin](https://github.com/swup/a11y-plugin).

Thanks for the pointer! I went ahead and added the inclusion of all a11y features in the core to the [project roadmap](https://github.com/orgs/swup/projects/3/views/1?pane=issue&itemId=80910041).

**Comment by Sidstumple** [comment]
Hi Daun, thanks! 

I really love Swup, great if this can be activated by default in the future, I understand maintaining a library is a lot of work!

Just keep in mind that accessibility improvements are often an enhancement for all users, not just those relying on assistive tech 🙏

**Comment by daun** [comment]
Totally with you on that! Tabbing through a website makes perfect sense for everybody.
