### ISSUE TITLE
[Feature Request]: Missing method on the docs!

### ISSUE THREAD

**Issue by bozdevs** [swup/swup#971]
### Describe the problem 🧐

1- In the API -> [Methods](https://swup.js.org/api/methods/), you have missing a method named of `scrollTo`.

### Describe the propsed solution 😎

You can add method to page.

### Alternatives considered 🤔

2- Develop `scrollTo` function to able to calculate given element scoll offset from top or bottom.

### How important is this feature to you? 🧭

Would make my life a lot easier

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

I ❤️ Swup.

**Comment by daun** [comment]
Hi, and thanks :) That method isn't part of swup itself, it's added when installing the Scroll Plugin. [There's a description of the method on the Scroll Plugin docs](https://swup.js.org/plugins/scroll-plugin/#methods-on-the-swup-instance). I'll close this for now, but feel free to chime in if you think that description is lacking!
